insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (488, 446, 87, 4, 3, '<script>alert(''hi'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (301, 251, 22, 1, 7, '사회과학원 어학연구소');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (171, 191, 42, 4, 4, '00˙Ɩ$-');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (301, 208, 65, 2, 10, '⁰⁴⁵');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (439, 343, 59, 3, 8, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (168, 84, 66, 4, 1, '1/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (195, 465, 78, 3, 6, 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (463, 355, 81, 4, 4, 'null');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (95, 325, 2, 2, 2, '⁰⁴⁵₀₁₂');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (339, 227, 27, 5, 1, ' test ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (10, 333, 3, 4, 1, '１２３');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (296, 330, 6, 3, 2, 'test⁠test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (249, 62, 55, 5, 10, '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (54, 203, 59, 1, 5, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (412, 283, 89, 3, 3, '''"''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (128, 226, 22, 4, 2, 'null');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (154, 116, 75, 4, 6, '1/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (444, 182, 32, 1, 5, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (107, 123, 2, 4, 1, '<>?:"{}|_+');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (453, 68, 76, 5, 10, '１２３');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (269, 195, 2, 2, 2, 'パーティーへ行かないか');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (256, 326, 71, 3, 5, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (150, 8, 99, 1, 8, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (72, 312, 83, 1, 5, ' ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (330, 59, 14, 4, 5, null);
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (54, 243, 33, 5, 5, '👩🏽');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (397, 27, 35, 5, 4, '__ﾛ(,_,*)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (163, 456, 51, 5, 6, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (301, 28, 83, 5, 1, '0.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (249, 424, 42, 3, 2, '<script>alert(''hi'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (238, 387, 76, 3, 10, '-1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (19, 167, 54, 3, 1, 'Œ„´‰ˇÁ¨ˆØ∏”’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (239, 10, 56, 2, 3, 'Ω≈ç√∫˜µ≤≥÷');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (231, 402, 97, 4, 10, 'null');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (70, 303, 7, 2, 10, '1;DROP TABLE users');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (254, 466, 30, 3, 4, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (325, 55, 73, 3, 7, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (271, 365, 81, 1, 3, '''"''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (239, 395, 65, 1, 1, '1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (422, 450, 42, 4, 2, '../../../../../../../../../../../etc/passwd%00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (242, 174, 50, 4, 6, '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (284, 189, 25, 5, 4, 'œ∑´®†¥¨ˆøπ“‘');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (263, 383, 17, 2, 3, 'nil');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (454, 152, 96, 3, 4, 'œ∑´®†¥¨ˆøπ“‘');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (451, 68, 60, 5, 8, '""');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (500, 48, 70, 1, 1, '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (123, 298, 1, 5, 3, 'パーティーへ行かないか');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (491, 144, 75, 3, 2, '␡');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (451, 345, 92, 4, 4, '<img src=x onerror=alert(''hi'') />');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (442, 101, 63, 2, 2, '"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (357, 280, 66, 3, 1, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (150, 64, 93, 2, 4, '0.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (388, 61, 21, 2, 10, '1');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (18, 331, 44, 2, 9, 'パーティーへ行かないか');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (3, 166, 82, 2, 3, '-1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (201, 79, 23, 5, 3, '1/2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (244, 453, 17, 1, 5, '1''; DROP TABLE users--');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (443, 291, 78, 5, 7, '١٢٣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (179, 61, 47, 1, 6, '1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (132, 226, 93, 4, 7, '(｡◕ ∀ ◕｡)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (263, 305, 64, 3, 7, '｀ｨ(´∀｀∩');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (313, 116, 41, 5, 7, '⁦test⁧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (18, 470, 54, 3, 1, '和製漢語');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (260, 233, 97, 4, 5, '١٢٣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (294, 482, 60, 5, 7, '사회과학원 어학연구소');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (486, 134, 27, 2, 10, 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (119, 114, 63, 5, 8, '١٢٣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (90, 352, 25, 4, 10, '和製漢語');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (272, 131, 79, 5, 1, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (329, 370, 60, 1, 9, '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (417, 494, 65, 5, 3, 'null');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (84, 72, 88, 1, 7, '1''; DROP TABLE users--');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (355, 158, 25, 2, 9, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (485, 343, 82, 5, 8, '"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (483, 393, 53, 4, 5, '1''; DROP TABLE users--');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (494, 69, 45, 2, 10, 'null');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (148, 275, 89, 4, 7, '🐵 🙈 🙉 🙊');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (47, 347, 62, 2, 4, '1/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (169, 169, 69, 3, 1, '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (220, 458, 57, 4, 8, '$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (320, 254, 75, 3, 6, null);
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (185, 236, 85, 2, 7, '␢');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (267, 416, 97, 3, 5, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (362, 4, 69, 4, 5, '　');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (14, 214, 75, 4, 4, '(╯°□°）╯︵ ┻━┻)  ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (496, 119, 36, 2, 10, '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (387, 323, 31, 5, 6, '-$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (143, 169, 51, 5, 8, '・(￣∀￣)・:*:');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (283, 173, 90, 2, 5, '␢');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (480, 311, 14, 2, 9, 'הָיְתָהtestالصفحات التّحول');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (118, 68, 89, 5, 7, '!@#$%^&*()');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (362, 371, 26, 1, 3, '"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (35, 395, 56, 4, 6, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (123, 81, 73, 4, 4, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (343, 359, 96, 4, 5, ',./;''[]\-=');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (128, 169, 41, 4, 6, '$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (36, 492, 16, 4, 9, '1/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (154, 297, 5, 4, 9, '１２３');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (152, 272, 55, 2, 6, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (419, 16, 35, 5, 3, '1''; DROP TABLE users--');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (276, 424, 2, 3, 1, '사회과학원 어학연구소');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (79, 466, 60, 5, 10, '｀ｨ(´∀｀∩');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (2, 96, 31, 1, 2, '・(￣∀￣)・:*:');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (433, 95, 81, 3, 2, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (156, 403, 75, 5, 2, '👩🏽');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (58, 369, 86, 3, 1, '!@#$%^&*()');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (307, 176, 45, 2, 1, '0/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (379, 277, 77, 1, 6, ' ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (107, 80, 64, 3, 4, 'åß∂ƒ©˙∆˚¬…æ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (402, 21, 41, 1, 6, '<>?:"{}|_+');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (89, 180, 7, 1, 10, '"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (224, 48, 3, 2, 3, '__ﾛ(,_,*)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (366, 172, 40, 1, 5, '1;DROP TABLE users');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (77, 266, 81, 5, 9, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (342, 282, 72, 1, 3, '"''"''"''''''''"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (390, 466, 81, 2, 8, '"''"''"''''''''"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (372, 393, 43, 4, 6, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (219, 80, 18, 3, 2, '1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (70, 132, 78, 1, 10, 'NULL');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (243, 422, 18, 5, 5, '␡');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (207, 442, 72, 2, 3, ',./;''[]\-=');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (257, 283, 7, 3, 6, '⁰⁴⁵₀₁₂');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (20, 251, 26, 1, 9, '울란바토르');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (374, 294, 83, 5, 6, '-1/2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (240, 329, 91, 5, 9, '-1/2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (443, 425, 37, 3, 3, '-$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (379, 416, 40, 1, 5, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (269, 135, 71, 5, 6, 'パーティーへ行かないか');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (312, 232, 36, 4, 4, '-1/2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (227, 152, 46, 1, 4, '"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (96, 290, 96, 4, 6, '(｡◕ ∀ ◕｡)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (88, 434, 66, 2, 9, ' ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (202, 268, 33, 1, 3, '田中さんにあげて下さい');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (428, 271, 47, 1, 8, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (340, 234, 58, 1, 9, '⁰⁴⁵');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (307, 362, 66, 4, 10, '""');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (26, 308, 32, 3, 6, ' test ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (239, 374, 29, 1, 10, '<img src=x onerror=alert(''hi'') />');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (279, 316, 43, 4, 7, '(╯°□°）╯︵ ┻━┻)  ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (259, 404, 43, 2, 10, '‫test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (208, 179, 11, 2, 2, 'ÅÍÎÏ˝ÓÔÒÚÆ☃');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (452, 137, 81, 2, 6, '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (245, 183, 22, 5, 7, '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (406, 145, 30, 2, 6, '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (243, 65, 52, 4, 5, '␢');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (344, 377, 64, 4, 3, 'Œ„´‰ˇÁ¨ˆØ∏”’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (258, 70, 63, 5, 3, '␡');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (31, 426, 89, 3, 5, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (206, 424, 74, 1, 7, '../../../../../../../../../../../etc/hosts');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (353, 437, 68, 4, 5, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (90, 403, 15, 3, 10, '　');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (82, 225, 45, 1, 3, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (153, 452, 11, 5, 9, '"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (176, 2, 93, 5, 10, 'パーティーへ行かないか');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (199, 423, 33, 5, 7, '0/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (362, 35, 22, 5, 2, '(｡◕ ∀ ◕｡)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (241, 409, 32, 2, 2, '１２３');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (74, 11, 36, 4, 7, 'Œ„´‰ˇÁ¨ˆØ∏”’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (140, 266, 39, 1, 6, '울란바토르');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (162, 228, 37, 1, 2, '<>?:"{}|_+');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (308, 423, 40, 5, 1, '울란바토르');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (396, 436, 49, 4, 5, '﻿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (241, 72, 100, 3, 6, '<img src=x onerror=alert(''hi'') />');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (70, 35, 57, 4, 10, 'åß∂ƒ©˙∆˚¬…æ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (87, 280, 44, 2, 10, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (395, 456, 53, 1, 6, 'ÅÍÎÏ˝ÓÔÒÚÆ☃');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (173, 423, 84, 4, 2, '﻿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (30, 147, 66, 4, 5, '<script>alert(''hi'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (180, 139, 47, 2, 5, '<script>alert(''hi'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (465, 204, 41, 5, 6, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (27, 141, 10, 5, 7, '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (411, 246, 26, 2, 8, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (65, 76, 21, 1, 1, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (206, 147, 52, 4, 9, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (113, 334, 53, 4, 1, '사회과학원 어학연구소');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (357, 258, 20, 5, 8, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (197, 455, 57, 3, 1, '1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (456, 185, 71, 3, 4, '-1/2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (401, 460, 45, 2, 8, '<svg><script>0<1>alert(''XSS'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (108, 172, 25, 4, 7, '‫test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (207, 468, 37, 2, 7, '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (232, 429, 24, 2, 7, '👩🏽');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (168, 176, 28, 1, 7, '⁦test⁧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (481, 403, 42, 1, 7, '1;DROP TABLE users');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (467, 446, 22, 3, 10, '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (84, 405, 16, 5, 6, 'ÅÍÎÏ˝ÓÔÒÚÆ☃');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (52, 420, 95, 4, 4, '｀ｨ(´∀｀∩');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (446, 351, 31, 1, 6, '<img src=x onerror=alert(''hi'') />');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (449, 133, 88, 4, 4, '1''; DROP TABLE users--');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (42, 348, 44, 3, 9, '👩🏽');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (85, 333, 72, 1, 6, '😍');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (40, 375, 79, 5, 6, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (499, 87, 36, 1, 3, '١٢٣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (442, 125, 55, 3, 7, 'Œ„´‰ˇÁ¨ˆØ∏”’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (115, 85, 91, 5, 7, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (21, 194, 49, 1, 9, '-1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (305, 322, 88, 5, 10, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (440, 448, 97, 4, 9, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (321, 19, 8, 1, 6, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (196, 307, 95, 4, 6, '｀ｨ(´∀｀∩');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (477, 253, 58, 5, 5, '(｡◕ ∀ ◕｡)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (327, 112, 83, 2, 1, '(╯°□°）╯︵ ┻━┻)  ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (140, 382, 97, 2, 4, '1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (476, 89, 51, 4, 4, 'test⁠test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (311, 380, 7, 1, 9, '␡');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (170, 249, 23, 1, 5, 'nil');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (476, 355, 62, 1, 4, 'œ∑´®†¥¨ˆøπ“‘');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (497, 84, 60, 5, 4, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (205, 341, 98, 4, 8, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (365, 80, 81, 5, 1, '﻿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (355, 178, 51, 5, 1, null);
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (59, 279, 96, 3, 4, '👩🏽');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (93, 329, 72, 2, 3, '1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (180, 412, 67, 3, 3, '사회과학원 어학연구소');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (251, 5, 16, 3, 3, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (114, 35, 43, 3, 9, '👩🏽');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (251, 362, 92, 4, 9, '␣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (407, 370, 42, 5, 5, '　');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (127, 36, 68, 3, 2, '사회과학원 어학연구소');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (433, 381, 31, 2, 7, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (109, 126, 50, 2, 1, '社會科學院語學研究所');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (79, 347, 31, 2, 1, 'test⁠test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (129, 2, 36, 4, 3, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (79, 327, 56, 2, 3, '᠎');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (243, 217, 95, 2, 3, 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (130, 263, 63, 5, 9, 'NIL');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (296, 384, 20, 5, 5, '␣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (371, 477, 72, 3, 6, '田中さんにあげて下さい');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (292, 243, 37, 1, 10, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (73, 425, 44, 5, 2, 'åß∂ƒ©˙∆˚¬…æ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (319, 201, 65, 3, 1, ',./;''[]\-=');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (90, 22, 58, 4, 3, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (23, 168, 81, 2, 3, '-1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (133, 104, 37, 3, 9, '''''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (260, 323, 43, 1, 2, '"''"''"''''''''"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (404, 481, 83, 5, 2, '・(￣∀￣)・:*:');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (187, 340, 80, 2, 7, '1''; DROP TABLE users--');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (115, 369, 67, 3, 8, '␣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (488, 141, 79, 4, 1, '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (203, 32, 51, 1, 3, '-1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (147, 382, 91, 3, 7, '１２３');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (183, 318, 73, 2, 6, 'הָיְתָהtestالصفحات التّحول');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (456, 446, 48, 3, 1, 'Ω≈ç√∫˜µ≤≥÷');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (359, 303, 32, 4, 5, '(｡◕ ∀ ◕｡)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (361, 228, 32, 1, 8, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (496, 10, 32, 2, 8, '᠎');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (372, 324, 77, 2, 9, '../../../../../../../../../../../etc/passwd%00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (480, 268, 37, 5, 7, '⁰⁴⁵');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (256, 126, 98, 5, 4, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (403, 319, 79, 2, 7, '　');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (489, 262, 68, 5, 10, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (145, 429, 73, 3, 9, '⁰⁴⁵');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (211, 263, 54, 4, 4, '¸˛Ç◊ı˜Â¯˘¿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (36, 358, 3, 4, 4, '-1');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (85, 202, 1, 3, 10, '00˙Ɩ$-');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (278, 179, 73, 4, 2, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (94, 120, 91, 3, 9, '$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (353, 129, 33, 4, 3, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (4, 468, 79, 4, 8, '田中さんにあげて下さい');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (407, 380, 84, 1, 7, 'nil');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (475, 454, 54, 1, 8, '🐵 🙈 🙉 🙊');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (192, 416, 22, 3, 3, '1''; DROP TABLE users--');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (301, 101, 91, 3, 7, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (148, 309, 91, 1, 5, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (394, 174, 19, 4, 6, '-1/2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (78, 330, 89, 2, 8, '社會科學院語學研究所');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (194, 61, 50, 1, 8, '1');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (49, 65, 93, 4, 3, '␣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (231, 186, 25, 1, 2, '1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (342, 246, 16, 1, 4, '　');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (421, 132, 13, 2, 3, '<>?:"{}|_+');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (242, 180, 88, 2, 1, '🐵 🙈 🙉 🙊');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (159, 448, 33, 3, 8, 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (400, 351, 39, 5, 9, '¡™£¢∞§¶•ªº–≠');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (440, 466, 56, 4, 10, '¸˛Ç◊ı˜Â¯˘¿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (340, 491, 50, 4, 2, '⁰⁴⁵₀₁₂');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (427, 26, 22, 5, 1, 'Ω≈ç√∫˜µ≤≥÷');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (260, 418, 71, 4, 8, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (84, 292, 84, 5, 10, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (393, 462, 34, 5, 7, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (74, 165, 23, 2, 6, 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (363, 23, 98, 3, 5, '''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (489, 234, 79, 2, 10, '00˙Ɩ$-');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (214, 223, 46, 3, 3, '1');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (158, 106, 8, 2, 1, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (209, 72, 45, 2, 10, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (251, 492, 46, 3, 4, '../../../../../../../../../../../etc/passwd%00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (331, 217, 83, 5, 6, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (317, 354, 86, 5, 3, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (383, 468, 82, 1, 4, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (485, 221, 32, 4, 6, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (347, 453, 6, 5, 7, '<script>alert(''hi'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (24, 378, 76, 2, 6, '1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (191, 373, 11, 4, 2, '0/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (166, 322, 27, 4, 9, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (403, 339, 93, 5, 4, '-1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (157, 485, 61, 5, 5, '　');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (310, 132, 31, 1, 8, '-1');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (412, 422, 78, 4, 10, '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (106, 286, 68, 2, 8, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (299, 160, 83, 4, 2, 'test⁠test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (127, 34, 85, 3, 10, 'パーティーへ行かないか');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (125, 22, 63, 1, 3, '(╯°□°）╯︵ ┻━┻)  ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (187, 48, 91, 2, 4, '1/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (62, 341, 5, 4, 5, 'Œ„´‰ˇÁ¨ˆØ∏”’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (54, 199, 74, 5, 10, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (122, 113, 96, 2, 7, '​');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (157, 115, 75, 3, 5, '1;DROP TABLE users');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (318, 307, 67, 4, 5, '""');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (194, 331, 2, 1, 7, '␣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (297, 461, 95, 2, 10, '1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (487, 404, 88, 3, 2, 'パーティーへ行かないか');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (50, 378, 1, 2, 5, '1''; DROP TABLE users--');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (367, 84, 69, 2, 1, '1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (8, 225, 2, 3, 8, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (32, 73, 50, 3, 4, '<script>alert(''hi'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (185, 385, 37, 1, 7, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (142, 238, 83, 3, 5, '-1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (343, 466, 52, 2, 2, '<script>alert(''hi'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (439, 324, 97, 2, 9, '田中さんにあげて下さい');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (228, 224, 2, 3, 1, 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (449, 185, 44, 3, 7, '‫test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (163, 433, 51, 1, 4, '¸˛Ç◊ı˜Â¯˘¿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (120, 335, 64, 5, 10, '﻿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (31, 166, 76, 1, 5, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (49, 383, 38, 5, 2, '<>?:"{}|_+');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (314, 309, 83, 5, 1, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (285, 462, 30, 1, 9, '../../../../../../../../../../../etc/hosts');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (156, 202, 2, 4, 5, '-1');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (2, 93, 53, 5, 4, '"''''''''"''"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (62, 39, 67, 1, 9, '""');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (222, 16, 87, 5, 7, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (230, 216, 71, 1, 10, 'NIL');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (490, 420, 38, 5, 6, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (286, 151, 29, 5, 2, 'NULL');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (429, 326, 53, 3, 7, '¡™£¢∞§¶•ªº–≠');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (144, 472, 34, 4, 5, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (370, 53, 87, 1, 1, 'Ω≈ç√∫˜µ≤≥÷');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (333, 458, 1, 5, 8, '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (300, 232, 28, 1, 2, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (492, 125, 19, 4, 2, '"''''''''"''"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (213, 330, 95, 2, 7, '⁰⁴⁵');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (253, 343, 19, 5, 2, 'パーティーへ行かないか');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (235, 221, 46, 5, 10, '울란바토르');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (212, 109, 69, 2, 8, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (209, 451, 92, 3, 3, '(｡◕ ∀ ◕｡)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (187, 248, 22, 4, 4, '../../../../../../../../../../../etc/hosts');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (253, 110, 54, 4, 10, '｀ｨ(´∀｀∩');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (422, 391, 35, 4, 8, '‪‪test‪');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (316, 40, 79, 4, 1, '"''''''''"''"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (487, 361, 17, 3, 9, '👩🏽');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (365, 326, 27, 1, 7, '(╯°□°）╯︵ ┻━┻)  ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (29, 346, 72, 1, 6, '👩🏽');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (345, 185, 95, 5, 2, '　');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (402, 468, 2, 3, 2, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (268, 284, 30, 3, 8, '‪‪test‪');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (109, 319, 59, 3, 2, '../../../../../../../../../../../etc/hosts');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (462, 86, 10, 3, 7, '₀₁₂');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (57, 10, 9, 1, 6, 'œ∑´®†¥¨ˆøπ“‘');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (362, 154, 23, 2, 4, 'NIL');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (453, 241, 100, 2, 10, null);
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (314, 448, 6, 1, 6, 'NIL');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (130, 21, 77, 2, 3, '␣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (64, 345, 62, 2, 2, '1;DROP TABLE users');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (202, 279, 57, 3, 8, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (103, 88, 76, 3, 6, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (120, 51, 66, 5, 5, '../../../../../../../../../../../etc/hosts');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (156, 336, 51, 2, 8, '和製漢語');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (496, 394, 74, 2, 10, '''''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (72, 82, 1, 4, 9, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (102, 474, 70, 3, 5, '''''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (291, 336, 32, 1, 2, '١٢٣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (38, 138, 44, 3, 2, '١٢٣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (80, 23, 29, 5, 3, '1''; DROP TABLE users--');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (364, 277, 87, 4, 8, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (21, 212, 46, 5, 10, '""');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (155, 473, 42, 3, 9, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (23, 376, 38, 4, 7, '-$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (425, 320, 17, 2, 9, '../../../../../../../../../../../etc/hosts');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (281, 85, 41, 1, 6, '¸˛Ç◊ı˜Â¯˘¿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (281, 137, 91, 3, 9, '0.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (307, 62, 98, 2, 6, '₀₁₂');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (356, 489, 95, 1, 8, ' ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (170, 347, 58, 1, 2, '""');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (11, 61, 90, 2, 4, '¡™£¢∞§¶•ªº–≠');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (249, 425, 1, 5, 8, 'œ∑´®†¥¨ˆøπ“‘');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (7, 364, 89, 4, 1, '１２３');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (141, 216, 57, 5, 2, '1/2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (308, 432, 61, 4, 9, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (48, 316, 32, 2, 10, '-$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (114, 412, 7, 3, 2, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (87, 353, 45, 4, 8, 'œ∑´®†¥¨ˆøπ“‘');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (33, 357, 15, 2, 6, '田中さんにあげて下さい');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (374, 239, 82, 1, 9, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (175, 219, 26, 4, 9, '␢');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (173, 495, 48, 1, 4, '᠎');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (475, 118, 98, 5, 6, '__ﾛ(,_,*)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (316, 397, 4, 2, 8, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (407, 115, 32, 2, 2, '1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (225, 47, 46, 5, 2, '᠎');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (77, 133, 21, 3, 10, '😍');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (222, 41, 1, 1, 6, 'NIL');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (170, 148, 54, 1, 3, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (446, 362, 99, 1, 3, '../../../../../../../../../../../etc/passwd%00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (242, 456, 54, 2, 8, '1''; DROP TABLE users--');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (66, 62, 74, 2, 8, '0.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (227, 285, 23, 5, 2, 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (96, 87, 94, 5, 6, '😍');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (476, 15, 69, 4, 4, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (382, 224, 53, 3, 8, '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (12, 224, 94, 4, 8, '"''''''''"''"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (364, 19, 96, 5, 6, '⁰⁴⁵₀₁₂');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (54, 417, 51, 1, 8, 'הָיְתָהtestالصفحات التّحول');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (418, 340, 71, 1, 9, '1/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (222, 227, 43, 1, 2, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (439, 246, 60, 5, 5, 'הָיְתָהtestالصفحات التّحول');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (175, 28, 38, 2, 7, '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (60, 132, 6, 1, 5, '🐵 🙈 🙉 🙊');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (248, 407, 91, 2, 4, '-1/2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (222, 271, 97, 1, 10, '(╯°□°）╯︵ ┻━┻)  ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (198, 96, 46, 1, 3, '👩🏽');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (110, 219, 7, 4, 1, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (378, 238, 23, 3, 2, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (267, 365, 48, 1, 5, '﻿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (456, 293, 94, 4, 3, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (324, 399, 97, 5, 5, '"''"''"''''''''"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (114, 233, 9, 2, 8, 'Œ„´‰ˇÁ¨ˆØ∏”’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (360, 137, 36, 1, 1, 'test⁠test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (212, 309, 14, 2, 2, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (468, 190, 56, 2, 10, '1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (448, 406, 4, 4, 6, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (259, 345, 86, 3, 7, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (127, 249, 18, 4, 2, null);
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (472, 378, 14, 3, 10, '1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (148, 60, 90, 2, 7, '-1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (348, 308, 2, 1, 1, '(╯°□°）╯︵ ┻━┻)  ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (295, 20, 59, 3, 3, '1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (145, 333, 9, 4, 3, null);
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (44, 499, 73, 2, 8, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (9, 370, 10, 4, 8, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (433, 18, 41, 4, 2, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (198, 448, 48, 1, 4, 'ÅÍÎÏ˝ÓÔÒÚÆ☃');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (413, 344, 73, 5, 2, '''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (375, 116, 14, 3, 9, '1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (148, 348, 84, 3, 6, '-$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (140, 275, 88, 4, 2, '-$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (128, 340, 50, 5, 2, '<script>alert(''hi'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (69, 21, 7, 3, 5, '﻿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (102, 92, 2, 1, 4, 'nil');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (493, 11, 64, 2, 4, 'הָיְתָהtestالصفحات التّحول');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (266, 134, 42, 5, 5, 'パーティーへ行かないか');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (303, 469, 49, 4, 4, '和製漢語');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (60, 85, 29, 2, 2, '␣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (296, 142, 74, 1, 7, '__ﾛ(,_,*)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (13, 142, 21, 2, 5, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (129, 134, 47, 2, 10, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (113, 239, 84, 1, 3, '␡');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (55, 287, 73, 3, 7, '-$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (378, 54, 33, 5, 7, '$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (33, 410, 71, 1, 3, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (207, 74, 7, 1, 3, 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (331, 108, 67, 2, 4, '""');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (439, 295, 49, 5, 7, '울란바토르');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (218, 236, 45, 3, 5, '1;DROP TABLE users');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (24, 318, 6, 1, 10, '1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (370, 307, 55, 4, 3, '"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (496, 130, 35, 4, 8, '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (2, 264, 70, 2, 1, '␡');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (472, 494, 23, 3, 8, '''''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (293, 320, 95, 4, 6, '・(￣∀￣)・:*:');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (355, 359, 20, 5, 1, '¸˛Ç◊ı˜Â¯˘¿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (211, 363, 35, 3, 7, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (221, 82, 94, 4, 8, '᠎');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (315, 488, 21, 2, 10, '00˙Ɩ$-');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (492, 175, 26, 1, 9, 'åß∂ƒ©˙∆˚¬…æ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (208, 362, 90, 3, 3, '・(￣∀￣)・:*:');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (97, 11, 22, 1, 10, '😍');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (402, 210, 89, 5, 7, '🐵 🙈 🙉 🙊');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (80, 294, 35, 3, 9, '社會科學院語學研究所');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (130, 87, 82, 4, 1, '../../../../../../../../../../../etc/hosts');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (7, 177, 22, 4, 5, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (14, 127, 8, 2, 4, '・(￣∀￣)・:*:');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (194, 178, 13, 5, 3, '$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (113, 240, 32, 4, 4, '👩🏽');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (239, 409, 35, 1, 2, 'הָיְתָהtestالصفحات التّحول');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (455, 313, 25, 4, 6, '''"''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (457, 373, 17, 3, 9, '田中さんにあげて下さい');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (376, 55, 9, 2, 1, '<>?:"{}|_+');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (418, 443, 60, 5, 3, '$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (163, 397, 42, 5, 3, '1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (423, 146, 77, 3, 10, '0.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (194, 496, 25, 5, 10, '"''"''"''''''''"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (319, 63, 62, 4, 2, 'Ω≈ç√∫˜µ≤≥÷');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (360, 424, 84, 2, 5, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (174, 191, 5, 4, 9, ' ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (274, 416, 23, 2, 3, 'הָיְתָהtestالصفحات التّحول');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (278, 171, 6, 5, 6, 'åß∂ƒ©˙∆˚¬…æ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (357, 472, 18, 4, 6, '1');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (260, 233, 78, 4, 4, '<img src=x onerror=alert(''hi'') />');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (15, 264, 10, 4, 1, '../../../../../../../../../../../etc/hosts');
