insert into direccion (linea1, ciudad, comunidad, pais) values ('950 Derek Plaza', 'New York City', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('96339 Carey Point', 'Mc Keesport', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('9212 Bunker Hill Alley', 'Birmingham', 'Alabama', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6 Reinke Junction', 'Buffalo', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('48 Sutherland Court', 'Las Vegas', 'Nevada', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('336 Redwing Terrace', 'Kansas City', 'Missouri', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('9098 Hintze Crossing', 'Evanston', 'Illinois', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5 Arapahoe Hill', 'Portland', 'Oregon', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('367 Manley Avenue', 'Fresno', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('35302 Northfield Road', 'New Haven', 'Connecticut', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0271 Ridgeview Parkway', 'Saint Louis', 'Missouri', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('919 Schlimgen Point', 'Chattanooga', 'Tennessee', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('63507 Packers Plaza', 'Arlington', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('80 Birchwood Trail', 'Berkeley', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('76 Iowa Plaza', 'Kansas City', 'Missouri', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8072 Steensland Park', 'El Paso', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('537 Chive Alley', 'San Diego', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('42 7th Road', 'Boston', 'Massachusetts', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('815 Anthes Road', 'Salt Lake City', 'Utah', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('437 Carberry Junction', 'Washington', 'District of Columbia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('553 Caliangt Pass', 'Kansas City', 'Missouri', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('22 Swallow Street', 'Trenton', 'New Jersey', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('670 Reindahl Lane', 'Mesa', 'Arizona', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('39042 Roxbury Alley', 'Minneapolis', 'Minnesota', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4 Del Sol Road', 'Wichita Falls', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('82867 Del Mar Terrace', 'Fort Lauderdale', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('19 La Follette Park', 'Dayton', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('78816 Vidon Circle', 'Lansing', 'Michigan', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('604 Delaware Place', 'El Paso', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2235 Duke Circle', 'Minneapolis', 'Minnesota', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('89011 Maryland Park', 'Roanoke', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('06371 Elgar Junction', 'Mobile', 'Alabama', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('68 Iowa Crossing', 'Arlington', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('7 Brown Center', 'Bronx', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('77 Dwight Park', 'Colorado Springs', 'Colorado', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('433 Fallview Hill', 'Baltimore', 'Maryland', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4 Havey Drive', 'New York City', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('195 Crest Line Circle', 'Springfield', 'Missouri', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('90 Elgar Crossing', 'Las Vegas', 'Nevada', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1 Paget Drive', 'Spartanburg', 'South Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5065 Esch Trail', 'Seattle', 'Washington', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1 Warbler Hill', 'Yonkers', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('68 Service Center', 'Jacksonville', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('13758 Mendota Place', 'Indianapolis', 'Indiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('62 Morrow Hill', 'Austin', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('890 Lakeland Pass', 'Houston', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5 Petterle Avenue', 'Albuquerque', 'New Mexico', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('78149 Northport Terrace', 'Portland', 'Oregon', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('53 Tomscot Trail', 'Macon', 'Georgia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1656 Armistice Road', 'Spring Hill', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('24 Debra Way', 'Jacksonville', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3 Union Drive', 'Houston', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2216 Myrtle Pass', 'Tulsa', 'Oklahoma', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8 Annamark Avenue', 'Fort Worth', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3814 Colorado Park', 'Arlington', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1 Ridgeview Crossing', 'Los Angeles', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('22536 Oriole Trail', 'Erie', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('803 Texas Drive', 'Washington', 'District of Columbia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('984 Ridge Oak Way', 'Lexington', 'Kentucky', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('21 Vidon Drive', 'Abilene', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4 Warrior Plaza', 'Staten Island', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('124 Homewood Drive', 'Worcester', 'Massachusetts', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0001 Coleman Street', 'Long Beach', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0 Heffernan Court', 'Shawnee Mission', 'Kansas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0 Lillian Point', 'Hartford', 'Connecticut', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('02895 Clemons Road', 'Columbus', 'Georgia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('22 Ruskin Crossing', 'Newport News', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('83 Lerdahl Place', 'San Antonio', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4476 Lawn Crossing', 'Rochester', 'Minnesota', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('431 Amoth Trail', 'Huntsville', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('9 Monterey Park', 'Temple', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('38 Bartillon Court', 'Atlanta', 'Georgia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5048 Mandrake Center', 'Memphis', 'Tennessee', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8 Melrose Drive', 'Los Angeles', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1271 Cherokee Circle', 'Charlotte', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('43902 Fair Oaks Point', 'Nashville', 'Tennessee', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3 Cardinal Avenue', 'Maple Plain', 'Minnesota', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('25 Troy Hill', 'Berkeley', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8209 1st Alley', 'Detroit', 'Michigan', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('56 Sunnyside Road', 'Englewood', 'Colorado', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0 Fulton Drive', 'Tucson', 'Arizona', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8 Surrey Crossing', 'Atlanta', 'Georgia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('28 Orin Way', 'Cheyenne', 'Wyoming', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('53 Porter Hill', 'East Saint Louis', 'Illinois', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('702 Vera Terrace', 'Washington', 'District of Columbia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('048 Troy Alley', 'Roanoke', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8168 Golf View Junction', 'Lake Worth', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('9992 Aberg Court', 'Orlando', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('34 Graceland Avenue', 'Austin', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('252 1st Park', 'Sacramento', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2149 Reindahl Hill', 'Stockton', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('28 Fuller Center', 'Orange', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5 Union Hill', 'Huntsville', 'Alabama', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('39 Melby Avenue', 'Huntington', 'West Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('612 Warbler Parkway', 'Toledo', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('29294 Raven Lane', 'Kansas City', 'Missouri', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('7 Texas Point', 'Newark', 'New Jersey', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6092 Artisan Avenue', 'Los Angeles', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('62021 Daystar Plaza', 'Brooklyn', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('62534 Kensington Circle', 'Amarillo', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('47 Birchwood Court', 'Los Angeles', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('771 Hanover Drive', 'Phoenix', 'Arizona', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2710 Leroy Hill', 'South Bend', 'Indiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('952 Kings Court', 'Miami', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('133 Warrior Way', 'Lincoln', 'Nebraska', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3622 Hallows Terrace', 'Buffalo', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4278 Garrison Crossing', 'New York City', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6757 Old Gate Park', 'Miami', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('54 Blackbird Parkway', 'Lynn', 'Massachusetts', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('55398 Hagan Lane', 'Honolulu', 'Hawaii', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('66 Quincy Street', 'Portland', 'Oregon', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('16 Dennis Avenue', 'Evansville', 'Indiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('947 Bayside Road', 'Racine', 'Wisconsin', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2 Blackbird Alley', 'Winston Salem', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0 Sheridan Plaza', 'Corpus Christi', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8 Reindahl Crossing', 'Van Nuys', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('20239 Talmadge Terrace', 'Spartanburg', 'South Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4 Union Street', 'Reno', 'Nevada', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('7 Redwing Center', 'Portland', 'Oregon', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('687 Colorado Junction', 'Midland', 'Michigan', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('862 Lakewood Park', 'Monticello', 'Minnesota', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('63314 Grasskamp Drive', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('67 5th Way', 'Charlotte', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('269 Coleman Place', 'Laurel', 'Maryland', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('9413 Stone Corner Crossing', 'Fresno', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5 Oak Hill', 'Fort Worth', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('79 Anthes Parkway', 'Washington', 'District of Columbia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4101 Rutledge Parkway', 'Springfield', 'Massachusetts', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('967 Johnson Circle', 'Tuscaloosa', 'Alabama', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('92 Buena Vista Court', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('60350 Village Trail', 'Jefferson City', 'Missouri', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('00043 Elgar Avenue', 'Toledo', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0523 Hudson Circle', 'Baltimore', 'Maryland', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('42 Pond Alley', 'Carlsbad', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('329 Golf Way', 'New York City', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3044 Onsgard Terrace', 'San Jose', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3286 Oak Street', 'Wichita Falls', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('658 Rieder Avenue', 'Cincinnati', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('226 Schiller Park', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('18444 Moose Hill', 'New York City', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4862 Chive Plaza', 'Phoenix', 'Arizona', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('88831 Meadow Ridge Drive', 'Newport News', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('871 Warrior Court', 'Bethesda', 'Maryland', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('419 Brickson Park Alley', 'Hollywood', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('434 Graedel Pass', 'Kansas City', 'Kansas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('78649 Milwaukee Road', 'Buffalo', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('383 Maple Hill', 'Durham', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('9 Talmadge Center', 'New Orleans', 'Louisiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8 Evergreen Junction', 'Baton Rouge', 'Louisiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3033 Prentice Place', 'San Antonio', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0 Commercial Alley', 'Denver', 'Colorado', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2643 Lerdahl Trail', 'Stamford', 'Connecticut', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('92 Merry Center', 'Phoenix', 'Arizona', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8959 Birchwood Circle', 'Hamilton', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('599 Bashford Plaza', 'Pittsburgh', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8 Carberry Avenue', 'Austin', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('89 Grover Park', 'Greensboro', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('03229 Marquette Terrace', 'Houston', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('78 Charing Cross Circle', 'Ogden', 'Utah', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('46 Bartillon Court', 'Atlanta', 'Georgia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5 1st Junction', 'Boca Raton', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4 Service Pass', 'Olympia', 'Washington', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('32 Lighthouse Bay Court', 'Portsmouth', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('9 Express Terrace', 'Lansing', 'Michigan', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4 Meadow Valley Crossing', 'Sacramento', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('787 Cordelia Alley', 'Evansville', 'Indiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('788 Anhalt Park', 'New Haven', 'Connecticut', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2 Knutson Circle', 'Orlando', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('80 Eggendart Point', 'Sioux City', 'Iowa', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1 Ilene Trail', 'Atlanta', 'Georgia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('44 Sunnyside Place', 'Amarillo', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('616 Barnett Park', 'Shreveport', 'Louisiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('24 Carey Plaza', 'Humble', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4367 Arkansas Drive', 'Hamilton', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('224 Lukken Way', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1 Golden Leaf Circle', 'Odessa', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('811 Badeau Hill', 'Syracuse', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('75638 Brown Circle', 'Saint Cloud', 'Minnesota', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4 Graedel Park', 'Orlando', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('165 Nobel Place', 'New Orleans', 'Louisiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('94019 Melody Trail', 'Raleigh', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('304 Warner Lane', 'Orlando', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3676 Stang Plaza', 'Tyler', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('39686 Elgar Center', 'Concord', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('72945 Maple Plaza', 'Albany', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('75 Stang Plaza', 'Wichita', 'Kansas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8 Cottonwood Crossing', 'Palatine', 'Illinois', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('08701 Summerview Pass', 'Manassas', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('19597 North Alley', 'Springfield', 'Massachusetts', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('7475 Hollow Ridge Street', 'Fargo', 'North Dakota', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('42 Sachs Hill', 'Wilmington', 'Delaware', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6 Cottonwood Center', 'Alexandria', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('272 Mosinee Trail', 'Pompano Beach', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('33399 Manufacturers Street', 'Independence', 'Missouri', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('907 Summit Plaza', 'Boise', 'Idaho', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('962 Kensington Plaza', 'Bakersfield', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('217 Farragut Plaza', 'Saint Louis', 'Missouri', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('88688 Thompson Place', 'Washington', 'District of Columbia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6197 Erie Way', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('542 Morning Parkway', 'Charlotte', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2958 Reinke Circle', 'Phoenix', 'Arizona', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('899 Riverside Hill', 'Charlotte', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('636 2nd Center', 'Reading', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('36 Bartelt Junction', 'Houston', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('7614 Cordelia Drive', 'Sacramento', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('08402 Utah Drive', 'York', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('89977 Brickson Park Lane', 'Washington', 'District of Columbia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8029 Commercial Avenue', 'Salt Lake City', 'Utah', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('94283 Vera Alley', 'Miami', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('80832 Johnson Hill', 'New Haven', 'Connecticut', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('67765 Oriole Parkway', 'Mesa', 'Arizona', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('661 Burning Wood Street', 'Abilene', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('454 Sycamore Street', 'Washington', 'District of Columbia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('77 Fordem Point', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('05449 Wayridge Court', 'Pueblo', 'Colorado', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('969 Doe Crossing Street', 'Oakland', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8 Calypso Center', 'El Paso', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6946 Fremont Terrace', 'Indianapolis', 'Indiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1011 Hayes Center', 'Pompano Beach', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('97590 Blackbird Place', 'Dallas', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('891 Ramsey Pass', 'Harrisburg', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5 Eliot Hill', 'Waco', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('7373 Scofield Avenue', 'Columbus', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('947 Kipling Point', 'Jacksonville', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0 Fisk Hill', 'Stamford', 'Connecticut', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0004 Tennyson Court', 'Columbus', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('9042 Pankratz Hill', 'Moreno Valley', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('9 Lighthouse Bay Pass', 'Pittsburgh', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('7 Debs Hill', 'San Francisco', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('30321 Fuller Avenue', 'Naples', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('482 Karstens Pass', 'Charlotte', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('50 Merry Pass', 'San Diego', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('475 Victoria Circle', 'Boulder', 'Colorado', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4717 Melody Drive', 'Salt Lake City', 'Utah', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('14728 Barby Point', 'Rochester', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('291 Farragut Lane', 'Kansas City', 'Kansas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8020 Cascade Alley', 'Pompano Beach', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('587 Raven Alley', 'Brooklyn', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('947 Fair Oaks Junction', 'Baton Rouge', 'Louisiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('65 Granby Center', 'Phoenix', 'Arizona', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('89121 Monument Parkway', 'Nashville', 'Tennessee', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('58661 Lunder Plaza', 'Denver', 'Colorado', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1 Ilene Center', 'New Orleans', 'Louisiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('64462 School Trail', 'Stockton', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0084 Lyons Park', 'Sacramento', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('83 Gerald Point', 'San Diego', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5 Starling Trail', 'Albany', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('21885 Forest Crossing', 'Springfield', 'Massachusetts', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('36 Valley Edge Court', 'El Paso', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('9695 Sunfield Drive', 'Macon', 'Georgia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('236 Becker Park', 'Wichita', 'Kansas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('378 Mayfield Court', 'Amarillo', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3586 North Junction', 'Hartford', 'Connecticut', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0 Nobel Hill', 'Shawnee Mission', 'Kansas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('77 Mesta Crossing', 'Reno', 'Nevada', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4492 Michigan Point', 'Lubbock', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('9 Cardinal Street', 'Syracuse', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('02 Fair Oaks Place', 'San Diego', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('90 Village Park', 'Hartford', 'Connecticut', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('05971 Helena Terrace', 'Erie', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('253 Columbus Parkway', 'Charlottesville', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('65 Commercial Drive', 'Vienna', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('898 Eastlawn Place', 'Norwalk', 'Connecticut', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('57 Dapin Hill', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('795 Fieldstone Alley', 'Amarillo', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8235 Golden Leaf Junction', 'Huntsville', 'Alabama', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('77 Pleasure Hill', 'Tacoma', 'Washington', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('76579 Victoria Terrace', 'Greensboro', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('7 Pearson Plaza', 'Lubbock', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('76822 Northview Center', 'Lake Worth', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2443 Warbler Crossing', 'Columbia', 'Missouri', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1 Vera Pass', 'Los Angeles', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2078 Main Lane', 'Johnson City', 'Tennessee', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('807 Carpenter Plaza', 'Orlando', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2536 Kings Point', 'Oklahoma City', 'Oklahoma', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6 Evergreen Point', 'San Luis Obispo', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2929 Village Point', 'Houston', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('54 Pond Plaza', 'Alexandria', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6 Steensland Park', 'Lincoln', 'Nebraska', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5769 Rockefeller Hill', 'New York City', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2 Harper Point', 'Nashville', 'Tennessee', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8 3rd Court', 'Arlington', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0775 Katie Plaza', 'Dallas', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('9 Porter Road', 'Scottsdale', 'Arizona', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6978 Garrison Way', 'Jamaica', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2690 Green Point', 'Detroit', 'Michigan', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('658 Ilene Trail', 'Syracuse', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('95 Dryden Park', 'Phoenix', 'Arizona', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2 Jenifer Trail', 'Tampa', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('43706 Weeping Birch Alley', 'New Haven', 'Connecticut', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3064 Dorton Avenue', 'El Paso', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('52855 Chinook Way', 'Houston', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('08615 Crownhardt Road', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('53203 Green Ridge Trail', 'El Paso', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3 Pine View Junction', 'Memphis', 'Tennessee', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0 Dwight Court', 'Pensacola', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('97 Talmadge Lane', 'Raleigh', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('89 Moulton Drive', 'Glendale', 'Arizona', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('662 Sycamore Plaza', 'Oakland', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('720 Kipling Way', 'Orange', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('000 7th Avenue', 'Oklahoma City', 'Oklahoma', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('9 Golf View Crossing', 'Jackson', 'Mississippi', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('71 Anzinger Way', 'Hattiesburg', 'Mississippi', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('44029 Marcy Trail', 'San Jose', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('60050 Division Crossing', 'Columbus', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1 Merchant Court', 'Charleston', 'West Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('22746 Eagle Crest Place', 'Peoria', 'Arizona', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('294 Sachs Center', 'Wilmington', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3 Buell Court', 'Austin', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('81059 Cambridge Drive', 'Irvine', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('91958 Loomis Crossing', 'Raleigh', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('91 Eagle Crest Place', 'San Antonio', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1642 Pine View Circle', 'Portland', 'Oregon', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2 Pepper Wood Plaza', 'Lynchburg', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('95269 Stephen Lane', 'San Jose', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('557 West Lane', 'Pinellas Park', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4492 Coleman Avenue', 'Johnstown', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3209 Calypso Crossing', 'Washington', 'District of Columbia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0 2nd Plaza', 'Huntington', 'West Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('10 Elgar Parkway', 'Baltimore', 'Maryland', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1 Village Green Street', 'Pasadena', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('88437 Hermina Circle', 'Fresno', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('23777 Gale Hill', 'Saint Paul', 'Minnesota', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('265 Daystar Court', 'Pensacola', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('903 Hagan Point', 'Trenton', 'New Jersey', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('13 Towne Lane', 'Boca Raton', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('431 Rockefeller Crossing', 'Tucson', 'Arizona', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('13797 Northland Park', 'Tulsa', 'Oklahoma', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('05 Killdeer Parkway', 'Akron', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1078 Lakeland Drive', 'Palatine', 'Illinois', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8 Portage Drive', 'Rochester', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('12 Sunnyside Parkway', 'Lawrenceville', 'Georgia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('59 Sunfield Pass', 'Louisville', 'Kentucky', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('36952 Artisan Crossing', 'Springfield', 'Massachusetts', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('35487 Maryland Center', 'Lawrenceville', 'Georgia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('75141 Pawling Way', 'Tampa', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2 Fairview Lane', 'Rochester', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('7402 Ramsey Road', 'Stamford', 'Connecticut', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('76891 Lighthouse Bay Avenue', 'Chicago', 'Illinois', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('941 Clarendon Hill', 'Winston Salem', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('577 Northview Terrace', 'Spring Hill', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('49400 Dottie Pass', 'Evanston', 'Illinois', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('19 Mallory Hill', 'Washington', 'District of Columbia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('103 Golden Leaf Court', 'Atlanta', 'Georgia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('187 Ilene Pass', 'San Antonio', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('112 Hanover Point', 'Denver', 'Colorado', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('979 Pond Street', 'Houston', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4069 Bay Parkway', 'Washington', 'District of Columbia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('57 Canary Road', 'Herndon', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('9 Aberg Court', 'Portland', 'Oregon', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('16 Grover Center', 'Omaha', 'Nebraska', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('45388 Forster Way', 'Pasadena', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('25952 Anderson Crossing', 'Clearwater', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('723 Shasta Court', 'Miami', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8 Weeping Birch Circle', 'Winston Salem', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('485 John Wall Crossing', 'Young America', 'Minnesota', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4245 Linden Point', 'Anchorage', 'Alaska', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('85 Oxford Drive', 'Charleston', 'West Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5 Westridge Circle', 'Everett', 'Washington', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('26658 International Avenue', 'Decatur', 'Illinois', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('28856 Pine View Street', 'Columbus', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4 South Drive', 'Staten Island', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('97807 Morning Road', 'Atlanta', 'Georgia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('32 Bunker Hill Center', 'Huntington', 'West Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('7161 Novick Street', 'New York City', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('66 Sheridan Pass', 'Fresno', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2 Pawling Court', 'Greensboro', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('56927 Kim Drive', 'Memphis', 'Tennessee', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('71984 Sunbrook Parkway', 'Miami', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('29536 Banding Drive', 'Carol Stream', 'Illinois', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('14 Spohn Point', 'Omaha', 'Nebraska', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0 Ridge Oak Avenue', 'Akron', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('7 Maywood Avenue', 'Tyler', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('38030 Clarendon Circle', 'Akron', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2673 Gateway Park', 'Waterbury', 'Connecticut', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('10 Amoth Point', 'Shreveport', 'Louisiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('56222 Menomonie Way', 'Redwood City', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('9 Sachtjen Avenue', 'New York City', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('08 Bultman Pass', 'Worcester', 'Massachusetts', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('242 Luster Parkway', 'Canton', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8881 Farmco Way', 'Portland', 'Oregon', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5203 Village Green Lane', 'Santa Cruz', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('96240 Becker Point', 'Pittsburgh', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5151 Fisk Way', 'Chicago', 'Illinois', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5 Jana Way', 'Charleston', 'West Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('509 Cherokee Lane', 'Watertown', 'Massachusetts', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('67960 Maple Road', 'Saint Paul', 'Minnesota', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6018 Eggendart Court', 'Hollywood', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('11180 Truax Center', 'San Diego', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('7184 Kensington Trail', 'Saint Louis', 'Missouri', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3 Express Drive', 'Fort Wayne', 'Indiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('7 Golf View Place', 'Springfield', 'Illinois', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2 Thompson Lane', 'San Luis Obispo', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('62553 Maywood Road', 'Sacramento', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6775 Pankratz Parkway', 'Durham', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6 John Wall Hill', 'Corpus Christi', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('967 3rd Hill', 'Dallas', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('327 American Ash Drive', 'Minneapolis', 'Minnesota', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('53178 Kingsford Drive', 'Raleigh', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3286 Di Loreto Way', 'Austin', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('997 Glendale Junction', 'Lincoln', 'Nebraska', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5497 Lukken Avenue', 'Cincinnati', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('13176 Fairview Place', 'Detroit', 'Michigan', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8 Schlimgen Way', 'Largo', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6 Springview Court', 'Los Angeles', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2984 Heath Lane', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('35 Anderson Hill', 'Detroit', 'Michigan', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4414 Thompson Trail', 'Loretto', 'Minnesota', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2997 Warrior Lane', 'Dallas', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1593 Cherokee Drive', 'Grand Junction', 'Colorado', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6 Comanche Court', 'Cape Coral', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0 Stuart Point', 'Fort Wayne', 'Indiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3257 Everett Terrace', 'Fort Myers', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('46 1st Junction', 'Columbia', 'South Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('46237 Arkansas Way', 'Hyattsville', 'Maryland', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('37256 Sheridan Way', 'New Castle', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('247 Doe Crossing Crossing', 'Alexandria', 'Louisiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('96 Heffernan Center', 'Waterbury', 'Connecticut', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('147 8th Avenue', 'Albuquerque', 'New Mexico', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('25 Westridge Crossing', 'Pittsburgh', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('77 Sommers Avenue', 'Shreveport', 'Louisiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('937 Vidon Terrace', 'Newark', 'Delaware', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('362 Delaware Street', 'Reston', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('261 Fisk Avenue', 'Muncie', 'Indiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('57816 Schmedeman Pass', 'San Francisco', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0 Arkansas Park', 'Pueblo', 'Colorado', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('81 Merrick Court', 'Los Angeles', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('14 Maywood Park', 'San Antonio', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1 American Junction', 'Savannah', 'Georgia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1376 Sherman Junction', 'Baton Rouge', 'Louisiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('92 Miller Plaza', 'Richmond', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('13 Gulseth Avenue', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0 Tony Junction', 'Raleigh', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('10114 Warbler Avenue', 'Portland', 'Oregon', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('64 Shasta Point', 'Tucson', 'Arizona', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('98 Bayside Lane', 'Orlando', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('60 Green Center', 'Jacksonville', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('990 Schurz Court', 'Shreveport', 'Louisiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('17347 Ohio Center', 'Biloxi', 'Mississippi', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('15 Roxbury Way', 'Stockton', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('4582 Crownhardt Trail', 'Baton Rouge', 'Louisiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('18045 Grover Center', 'Hagerstown', 'Maryland', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('774 Briar Crest Terrace', 'Fort Worth', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('055 Village Point', 'Washington', 'District of Columbia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('69695 Gerald Parkway', 'Richmond', 'Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('582 Division Court', 'Norcross', 'Georgia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('0784 Oriole Avenue', 'Peoria', 'Illinois', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('21747 Spenser Pass', 'Boulder', 'Colorado', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('40 Forest Run Trail', 'Peoria', 'Illinois', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('78 Annamark Alley', 'San Diego', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('10 Hoard Crossing', 'Washington', 'District of Columbia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8283 Mayer Court', 'Charlotte', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('480 Johnson Trail', 'Tulsa', 'Oklahoma', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1 Vidon Avenue', 'New York City', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1405 Lunder Park', 'Memphis', 'Tennessee', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8389 Graceland Street', 'Kansas City', 'Missouri', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('93 Service Parkway', 'Newton', 'Massachusetts', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('398 Artisan Trail', 'Fort Worth', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1758 Mayer Street', 'Orlando', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5 Spohn Court', 'Omaha', 'Nebraska', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('22 Surrey Street', 'Salt Lake City', 'Utah', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('56 Stone Corner Lane', 'Miami', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('245 Springview Drive', 'Salt Lake City', 'Utah', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('62 Ramsey Street', 'Savannah', 'Georgia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('03 Elmside Center', 'Las Vegas', 'Nevada', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5 Randy Crossing', 'Escondido', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('332 Eagan Drive', 'Huntington', 'West Virginia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6 Manufacturers Road', 'Dallas', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('120 Northfield Crossing', 'Trenton', 'New Jersey', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('65 Elmside Hill', 'Wilmington', 'Delaware', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1174 Hanover Terrace', 'Fayetteville', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1 Utah Trail', 'Lincoln', 'Nebraska', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('17198 Ryan Park', 'Indianapolis', 'Indiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('55 Mallory Junction', 'Phoenix', 'Arizona', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('05749 Holy Cross Street', 'Dayton', 'Ohio', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('26530 Melby Center', 'Naples', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('57 Old Gate Center', 'Silver Spring', 'Maryland', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('82427 Hoard Center', 'Lincoln', 'Nebraska', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3 Sommers Avenue', 'Minneapolis', 'Minnesota', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2470 Colorado Center', 'Rochester', 'New York', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('634 Hermina Parkway', 'Allentown', 'Pennsylvania', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6977 Dapin Center', 'Saint Paul', 'Minnesota', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('3383 Hudson Crossing', 'Littleton', 'Colorado', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('5683 Superior Trail', 'Detroit', 'Michigan', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('301 Homewood Alley', 'Washington', 'District of Columbia', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8 Hovde Alley', 'Sarasota', 'Florida', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('2442 Debra Plaza', 'Norwalk', 'Connecticut', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('42 Eliot Place', 'Colorado Springs', 'Colorado', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('75 Porter Hill', 'Tacoma', 'Washington', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('59 Blackbird Avenue', 'Charlotte', 'North Carolina', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('06602 Petterle Road', 'Des Moines', 'Iowa', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('06734 Ilene Drive', 'Long Beach', 'California', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('95501 Kingsford Place', 'Indianapolis', 'Indiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('6 Roth Junction', 'Houston', 'Texas', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('1582 Village Green Junction', 'Montgomery', 'Alabama', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8 Pennsylvania Pass', 'Minneapolis', 'Minnesota', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('95 Forest Dale Drive', 'Monroe', 'Louisiana', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('8240 Becker Terrace', 'Montgomery', 'Alabama', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('271 Northview Plaza', 'Louisville', 'Kentucky', 'United States');
insert into direccion (linea1, ciudad, comunidad, pais) values ('950 Oriole Point', 'Seattle', 'Washington', 'United States');
