insert into direccion (id, linea1, ciudad, comunidad, pais) values (1, '16 Chinook Place', 'Roanoke', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (2, '6 Golf Course Place', 'Hagerstown', 'Maryland', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (3, '93002 Maywood Parkway', 'Montgomery', 'Alabama', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (4, '427 Loomis Terrace', 'Alexandria', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (5, '4 Sommers Lane', 'Virginia Beach', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (6, '8 Scott Pass', 'Saint Louis', 'Missouri', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (7, '367 Anzinger Road', 'Charlotte', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (8, '5210 Lawn Park', 'Chattanooga', 'Tennessee', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (9, '3743 Montana Hill', 'Indianapolis', 'Indiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (10, '484 Meadow Vale Park', 'Jacksonville', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (11, '471 Talmadge Street', 'Spokane', 'Washington', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (12, '961 Briar Crest Road', 'Austin', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (13, '4 Havey Pass', 'Lincoln', 'Nebraska', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (14, '3 Chive Lane', 'Bakersfield', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (15, '685 Leroy Court', 'Evansville', 'Indiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (16, '4325 Michigan Parkway', 'Brooklyn', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (17, '97827 Killdeer Street', 'Pittsburgh', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (18, '19 Elmside Point', 'Biloxi', 'Mississippi', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (19, '69 Sunbrook Point', 'Toledo', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (20, '1139 Merry Point', 'Buffalo', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (21, '47097 Washington Parkway', 'Miami Beach', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (22, '01 Shasta Way', 'Amarillo', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (23, '28 Barby Road', 'Alexandria', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (24, '87088 Boyd Court', 'Springfield', 'Illinois', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (25, '06 Raven Center', 'Denver', 'Colorado', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (26, '297 Butternut Lane', 'Fairbanks', 'Alaska', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (27, '5072 Shasta Alley', 'Daytona Beach', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (28, '70 Dawn Alley', 'Evansville', 'Indiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (29, '698 Cascade Hill', 'Atlanta', 'Georgia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (30, '18274 Esch Center', 'Albuquerque', 'New Mexico', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (31, '6 Clarendon Court', 'Winston Salem', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (32, '1 Maywood Way', 'Fort Wayne', 'Indiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (33, '84523 Rowland Crossing', 'Fort Smith', 'Arkansas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (34, '50 Golf View Road', 'Portsmouth', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (35, '617 Randy Center', 'Lakewood', 'Washington', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (36, '7 Stang Park', 'Jamaica', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (37, '1110 Morning Crossing', 'Los Angeles', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (38, '7 Summerview Drive', 'Roanoke', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (39, '47 Morningstar Trail', 'Boulder', 'Colorado', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (40, '9336 Del Mar Crossing', 'Englewood', 'Colorado', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (41, '23318 Southridge Drive', 'Peoria', 'Illinois', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (42, '7733 Bultman Avenue', 'Topeka', 'Kansas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (43, '54 Redwing Place', 'Prescott', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (44, '815 Prairieview Trail', 'Wilmington', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (45, '668 Union Plaza', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (46, '43 Nova Lane', 'Newport News', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (47, '7648 American Street', 'Little Rock', 'Arkansas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (48, '10 Iowa Trail', 'Columbia', 'South Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (49, '9 Corry Point', 'Dallas', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (50, '6 Mayer Street', 'Sacramento', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (51, '90054 Kensington Park', 'Omaha', 'Nebraska', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (52, '7 Hallows Circle', 'Pompano Beach', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (53, '5625 Gulseth Place', 'Madison', 'Wisconsin', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (54, '444 Farmco Hill', 'Hollywood', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (55, '130 Dayton Park', 'San Jose', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (56, '463 Merrick Trail', 'Phoenix', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (57, '7 Myrtle Center', 'Rockford', 'Illinois', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (58, '85299 Fallview Point', 'Petaluma', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (59, '29134 Chinook Court', 'Everett', 'Washington', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (60, '22 Oak Street', 'Austin', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (61, '36564 Thompson Parkway', 'Beaverton', 'Oregon', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (62, '354 Mariners Cove Trail', 'Waterbury', 'Connecticut', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (63, '154 Bobwhite Pass', 'Birmingham', 'Alabama', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (64, '7 David Point', 'Chicago', 'Illinois', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (65, '3 Corben Alley', 'El Paso', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (66, '6746 Ronald Regan Place', 'Lafayette', 'Louisiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (67, '9029 Golf View Lane', 'Rockville', 'Maryland', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (68, '9 Michigan Court', 'San Francisco', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (69, '02772 Farwell Pass', 'Minneapolis', 'Minnesota', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (70, '7923 Spaight Street', 'Mesa', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (71, '0 Susan Avenue', 'Austin', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (72, '3 East Plaza', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (73, '5427 Pleasure Drive', 'Flushing', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (74, '71844 Steensland Avenue', 'Springfield', 'Illinois', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (75, '3541 Declaration Alley', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (76, '847 Summerview Trail', 'Scottsdale', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (77, '411 Grim Parkway', 'Denver', 'Colorado', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (78, '2385 Pankratz Road', 'Harrisburg', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (79, '4296 East Hill', 'Tampa', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (80, '676 Summerview Road', 'Madison', 'Wisconsin', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (81, '5 Clarendon Plaza', 'Sioux City', 'Iowa', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (82, '8 Warrior Place', 'Hartford', 'Connecticut', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (83, '562 Swallow Trail', 'New York City', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (84, '3 Ridgeway Hill', 'Los Angeles', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (85, '31 Sundown Avenue', 'Houston', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (86, '1834 Reindahl Alley', 'Cincinnati', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (87, '3 Ilene Crossing', 'Houston', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (88, '53733 Hintze Circle', 'Raleigh', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (89, '48 Delaware Lane', 'New Orleans', 'Louisiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (90, '46700 Parkside Place', 'San Antonio', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (91, '627 Sauthoff Drive', 'Raleigh', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (92, '9 Holy Cross Pass', 'Kansas City', 'Missouri', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (93, '04 Holmberg Parkway', 'Lansing', 'Michigan', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (94, '9 Kedzie Hill', 'Memphis', 'Tennessee', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (95, '4 Oakridge Circle', 'Detroit', 'Michigan', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (96, '4492 Warrior Junction', 'Santa Ana', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (97, '2879 Manitowish Alley', 'Milwaukee', 'Wisconsin', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (98, '100 Susan Pass', 'Memphis', 'Tennessee', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (99, '7 Laurel Parkway', 'Atlanta', 'Georgia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (100, '728 Eagan Trail', 'Richmond', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (101, '2 Nevada Avenue', 'Reno', 'Nevada', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (102, '2 Helena Circle', 'Akron', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (103, '67 Vidon Junction', 'Salt Lake City', 'Utah', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (104, '42466 Spohn Point', 'Mobile', 'Alabama', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (105, '235 Harbort Center', 'Melbourne', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (106, '77374 Lien Parkway', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (107, '387 Bashford Parkway', 'Pittsburgh', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (108, '4 Sachtjen Way', 'Hicksville', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (109, '7 Del Sol Junction', 'Gulfport', 'Mississippi', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (110, '27888 Gerald Park', 'Los Angeles', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (111, '33 Warrior Avenue', 'Valdosta', 'Georgia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (112, '9 6th Crossing', 'Harrisburg', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (113, '330 Ryan Pass', 'New York City', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (114, '519 Katie Way', 'Las Cruces', 'New Mexico', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (115, '109 Loomis Park', 'Amarillo', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (116, '837 Havey Center', 'Palm Bay', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (117, '45 Golf Avenue', 'Boston', 'Massachusetts', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (118, '017 Monterey Court', 'Montgomery', 'Alabama', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (119, '79175 4th Terrace', 'Boston', 'Massachusetts', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (120, '07 Sutherland Terrace', 'Fort Worth', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (121, '6 Maywood Park', 'Des Moines', 'Iowa', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (122, '27 Texas Plaza', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (123, '9701 Saint Paul Drive', 'Cumming', 'Georgia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (124, '44205 Menomonie Street', 'Metairie', 'Louisiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (125, '003 Mallard Way', 'Warren', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (126, '14501 Thierer Lane', 'Charleston', 'South Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (127, '354 Prentice Place', 'Lubbock', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (128, '7 Hayes Parkway', 'Kingsport', 'Tennessee', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (129, '0 Pennsylvania Road', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (130, '186 Ronald Regan Court', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (131, '479 Vera Road', 'Trenton', 'New Jersey', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (132, '45076 Lukken Pass', 'Young America', 'Minnesota', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (133, '331 Huxley Circle', 'Cincinnati', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (134, '48 Hermina Junction', 'San Bernardino', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (135, '586 Bowman Pass', 'Mesa', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (136, '972 Derek Junction', 'Gainesville', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (137, '802 Mcguire Drive', 'Richmond', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (138, '59349 Utah Point', 'Stockton', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (139, '9784 Crescent Oaks Court', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (140, '074 Mitchell Road', 'Salt Lake City', 'Utah', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (141, '4 Banding Hill', 'Shreveport', 'Louisiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (142, '8 Hallows Pass', 'Port Saint Lucie', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (143, '298 Rowland Avenue', 'Colorado Springs', 'Colorado', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (144, '2902 Ronald Regan Circle', 'Arlington', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (145, '197 Macpherson Street', 'Portland', 'Oregon', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (146, '979 Elmside Way', 'Ann Arbor', 'Michigan', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (147, '6 Warner Circle', 'Ogden', 'Utah', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (148, '9580 Charing Cross Plaza', 'Lancaster', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (149, '725 Anzinger Parkway', 'Sioux Falls', 'South Dakota', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (150, '5640 Shasta Alley', 'Anchorage', 'Alaska', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (151, '16 4th Center', 'Hayward', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (152, '2 Melrose Center', 'Saint Paul', 'Minnesota', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (153, '41 Rowland Way', 'Fargo', 'North Dakota', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (154, '58288 Melrose Drive', 'Shreveport', 'Louisiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (155, '89 Toban Junction', 'Missoula', 'Montana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (156, '3892 Carberry Pass', 'New York City', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (157, '897 Veith Trail', 'Phoenix', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (158, '7 Atwood Trail', 'Denton', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (159, '4 Raven Plaza', 'Seattle', 'Washington', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (160, '1 Corry Avenue', 'Houston', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (161, '9 Loomis Lane', 'Fort Wayne', 'Indiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (162, '75072 Superior Parkway', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (163, '92302 Bunker Hill Street', 'Los Angeles', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (164, '9 Mariners Cove Park', 'Orlando', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (165, '97370 Eliot Trail', 'Flint', 'Michigan', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (166, '84 Marcy Court', 'San Jose', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (167, '631 Warrior Crossing', 'Colorado Springs', 'Colorado', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (168, '0 Maywood Parkway', 'Evansville', 'Indiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (169, '2 Emmet Hill', 'Grand Rapids', 'Michigan', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (170, '384 Pleasure Place', 'San Francisco', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (171, '7700 Sunnyside Trail', 'Portsmouth', 'New Hampshire', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (172, '934 East Terrace', 'West Palm Beach', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (173, '614 Granby Avenue', 'Memphis', 'Tennessee', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (174, '22 Victoria Drive', 'Dayton', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (175, '314 Grover Junction', 'Boulder', 'Colorado', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (176, '418 Dunning Crossing', 'Bakersfield', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (177, '799 Hoepker Road', 'Fort Lauderdale', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (178, '5 Bayside Lane', 'San Diego', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (179, '3 Red Cloud Park', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (180, '484 Grover Street', 'Melbourne', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (181, '297 Shopko Street', 'New York City', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (182, '2 Milwaukee Junction', 'Huntington', 'West Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (183, '7 Moose Circle', 'Charlottesville', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (184, '59062 Florence Point', 'Milwaukee', 'Wisconsin', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (185, '725 Drewry Trail', 'Newark', 'New Jersey', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (186, '9974 Atwood Point', 'San Antonio', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (187, '994 Redwing Terrace', 'Corpus Christi', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (188, '30 6th Road', 'Tacoma', 'Washington', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (189, '4 Merchant Circle', 'Honolulu', 'Hawaii', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (190, '53497 Moland Road', 'Evansville', 'Indiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (191, '279 Butterfield Plaza', 'Houston', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (192, '222 Scofield Hill', 'Bronx', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (193, '7401 Anhalt Avenue', 'Montgomery', 'Alabama', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (194, '1282 Declaration Road', 'Roanoke', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (195, '5 Orin Center', 'Worcester', 'Massachusetts', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (196, '813 Bunting Drive', 'New York City', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (197, '03 Tomscot Avenue', 'Yonkers', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (198, '0 Crescent Oaks Avenue', 'Las Vegas', 'Nevada', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (199, '14514 Crownhardt Place', 'Miami', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (200, '11361 Warrior Alley', 'Chandler', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (201, '818 Fieldstone Junction', 'New York City', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (202, '51263 Havey Avenue', 'Buffalo', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (203, '679 Mayer Park', 'New Castle', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (204, '0413 Meadow Ridge Park', 'Duluth', 'Minnesota', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (205, '6763 Barby Trail', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (206, '2358 Shopko Hill', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (207, '30276 Thompson Pass', 'Houston', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (208, '355 Jay Junction', 'Erie', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (209, '12 Magdeline Court', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (210, '8 Blaine Court', 'Miami', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (211, '24 Tony Lane', 'Des Moines', 'Iowa', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (212, '371 Acker Plaza', 'Fort Worth', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (213, '9225 Fulton Circle', 'Saint Louis', 'Missouri', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (214, '9420 Beilfuss Hill', 'Las Vegas', 'Nevada', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (215, '582 Packers Court', 'New York City', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (216, '41 Surrey Avenue', 'Phoenix', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (217, '7734 Tennessee Circle', 'Albany', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (218, '93 Hermina Pass', 'Norcross', 'Georgia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (219, '424 Scoville Avenue', 'Columbia', 'South Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (220, '3170 Browning Court', 'Macon', 'Georgia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (221, '3597 Prentice Alley', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (222, '4576 Blaine Court', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (223, '8968 Gina Lane', 'Saint Louis', 'Missouri', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (224, '5244 Carey Trail', 'Sacramento', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (225, '3 Harper Drive', 'Houston', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (226, '37531 Blackbird Drive', 'Toledo', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (227, '4729 Clarendon Road', 'Louisville', 'Kentucky', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (228, '34 4th Point', 'Richmond', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (229, '574 Holmberg Pass', 'Milwaukee', 'Wisconsin', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (230, '28013 5th Drive', 'Cincinnati', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (231, '56 American Ash Circle', 'Gainesville', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (232, '300 Bayside Way', 'Atlanta', 'Georgia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (233, '0 Monterey Point', 'Jackson', 'Mississippi', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (234, '178 Logan Junction', 'Newton', 'Massachusetts', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (235, '193 Knutson Terrace', 'Sacramento', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (236, '5697 Fieldstone Point', 'Houston', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (237, '622 Mcbride Road', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (238, '05933 Sunfield Place', 'Winston Salem', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (239, '2 Coolidge Place', 'Austin', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (240, '202 North Court', 'Fort Worth', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (241, '16013 Heath Park', 'Montgomery', 'Alabama', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (242, '5 Loomis Trail', 'Charleston', 'South Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (243, '51 Veith Center', 'Madison', 'Wisconsin', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (244, '023 Dexter Junction', 'Pasadena', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (245, '2143 Summerview Court', 'Tucson', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (246, '46 Rutledge Court', 'Charlotte', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (247, '06623 Elka Street', 'Louisville', 'Kentucky', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (248, '162 Vidon Junction', 'Temple', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (249, '2272 Petterle Terrace', 'Fayetteville', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (250, '1250 Lake View Lane', 'Kansas City', 'Missouri', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (251, '8433 Warner Place', 'Cape Coral', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (252, '00 Harper Park', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (253, '8839 Oxford Alley', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (254, '4007 Leroy Avenue', 'Macon', 'Georgia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (255, '64488 Havey Park', 'Albuquerque', 'New Mexico', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (256, '48541 Dexter Drive', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (257, '131 Prairie Rose Pass', 'Canton', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (258, '861 Starling Drive', 'Wilmington', 'Delaware', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (259, '32311 Eastlawn Plaza', 'Flint', 'Michigan', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (260, '9396 Walton Way', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (261, '031 Cherokee Road', 'Tampa', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (262, '465 Prairie Rose Court', 'San Diego', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (263, '3749 1st Terrace', 'Philadelphia', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (264, '85 Park Meadow Terrace', 'Cincinnati', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (265, '90 Monterey Lane', 'Tulsa', 'Oklahoma', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (266, '39145 Waywood Road', 'Dallas', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (267, '91077 Forster Circle', 'North Little Rock', 'Arkansas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (268, '27 Longview Junction', 'Oklahoma City', 'Oklahoma', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (269, '96052 Thierer Avenue', 'Visalia', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (270, '202 Main Place', 'Shreveport', 'Louisiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (271, '0188 Donald Trail', 'Los Angeles', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (272, '0165 Burrows Parkway', 'Pensacola', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (273, '68029 Manitowish Junction', 'Alexandria', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (274, '62 Raven Road', 'Shreveport', 'Louisiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (275, '859 Pepper Wood Point', 'Brockton', 'Massachusetts', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (276, '79261 Fallview Way', 'Las Vegas', 'Nevada', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (277, '62 Almo Trail', 'Bloomington', 'Indiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (278, '24981 Hollow Ridge Alley', 'Birmingham', 'Alabama', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (279, '867 Fieldstone Place', 'Round Rock', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (280, '794 Comanche Point', 'Fort Worth', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (281, '61254 Sullivan Place', 'Boston', 'Massachusetts', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (282, '716 Havey Drive', 'Hayward', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (283, '88 Orin Lane', 'Topeka', 'Kansas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (284, '511 Spohn Circle', 'Corpus Christi', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (285, '235 Gerald Parkway', 'San Antonio', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (286, '427 Debra Trail', 'El Paso', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (287, '96 Mendota Hill', 'Herndon', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (288, '64 Pearson Pass', 'Salt Lake City', 'Utah', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (289, '8 Vidon Center', 'New York City', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (290, '2 Mallory Point', 'Austin', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (291, '31 Hagan Plaza', 'Irvine', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (292, '23 Porter Court', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (293, '1 Miller Way', 'Seattle', 'Washington', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (294, '557 Luster Lane', 'Pasadena', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (295, '826 Tennyson Street', 'Baltimore', 'Maryland', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (296, '3953 Bayside Avenue', 'Schaumburg', 'Illinois', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (297, '363 Prentice Pass', 'Hialeah', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (298, '86 Vernon Way', 'Minneapolis', 'Minnesota', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (299, '844 Pepper Wood Terrace', 'Henderson', 'Nevada', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (300, '40 Welch Plaza', 'Miami', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (301, '65 Aberg Street', 'Naples', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (302, '1 Talisman Way', 'Chicago', 'Illinois', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (303, '9 Lawn Court', 'Anderson', 'Indiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (304, '19 Susan Trail', 'Fullerton', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (305, '32 Moulton Junction', 'Flint', 'Michigan', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (306, '7558 Garrison Plaza', 'Louisville', 'Kentucky', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (307, '835 Mifflin Alley', 'Charlotte', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (308, '2 Westport Circle', 'Miami', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (309, '7548 Arizona Terrace', 'Baltimore', 'Maryland', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (310, '88744 Eagle Crest Hill', 'Durham', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (311, '053 Mandrake Hill', 'Columbia', 'South Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (312, '02 Hanson Parkway', 'Fullerton', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (313, '90 Northridge Circle', 'Muskegon', 'Michigan', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (314, '098 Pierstorff Lane', 'Los Angeles', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (315, '303 Surrey Court', 'Peoria', 'Illinois', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (316, '5 Clove Trail', 'Omaha', 'Nebraska', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (317, '05 Karstens Pass', 'Olympia', 'Washington', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (318, '02 Melrose Lane', 'Houston', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (319, '7 International Pass', 'Sarasota', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (320, '56054 Oak Valley Center', 'San Francisco', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (321, '91591 Schurz Circle', 'Colorado Springs', 'Colorado', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (322, '8 Crest Line Circle', 'Newark', 'New Jersey', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (323, '93 Leroy Hill', 'Lexington', 'Kentucky', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (324, '3984 Ilene Street', 'Minneapolis', 'Minnesota', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (325, '37 Hagan Terrace', 'Tucson', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (326, '20786 Bunting Junction', 'Birmingham', 'Alabama', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (327, '30 Florence Avenue', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (328, '15869 Rowland Place', 'Dallas', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (329, '25742 Golf Trail', 'Saint Paul', 'Minnesota', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (330, '3046 Hanover Court', 'Little Rock', 'Arkansas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (331, '02936 Blaine Center', 'Denver', 'Colorado', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (332, '79978 Fremont Center', 'Los Angeles', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (333, '38540 Veith Street', 'Gatesville', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (334, '8 Meadow Vale Place', 'Bloomington', 'Illinois', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (335, '6 Melvin Hill', 'Boston', 'Massachusetts', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (336, '567 Helena Road', 'Cincinnati', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (337, '6225 Grasskamp Hill', 'Bakersfield', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (338, '80603 Darwin Avenue', 'Gadsden', 'Alabama', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (339, '1480 Duke Road', 'Iowa City', 'Iowa', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (340, '67 Shopko Drive', 'Burbank', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (341, '008 Hooker Junction', 'Sacramento', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (342, '3595 Kipling Trail', 'Springfield', 'Illinois', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (343, '9660 Kim Circle', 'Charlotte', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (344, '19676 Ilene Street', 'Lincoln', 'Nebraska', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (345, '595 Declaration Avenue', 'Houston', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (346, '3347 Brown Center', 'Orlando', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (347, '971 Karstens Hill', 'Dallas', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (348, '8 Dwight Hill', 'Tucson', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (349, '538 Pearson Street', 'Boise', 'Idaho', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (350, '2 Carberry Junction', 'Marietta', 'Georgia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (351, '556 Clarendon Crossing', 'Johnstown', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (352, '8429 Starling Alley', 'Jacksonville', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (353, '65264 Mcbride Terrace', 'Vancouver', 'Washington', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (354, '29 Daystar Park', 'Milwaukee', 'Wisconsin', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (355, '64 Coolidge Hill', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (356, '3 Crest Line Way', 'Charlotte', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (357, '9472 Pond Drive', 'Dayton', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (358, '35135 Elgar Parkway', 'Gaithersburg', 'Maryland', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (359, '045 Fairview Avenue', 'Trenton', 'New Jersey', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (360, '9 Lillian Court', 'Frankfort', 'Kentucky', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (361, '74532 Brown Point', 'Dallas', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (362, '167 Dennis Crossing', 'Madison', 'Wisconsin', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (363, '73236 Everett Lane', 'Oklahoma City', 'Oklahoma', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (364, '6273 Ridgeway Point', 'Denver', 'Colorado', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (365, '1 Kipling Center', 'Phoenix', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (366, '2 Mcguire Parkway', 'San Rafael', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (367, '38 Oakridge Crossing', 'Milwaukee', 'Wisconsin', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (368, '34 Jana Crossing', 'Knoxville', 'Tennessee', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (369, '2549 Marcy Point', 'Florence', 'South Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (370, '0 Huxley Court', 'Cincinnati', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (371, '92 Bashford Plaza', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (372, '7133 Hanover Avenue', 'Peoria', 'Illinois', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (373, '547 New Castle Parkway', 'Houston', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (374, '3 Moulton Park', 'Bonita Springs', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (375, '5001 Oak Court', 'Shreveport', 'Louisiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (376, '472 Bartelt Parkway', 'Los Angeles', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (377, '2 Autumn Leaf Drive', 'Tacoma', 'Washington', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (378, '5 Pierstorff Place', 'Houston', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (379, '0418 Birchwood Road', 'Toledo', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (380, '4642 Spenser Drive', 'Wichita', 'Kansas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (381, '58 Browning Center', 'Wichita Falls', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (382, '4 Homewood Park', 'San Francisco', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (383, '1 Atwood Drive', 'Miami', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (384, '651 Norway Maple Lane', 'Elmira', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (385, '4 Stoughton Point', 'Los Angeles', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (386, '9846 Karstens Alley', 'Charlotte', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (387, '307 North Way', 'North Hollywood', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (388, '461 Maple Wood Court', 'Columbia', 'South Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (389, '38 Schiller Circle', 'Las Vegas', 'Nevada', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (390, '83 Blue Bill Park Drive', 'Raleigh', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (391, '42 Northport Plaza', 'Birmingham', 'Alabama', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (392, '9 Texas Crossing', 'Charleston', 'South Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (393, '62 Bonner Way', 'Akron', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (394, '3 Maywood Center', 'Shreveport', 'Louisiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (395, '6553 Dakota Plaza', 'Albany', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (396, '7534 Sutherland Junction', 'Pompano Beach', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (397, '7 Lakeland Court', 'Tucson', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (398, '3 Hanson Drive', 'Irvine', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (399, '13 Corscot Court', 'Gainesville', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (400, '16 Rockefeller Avenue', 'Buffalo', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (401, '75 Towne Way', 'Las Vegas', 'Nevada', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (402, '2506 Sachs Court', 'West Palm Beach', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (403, '3 Hoard Center', 'Norfolk', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (404, '38 Bellgrove Pass', 'San Francisco', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (405, '530 Mosinee Court', 'Ventura', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (406, '71843 Anniversary Alley', 'Cincinnati', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (407, '67893 Glacier Hill Avenue', 'Birmingham', 'Alabama', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (408, '348 Summer Ridge Road', 'Columbus', 'Mississippi', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (409, '6 Hintze Way', 'Idaho Falls', 'Idaho', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (410, '76732 Welch Park', 'Fort Lauderdale', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (411, '2 Tomscot Pass', 'Rochester', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (412, '28 Ramsey Park', 'Hyattsville', 'Maryland', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (413, '2006 Scofield Park', 'Santa Clara', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (414, '80 Union Drive', 'Houston', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (415, '287 Maywood Alley', 'Columbus', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (416, '854 Russell Point', 'Punta Gorda', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (417, '97 Eagan Junction', 'El Paso', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (418, '05 Mcbride Road', 'Billings', 'Montana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (419, '4 Dottie Alley', 'Kansas City', 'Missouri', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (420, '440 Porter Park', 'Great Neck', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (421, '220 4th Park', 'Saint Paul', 'Minnesota', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (422, '7712 Veith Park', 'Dallas', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (423, '73 Pearson Trail', 'Saint Louis', 'Missouri', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (424, '56079 Springview Hill', 'Raleigh', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (425, '1 Summerview Place', 'Las Vegas', 'Nevada', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (426, '12 Stuart Street', 'Albuquerque', 'New Mexico', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (427, '8714 Northwestern Pass', 'Arvada', 'Colorado', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (428, '01743 Pine View Lane', 'Colorado Springs', 'Colorado', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (429, '29 Rowland Center', 'Fort Worth', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (430, '4 Ohio Plaza', 'Madison', 'Wisconsin', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (431, '73152 Ronald Regan Junction', 'Pompano Beach', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (432, '68 Hovde Place', 'Corpus Christi', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (433, '13180 Banding Place', 'Houston', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (434, '22326 Buell Center', 'Hartford', 'Connecticut', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (435, '707 7th Circle', 'Lincoln', 'Nebraska', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (436, '3 Eastwood Alley', 'Wilmington', 'Delaware', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (437, '292 Muir Road', 'Jackson', 'Mississippi', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (438, '338 Onsgard Avenue', 'San Diego', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (439, '058 Lyons Crossing', 'Wilmington', 'Delaware', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (440, '4799 Springs Junction', 'Indianapolis', 'Indiana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (441, '01845 Esch Drive', 'Albuquerque', 'New Mexico', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (442, '463 Jenifer Way', 'Orange', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (443, '09 Amoth Parkway', 'Dayton', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (444, '49 American Ash Drive', 'Albuquerque', 'New Mexico', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (445, '85245 Eggendart Place', 'Columbia', 'South Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (446, '35 Sachs Street', 'Davenport', 'Iowa', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (447, '50 Vernon Park', 'Birmingham', 'Alabama', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (448, '6 Cardinal Place', 'Saint Louis', 'Missouri', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (449, '4 Cottonwood Junction', 'Garden Grove', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (450, '676 Nancy Court', 'York', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (451, '448 Mendota Trail', 'Gilbert', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (452, '10538 Main Place', 'Chicago', 'Illinois', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (453, '5766 Buhler Way', 'Chicago', 'Illinois', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (454, '43 High Crossing Street', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (455, '0 Spenser Street', 'Abilene', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (456, '80 Michigan Circle', 'San Diego', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (457, '8882 Springview Place', 'Charlotte', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (458, '7 Elka Place', 'San Antonio', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (459, '83193 Kinsman Way', 'Oklahoma City', 'Oklahoma', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (460, '7414 Atwood Road', 'Anchorage', 'Alaska', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (461, '39 Buhler Point', 'Norfolk', 'Virginia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (462, '99 Grim Avenue', 'Flint', 'Michigan', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (463, '830 Hermina Junction', 'Jacksonville', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (464, '3 Eliot Junction', 'Great Neck', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (465, '0 Sunnyside Hill', 'Bozeman', 'Montana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (466, '05792 Jenifer Point', 'Scottsdale', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (467, '6 Carpenter Center', 'San Diego', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (468, '0 Cardinal Parkway', 'Paterson', 'New Jersey', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (469, '00515 Tennyson Center', 'Decatur', 'Illinois', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (470, '8 Paget Point', 'Cincinnati', 'Ohio', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (471, '1 South Way', 'Dallas', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (472, '9 Eastwood Drive', 'Charlotte', 'North Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (473, '93887 Glacier Hill Park', 'Houston', 'Texas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (474, '823 Forster Park', 'Miami', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (475, '6064 Summerview Road', 'Shawnee Mission', 'Kansas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (476, '0490 Northridge Street', 'Tampa', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (477, '34 Pine View Circle', 'Boca Raton', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (478, '403 Nevada Junction', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (479, '48 Butterfield Drive', 'Pensacola', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (480, '35 Memorial Point', 'Phoenix', 'Arizona', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (481, '38 Sunbrook Drive', 'Oklahoma City', 'Oklahoma', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (482, '4 Crest Line Way', 'Charleston', 'South Carolina', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (483, '705 Rieder Park', 'Huntington Beach', 'California', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (484, '349 Hudson Alley', 'Jacksonville', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (485, '56594 Ronald Regan Avenue', 'Albany', 'Georgia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (486, '884 Glendale Pass', 'Clearwater', 'Florida', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (487, '886 Katie Trail', 'Pittsburgh', 'Pennsylvania', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (488, '64271 Monica Junction', 'Wichita', 'Kansas', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (489, '2777 Monica Parkway', 'Saint Cloud', 'Minnesota', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (490, '545 Laurel Trail', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (491, '93457 Rieder Crossing', 'Oklahoma City', 'Oklahoma', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (492, '29515 Farmco Terrace', 'Salt Lake City', 'Utah', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (493, '9 Pine View Parkway', 'Chattanooga', 'Tennessee', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (494, '02790 Sachtjen Avenue', 'Rochester', 'New York', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (495, '62176 Hanson Terrace', 'Spokane', 'Washington', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (496, '8 Steensland Trail', 'Baltimore', 'Maryland', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (497, '880 Comanche Park', 'Missoula', 'Montana', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (498, '04203 Petterle Road', 'Atlanta', 'Georgia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (499, '2 Monica Circle', 'Washington', 'District of Columbia', 'United States');
insert into direccion (id, linea1, ciudad, comunidad, pais) values (500, '78 Oak Valley Hill', 'Saginaw', 'Michigan', 'United States');
