insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sherry - Dry', '../../../../../../../../../../../etc/passwd%00', 14, 4, 108);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Asparagus - Green, Fresh', '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕', 22, 1, 367);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lamb - Whole, Frozen', '<>?:"{}|_+', 28, 3, 430);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Ecolab - Solid Fusion', '"''"''"''''''''"', 37, 5, 210);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Isomalt', '１２３', 23, 9, 400);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Soup - Campbells Beef Stew', '() { 0; }; touch /tmp/blns.shellshock1.fail;', 1, 9, 51);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beans - Fine', '👩🏽', 19, 7, 291);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Mozzarella, Shredded', '"', 40, 6, 321);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Petite Baguette', '社會科學院語學研究所', 26, 7, 266);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pate - Liver', 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', 2, 6, 24);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Corn Shoots', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 28, 4, 6);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beans - French', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 36, 9, 236);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Turkey - Breast, Boneless Sk On', '﻿', 21, 8, 244);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Carbonated Water - Orange', '田中さんにあげて下さい', 35, 4, 381);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pasta - Bauletti, Chicken White', 'nil', 17, 3, 113);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Stock - Veal, Brown', '../../../../../../../../../../../etc/hosts', 11, 3, 56);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Jackson Triggs Okonagan', '사회과학원 어학연구소', 6, 4, 433);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Flower - Daisies', '-1', 29, 4, 303);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lamb Leg - Bone - In Nz', '¸˛Ç◊ı˜Â¯˘¿', 14, 5, 342);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beef - Cooked, Corned', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 17, 1, 267);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Cambozola', '0/0', 1, 4, 339);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Blue Nun Qualitatswein', 'ÅÍÎÏ˝ÓÔÒÚÆ☃', 13, 9, 311);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Blackberries', '1E02', 34, 9, 203);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Soup - Knorr, Ministrone', '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 22, 2, 107);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Syrup - Chocolate', '사회과학원 어학연구소', 5, 6, 309);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Trout - Smoked', '１２３', 25, 10, 10);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lentils - Green Le Puy', '<svg><script>0<1>alert(''XSS'')</script>', 38, 5, 480);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Soup - Campbells Beef Stew', 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', 22, 3, 146);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Red, Lurton Merlot De', '␣', 3, 1, 349);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Steam Pan - Half Size Deep', 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', 3, 6, 404);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cucumber - Pickling Ontario', ' ', 12, 8, 119);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Piping Jelly - All Colours', 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', 39, 1, 296);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Veal - Inside', 'NIL', 32, 1, 9);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bread - Crusty Italian Poly', 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', 24, 9, 392);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Puree - Kiwi', '1.00', 45, 3, 460);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Cambozola', '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 13, 5, 297);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Fiddlehead - Frozen', '<img src=x onerror=alert(''hi'') />', 23, 6, 47);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Dubouef Macon - Villages', '0/0', 48, 8, 346);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Trimbach Pinot Blanc', '-1/2', 7, 10, 442);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Hardys Bankside Shiraz', '👩🏽', 19, 9, 146);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lumpfish Black', '00˙Ɩ$-', 9, 2, 442);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beef - Bresaola', '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', 44, 5, 307);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sauce - Demi Glace', '⁰⁴⁵₀₁₂', 21, 1, 349);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beans - Kidney, Red Dry', '１２３', 46, 7, 110);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sproutsmustard Cress', '$1.00', 5, 3, 223);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Soup - Campbells Beef Stew', '1E02', 14, 3, 261);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Ketchup - Tomato', '-1/2', 1, 9, 142);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Juice - Lemon', 'œ∑´®†¥¨ˆøπ“‘', 17, 5, 213);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Appetizer - Veg Assortment', '-1E2', 47, 5, 496);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lettuce - Lambs Mash', '🐵 🙈 🙉 🙊', 48, 4, 344);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Garbage Bags - Black', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 31, 8, 10);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beer - Guiness', '-1E2', 17, 8, 410);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pickle - Dill', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 18, 8, 309);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lettuce - Sea / Sea Asparagus', '᠎', 10, 3, 470);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cinnamon Buns Sticky', '`⁄€‹›ﬁﬂ‡°·‚—±', 26, 3, 290);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pork - Smoked Kassler', '!@#$%^&*()', 1, 8, 18);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Rum - Coconut, Malibu', '<svg><script>0<1>alert(''XSS'')</script>', 35, 7, 97);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pectin', '田中さんにあげて下さい', 2, 8, 322);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Salt - Seasoned', ' ', 15, 10, 361);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chervil - Fresh', '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 49, 10, 166);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Red, Concha Y Toro', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 12, 1, 491);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Orange Roughy 4/6 Oz', '../../../../../../../../../../../etc/passwd%00', 45, 5, 56);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chocolate Bar - Reese Pieces', '⁦test⁧', 43, 8, 97);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tuna - Fresh', '1/0', 48, 10, 231);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bacardi Limon', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 33, 9, 280);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bagel - Sesame Seed Presliced', '1', 27, 5, 307);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bread - Olive', '-1.00', 17, 3, 336);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Onion - Dried', 'null', 44, 1, 388);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Coffee - Espresso', '１２３', 49, 2, 468);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cabbage - Green', '""', 44, 1, 428);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Taro Leaves', '𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 36, 10, 274);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Soup - French Onion', 'Œ„´‰ˇÁ¨ˆØ∏”’', 8, 5, 18);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Soup - Campbells, Cream Of', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 28, 3, 263);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chips - Assorted', 'œ∑´®†¥¨ˆøπ“‘', 43, 5, 368);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sugar - Splenda Sweetener', '¸˛Ç◊ı˜Â¯˘¿', 2, 10, 321);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Cheddarsliced', '<img src=x onerror=alert(''hi'') />', 48, 5, 469);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Gingerale - Schweppes, 355 Ml', '""', 44, 3, 126);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Jafflin Bourgongone', '1E+02', 44, 3, 108);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Walkers Special Old Whiskey', '0/0', 10, 4, 4);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Foam Dinner Plate', 'null', 29, 10, 103);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lid - 10,12,16 Oz', '⁰⁴⁵', 39, 10, 94);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Chablis J Moreau Et Fils', '١٢٣', 41, 1, 411);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Spring Roll Wrappers', '<img src=x onerror=alert(''hi'') />', 9, 8, 23);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Leeks - Large', '和製漢語', 30, 6, 351);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cocoa Powder - Natural', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 3, 3, 201);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Olives - Stuffed', null, 6, 1, 262);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Skewers - Bamboo', '!@#$%^&*()', 44, 6, 291);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Plasticknivesblack', '﻿', 41, 2, 450);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bag - Bread, White, Plain', '-1E02', 37, 3, 260);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Meldea Green Tea Liquor', '␣', 47, 7, 438);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Glass Clear 7 Oz Xl', '社會科學院語學研究所', 36, 3, 346);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beef - Eye Of Round', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 42, 8, 273);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Daikon Radish', '<img src=x onerror=alert(''hi'') />', 25, 5, 322);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Oil - Hazelnut', '-1E2', 24, 5, 309);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beef Tenderloin Aaa', ',./;''[]\-=', 43, 7, 435);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pasta - Spaghetti, Dry', '-1/2', 27, 8, 415);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Soup - Campbells, Creamy', 'NULL', 18, 6, 264);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pastry - Key Limepoppy Seed Tea', '👩🏽', 41, 1, 462);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chevere Logs', '<svg><script>0<1>alert(''XSS'')</script>', 13, 1, 256);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sherbet - Raspberry', '⁰⁴⁵₀₁₂', 34, 5, 245);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bread - Calabrese Baguette', '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 28, 4, 58);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Salad Dressing', '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', 5, 6, 114);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lid Tray - 16in Dome', '<img src=x onerror=alert(''hi'') />', 46, 8, 366);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Shrimp - Tiger 21/25', '😍', 50, 7, 59);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bread - Onion Focaccia', '﻿', 15, 6, 472);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Lou Black Shiraz', 'パーティーへ行かないか', 43, 1, 242);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Oranges', '-1.00', 36, 9, 242);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Vermouth - Sweet, Cinzano', '0/0', 45, 7, 62);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pepper - Yellow Bell', null, 19, 6, 279);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Veal - Striploin', '-1E2', 6, 10, 103);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pork - Bacon, Sliced', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 11, 9, 116);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Trout - Smoked', '../../../../../../../../../../../etc/passwd%00', 4, 7, 173);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Butter Sweet', '⁦test⁧', 39, 1, 72);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Ham - Cooked Italian', '$1.00', 29, 10, 410);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sproutsmustard Cress', '1/0', 10, 6, 267);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - White, Riesling, Henry Of', '١٢٣', 6, 4, 362);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Parsley - Fresh', '␢', 4, 4, 1);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Doilies - 12, Paper', '1''; DROP TABLE users--', 5, 10, 383);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pasta - Rotini, Dry', '​', 35, 2, 203);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Dip - Tapenade', '0/0', 15, 2, 268);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Anisette - Mcguiness', ' test ', 33, 5, 307);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Savigny - Les - Beaune', '👩🏽', 42, 9, 197);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sesame Seed Black', '1/0', 36, 7, 11);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Frangelico', 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', 36, 7, 210);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Squid - U - 10 Thailand', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 30, 6, 112);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sprouts - Corn', '0.00', 5, 2, 248);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Magnotta Bel Paese Red', '''"''', 27, 9, 128);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Ham - Smoked, Bone - In', '社會科學院語學研究所', 35, 1, 75);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Orange - Blood', '1E2', 29, 3, 156);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beans - Yellow', 'åß∂ƒ©˙∆˚¬…æ', 40, 1, 101);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sauce - Soya, Light', 'null', 8, 3, 149);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Swiss Chard', '`⁄€‹›ﬁﬂ‡°·‚—±', 16, 10, 34);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Ice Cream Bar - Oreo Cone', '''', 26, 6, 355);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Veal - Brisket, Provimi, Bone - In', '"''"''"''''''''"', 25, 7, 330);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Carbonated Water - Peach', 'NIL', 7, 2, 31);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Juice - Prune', '␢', 35, 8, 372);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chips - Doritos', '¸˛Ç◊ı˜Â¯˘¿', 3, 4, 217);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cup - 8oz Coffee Perforated', '1', 30, 4, 325);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - La Sauvagine', '-1E02', 12, 6, 249);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lettuce - Curly Endive', 'NIL', 10, 3, 177);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Herb Du Provence - Primerba', '-1E+02', 44, 6, 113);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pork - Back, Short Cut, Boneless', '-1.00', 48, 4, 41);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Ecolab - Balanced Fusion', '"''"''"''''''''"', 8, 2, 239);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chicken Thigh - Bone Out', '-1', 28, 1, 379);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tea - Herbal Orange Spice', '１２３', 49, 2, 278);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beans - Navy, Dry', '和製漢語', 49, 4, 458);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Mint - Fresh', '!@#$%^&*()', 15, 2, 92);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pancetta', '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', 37, 8, 245);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pork - Back Ribs', 'test⁠test‫', 48, 4, 215);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Chablis 2003 Champs', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 3, 3, 110);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sauce - Apple, Unsweetened', '¡™£¢∞§¶•ªº–≠', 38, 4, 462);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Vol Au Vents', 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', 7, 7, 399);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Coffee Cup 8oz 5338cd', '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', 6, 9, 424);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beer - Sleeman Fine Porter', 'パーティーへ行かないか', 48, 3, 472);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Balbach Riverside', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 43, 9, 159);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Taylors Reserve', '<script>alert(''hi'')</script>', 36, 4, 480);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Taro Leaves', '᠎', 15, 10, 25);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Soup Campbells Beef With Veg', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 28, 1, 403);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bacardi Breezer - Strawberry', '部落格', 6, 2, 459);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Casillero Del Diablo', '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', 37, 9, 297);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sobe - Green Tea', '⁦test⁧', 28, 8, 17);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tamarillo', '・(￣∀￣)・:*:', 15, 4, 195);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Swiss Sliced', ' test ', 11, 4, 222);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Crawfish', '部落格', 23, 7, 280);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Coffee - Beans, Whole', 'Œ„´‰ˇÁ¨ˆØ∏”’', 41, 4, 192);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Oven Mitt - 13 Inch', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 15, 2, 253);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sauce - Vodka Blush', '　', 31, 7, 410);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tomatillo', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 37, 8, 278);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Carrots - Purple, Organic', '(╯°□°）╯︵ ┻━┻)  ', 48, 1, 67);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lamb - Loin Chops', '00˙Ɩ$-', 23, 9, 94);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Rosso Toscano Igt', '1E+02', 39, 9, 250);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Mousse - Passion Fruit', 'パーティーへ行かないか', 49, 9, 321);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Ice Cream Bar - Oreo Sandwich', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 32, 5, 44);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Rice - 7 Grain Blend', '<>?:"{}|_+', 27, 1, 83);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Phyllo Dough', '00˙Ɩ$-', 45, 1, 228);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Glass - Juice Clear 5oz 55005', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 42, 8, 393);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cape Capensis - Fillet', '‫test‫', 17, 7, 194);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Yeast - Fresh, Fleischman', '¡™£¢∞§¶•ªº–≠', 50, 5, 469);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cake Circle, Foil, Scallop', '''''', 36, 9, 470);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Clementine', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 9, 7, 356);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Red, Pelee Island Merlot', '１２３', 49, 6, 496);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pasta - Angel Hair', '-1', 17, 3, 376);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Mozzarella, Buffalo', '¸˛Ç◊ı˜Â¯˘¿', 47, 3, 168);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Muffin - Mix - Creme Brule 15l', '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', 1, 10, 100);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Syrup - Monin - Granny Smith', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 44, 3, 32);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('English Muffin', '1E02', 20, 9, 260);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pear - Packum', 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', 40, 8, 439);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lettuce - Arugula', 'åß∂ƒ©˙∆˚¬…æ', 12, 8, 97);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Potato - Sweet', '1.00', 36, 8, 422);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cabbage - Green', '-$1.00', 43, 10, 238);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Quail - Jumbo', '¸˛Ç◊ı˜Â¯˘¿', 37, 6, 204);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lettuce - Green Leaf', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 35, 3, 258);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Turkey - Breast, Double', 'Ω≈ç√∫˜µ≤≥÷', 16, 10, 386);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Compound - Passion Fruit', '1E2', 45, 6, 266);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beef - Ox Tongue', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 48, 2, 413);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lemon Grass', '-1.00', 46, 5, 389);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Rosemary - Primerba, Paste', '<svg><script>0<1>alert(''XSS'')</script>', 23, 9, 116);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beef - Tenderloin', '!@#$%^&*()', 11, 10, 115);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Vidal Icewine Magnotta', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 18, 4, 246);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Rice - Brown', '　', 34, 4, 466);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tomatoes - Plum, Canned', ' ', 1, 4, 287);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Blue Nun Qualitatswein', 'NULL', 48, 7, 62);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Dr. Pepper - 355ml', 'Œ„´‰ˇÁ¨ˆØ∏”’', 6, 1, 411);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Jameson - Irish Whiskey', '(｡◕ ∀ ◕｡)', 14, 9, 421);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Soup - Campbells Asian Noodle', '<>?:"{}|_+', 30, 2, 494);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Octopus', 'パーティーへ行かないか', 24, 6, 423);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beans - Turtle, Black, Dry', '<img src=x onerror=alert(''hi'') />', 3, 6, 250);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tuna - Loin', '⁰⁴⁵₀₁₂', 16, 5, 78);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Ham - Cooked Bayonne Tinned', ' ', 5, 5, 340);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tomatoes - Grape', '␡', 28, 8, 385);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Coffee - Hazelnut Cream', '᠎', 29, 7, 185);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Shrimp - Black Tiger 6 - 8', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 2, 3, 347);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Cotes Du Rhone', ' ', 48, 10, 427);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Veal - Osso Bucco', '사회과학원 어학연구소', 44, 9, 102);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chicken - White Meat, No Tender', '`⁄€‹›ﬁﬂ‡°·‚—±', 7, 6, 426);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Tribal Sauvignon', '../../../../../../../../../../../etc/passwd%00', 46, 3, 257);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Yogurt - Strawberry, 175 Gr', '　', 28, 9, 451);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cake - Lemon Chiffon', ',./;''[]\-=', 20, 8, 67);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cloves - Ground', '１２３', 33, 10, 459);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lettuce Romaine Chopped', 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', 31, 4, 122);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Stock - Beef, Brown', '𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 10, 9, 458);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cookies - Assorted', '''"''', 41, 6, 297);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Rosemary - Primerba, Paste', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 41, 2, 201);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chocolate - Pistoles, White', '　', 9, 3, 375);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bag - Bread, White, Plain', '울란바토르', 14, 8, 428);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cake Circle, Foil, Scallop', '␡', 8, 7, 27);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Island Oasis - Ice Cream Mix', '1/0', 7, 4, 381);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chocolate Bar - Coffee Crisp', '(｡◕ ∀ ◕｡)', 43, 2, 293);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Shichimi Togarashi Peppeers', '울란바토르', 15, 8, 191);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tandoori Curry Paste', '`⁄€‹›ﬁﬂ‡°·‚—±', 31, 5, 439);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Compound - Raspberry', 'Œ„´‰ˇÁ¨ˆØ∏”’', 28, 9, 334);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beef - Tongue, Fresh', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 1, 1, 398);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beer - Mcauslan Apricot', '␡', 50, 9, 104);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Melon - Watermelon Yellow', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 15, 9, 303);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sauce - Demi Glace', '<script>alert(''hi'')</script>', 32, 1, 148);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('White Fish - Filets', '1/0', 45, 10, 243);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Guinea Fowl', '0.00', 9, 10, 463);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Trout - Hot Smkd, Dbl Fillet', '''', 34, 2, 457);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Butter - Salted', '''', 7, 6, 479);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Mace Ground', '<svg><script>0<1>alert(''XSS'')</script>', 32, 3, 284);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cabbage - Nappa', '-1', 3, 3, 407);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Puree - Pear', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 33, 7, 425);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sesame Seed Black', '␢', 47, 6, 202);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Muffin - Mix - Mango Sour Cherry', '𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 42, 10, 10);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cake - Mini Potato Pancake', '␢', 18, 5, 257);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Cava Aria Estate Brut', '00˙Ɩ$-', 30, 3, 266);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Bakers Cream Cheese', 'test⁠test‫', 7, 2, 210);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Daves Island Stinger', 'Ω≈ç√∫˜µ≤≥÷', 14, 5, 154);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Flavouring - Rum', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 48, 6, 158);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Pied De Vents', '<>?:"{}|_+', 15, 9, 410);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Guy Sage Touraine', '田中さんにあげて下さい', 25, 1, 26);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Juice - Ocean Spray Kiwi', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 18, 3, 163);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tea - Vanilla Chai', '-$1.00', 38, 7, 494);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cookie Trail Mix', '"', 45, 10, 353);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cream - 18%', '1''; DROP TABLE users--', 20, 3, 244);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Apples - Sliced / Wedge', '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 3, 4, 65);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Trout Rainbow Whole', '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕', 40, 6, 115);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Red Oakridge Merlot', '<>?:"{}|_+', 5, 4, 138);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sandwich Wrap', '<>?:"{}|_+', 17, 6, 58);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chocolate - Dark Callets', '・(￣∀￣)・:*:', 21, 5, 5);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Snapple Raspberry Tea', '() { 0; }; touch /tmp/blns.shellshock1.fail;', 12, 3, 150);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lamb Rack Frenched Australian', '​', 46, 2, 350);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cookies Oatmeal Raisin', '0.00', 7, 8, 398);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Vermouth - Sweet, Cinzano', '‪‪test‪', 22, 5, 192);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cactus Pads', '・(￣∀￣)・:*:', 19, 2, 355);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Mushroom Morel Fresh', '''"''', 49, 9, 339);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Vodka - Smirnoff', '<svg><script>0<1>alert(''XSS'')</script>', 40, 3, 309);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - White, Ej', 'test⁠test‫', 49, 5, 460);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Rubyport', '␢', 12, 6, 202);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bread - White Epi Baguette', '00˙Ɩ$-', 43, 8, 452);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Magnotta - Bel Paese White', '''''', 2, 9, 284);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Mix', '-1E02', 46, 4, 174);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pepper - Roasted Red', '<script>alert(''hi'')</script>', 4, 8, 467);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Blueberries - Frozen', '`⁄€‹›ﬁﬂ‡°·‚—±', 24, 2, 354);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Dubouef Macon - Villages', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 24, 7, 265);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Appetizer - Southwestern', ' test ', 34, 1, 146);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Rice - Brown', '"', 10, 2, 67);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Marble', '<svg><script>0<1>alert(''XSS'')</script>', 9, 4, 26);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Miso - Soy Bean Paste', 'åß∂ƒ©˙∆˚¬…æ', 31, 10, 381);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Rice Wine - Aji Mirin', '﻿', 36, 10, 12);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Corn Shoots', '1;DROP TABLE users', 33, 1, 185);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lettuce - Belgian Endive', 'åß∂ƒ©˙∆˚¬…æ', 36, 7, 8);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Mushroom - Shitake, Fresh', '‫test‫', 12, 2, 179);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bread - Rolls, Rye', '-$1.00', 16, 3, 451);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bacardi Mojito', '😍', 10, 7, 34);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Capon - Breast, Double, Wing On', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 40, 8, 53);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Marlbourough Sauv Blanc', '١٢٣', 50, 8, 124);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Iced Tea - Lemon, 340ml', '-1/2', 43, 1, 132);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Salt - Celery', '`⁄€‹›ﬁﬂ‡°·‚—±', 5, 9, 439);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beer - Labatt Blue', '1E02', 38, 8, 298);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tomatoes Tear Drop', '''', 40, 4, 190);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Juice - Grape, White', '｀ｨ(´∀｀∩', 19, 2, 427);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Vovray Sec Domaine Huet', '⁰⁴⁵₀₁₂', 6, 8, 157);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Oil - Olive, Extra Virgin', '""', 32, 5, 196);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Dr. Pepper - 355ml', '1.00', 15, 2, 79);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Soup - Campbells, Cream Of', '(╯°□°）╯︵ ┻━┻)  ', 25, 6, 439);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pepper - Paprika, Hungarian', ' test ', 4, 10, 404);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Zucchini - Green', 'NULL', 19, 3, 395);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Longos - Chicken Wings', '¸˛Ç◊ı˜Â¯˘¿', 35, 9, 327);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Muffin Mix - Blueberry', '<>?:"{}|_+', 19, 7, 462);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Veal - Brisket, Provimi,bnls', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 27, 4, 312);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pasta - Orecchiette', '<svg><script>0<1>alert(''XSS'')</script>', 36, 1, 487);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chips - Miss Vickies', '　', 43, 10, 280);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tray - Foam, Square 4 - S', '1.00', 50, 8, 5);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cleaner - Comet', '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 9, 1, 215);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chicken - White Meat With Tender', '1''; DROP TABLE users--', 19, 10, 33);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pork - Hock And Feet Attached', '1E2', 40, 10, 414);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chicken - Wieners', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 48, 9, 430);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bread - Pita, Mini', '-1E02', 31, 10, 142);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cup - 8oz Coffee Perforated', '⁰⁴⁵', 17, 10, 42);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cinnamon - Ground', '../../../../../../../../../../../etc/passwd%00', 34, 2, 325);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Spice - Montreal Steak Spice', '␢', 22, 3, 123);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sugar - Individual Portions', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 7, 5, 43);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Saskatoon Berries - Frozen', '"''"''"''''''''"', 17, 2, 67);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Segura Viudas Aria Brut', '../../../../../../../../../../../etc/passwd%00', 20, 3, 237);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Burger Veggie', 'œ∑´®†¥¨ˆøπ“‘', 49, 7, 169);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Dill - Primerba, Paste', '1''; DROP TABLE users--', 11, 10, 179);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Puree - Kiwi', '‫test‫', 1, 9, 299);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Venison - Striploin', '<>?:"{}|_+', 25, 4, 233);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Mortadella', '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 36, 5, 173);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Spring Roll Wrappers', '''"''', 36, 1, 241);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pepper - Chipotle, Canned', '⁰⁴⁵', 2, 7, 434);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Woolwich Goat, Log', '0/0', 19, 7, 166);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tea - Honey Green Tea', '-1E2', 7, 7, 160);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pear - Halves', '␢', 43, 7, 44);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Two Oceans Sauvignon', '"', 48, 5, 277);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beef - Ground Medium', '1.00', 42, 9, 414);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Doilies - 5, Paper', '__ﾛ(,_,*)', 23, 7, 361);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lamb Shoulder Boneless Nz', '1', 32, 8, 189);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cake - Miini Cheesecake Cherry', '<script>alert(''hi'')</script>', 17, 8, 130);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Flour - So Mix Cake White', '⁦test⁧', 34, 8, 446);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Mix - Cappucino Cocktail', '👩🏽', 10, 2, 331);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Spice - Chili Powder Mexican', '-1.00', 32, 4, 296);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bread Base - Gold Formel', '<>?:"{}|_+', 37, 3, 473);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Foil - Round Foil', '-$1.00', 8, 1, 413);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bread Bowl Plain', ' test ', 6, 3, 355);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Apple - Royal Gala', '１２３', 16, 2, 238);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Island Oasis - Mango Daiquiri', '１２３', 10, 6, 167);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Broom - Push', '1E+02', 6, 9, 211);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chevere Logs', '""', 26, 4, 50);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Honey - Comb', '00˙Ɩ$-', 12, 1, 341);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Muffin Hinge 117n', '"', 9, 2, 436);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cookies Almond Hazelnut', '-1E2', 11, 4, 29);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lettuce - Treviso', '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 20, 9, 269);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Green Tea Refresher', '␡', 7, 6, 435);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Juice - Mango', 'test⁠test‫', 50, 9, 255);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Crush - Grape, 355 Ml', '$1.00', 21, 7, 376);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Dc - Sakura Fu', '(｡◕ ∀ ◕｡)', 34, 8, 326);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pepper - Roasted Red', '울란바토르', 50, 3, 146);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pecan Raisin - Tarts', '1E02', 15, 10, 309);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chocolate - Compound Coating', '-1', 32, 10, 316);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pork - Kidney', '¡™£¢∞§¶•ªº–≠', 1, 4, 109);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Fireball Whisky', '部落格', 8, 1, 407);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pasta - Fettuccine, Egg, Fresh', '１２３', 35, 3, 439);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Canada Dry', '1E2', 45, 1, 353);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lamb - Rack', '1E02', 14, 10, 261);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tea - Herbal - 6 Asst', '⁦test⁧', 44, 5, 338);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bread - Burger', '␣', 1, 2, 470);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Provolone', '🐵 🙈 🙉 🙊', 20, 8, 328);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Soup - Campbells Chili Veg', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 25, 9, 275);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Skirt - 24 Foot', '₀₁₂', 34, 7, 301);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Sherry Dry Sack, William', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 25, 6, 400);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Red, Gamay Noir', '../../../../../../../../../../../etc/passwd%00', 32, 1, 318);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Manchego, Spanish', '<script>alert(''hi'')</script>', 18, 5, 383);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bread - Pullman, Sliced', '-1E02', 50, 10, 9);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beef - Bones, Marrow', 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', 16, 3, 425);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Myers Planters Punch', '‪‪test‪', 5, 10, 271);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Fontina', '和製漢語', 39, 4, 471);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Baron De Rothschild', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 15, 7, 419);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Relish', '-1E2', 18, 6, 231);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sauerkraut', '‪‪test‪', 42, 10, 489);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beets', '​', 46, 1, 475);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Glove - Cutting', 'œ∑´®†¥¨ˆøπ“‘', 13, 8, 396);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Roe - Flying Fish', '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 4, 8, 155);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Kahlua', '''"''', 41, 10, 357);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Mussels - Frozen', '../../../../../../../../../../../etc/passwd%00', 44, 3, 277);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Salt - Table', '␢', 48, 1, 279);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Ostrich - Prime Cut', '""', 41, 1, 4);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bread - Malt', '﻿', 39, 9, 484);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Veal - Inside', 'œ∑´®†¥¨ˆøπ“‘', 17, 8, 429);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Mushrooms - Honey', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 8, 2, 103);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pail For Lid 1537', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 39, 8, 313);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Mozzarella, Shredded', 'Ω≈ç√∫˜µ≤≥÷', 1, 8, 108);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Stainless Steel Cleaner Vision', ' ', 30, 1, 223);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Rappini - Andy Boy', '''''', 5, 10, 210);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tendrils - Baby Pea, Organic', '‫test‫', 47, 3, 26);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bread - Rosemary Focaccia', '<svg><script>0<1>alert(''XSS'')</script>', 35, 7, 63);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Iced Tea - Lemon, 340ml', '社會科學院語學研究所', 9, 4, 82);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Squid - Tubes / Tenticles 10/20', '١٢٣', 10, 7, 112);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sauce - Rosee', '../../../../../../../../../../../etc/passwd%00', 14, 4, 164);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pork - Loin, Bone - In', '"''''''''"''"', 23, 9, 66);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Syrup - Monin - Granny Smith', '｀ｨ(´∀｀∩', 49, 5, 480);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bagel - Sesame Seed Presliced', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 23, 10, 456);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pie Filling - Pumpkin', ',./;''[]\-=', 18, 6, 40);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Syrup - Pancake', '1.00', 41, 5, 289);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Flour - Pastry', '/dev/null; touch /tmp/blns.fail ; echo', 39, 4, 199);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Eggplant - Regular', '1E02', 17, 4, 266);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Muffin - Mix - Strawberry Rhubarb', '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 33, 8, 110);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Dasheen', '部落格', 37, 1, 129);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pork - Tenderloin, Frozen', '‪‪test‪', 16, 3, 471);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Calypso - Lemonade', '1;DROP TABLE users', 9, 2, 176);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pectin', 'test⁠test‫', 24, 3, 60);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Table Cloth 72x144 White', '울란바토르', 12, 5, 286);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Cave Springs Dry Riesling', '/dev/null; touch /tmp/blns.fail ; echo', 29, 1, 169);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Squash - Butternut', '・(￣∀￣)・:*:', 2, 5, 470);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sole - Fillet', '部落格', 6, 2, 146);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Spice - Onion Powder Granulated', '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', 27, 8, 90);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Compound - Raspberry', '␢', 48, 5, 167);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Fudge - Chocolate Fudge', 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', 9, 8, 439);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sambuca - Opal Nera', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 27, 7, 387);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Chablis 2003 Champs', '0.00', 30, 9, 388);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Yukon Jack', '() { 0; }; touch /tmp/blns.shellshock1.fail;', 43, 7, 180);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cucumber - English', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 36, 8, 156);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Plate Pie Foil', '¡™£¢∞§¶•ªº–≠', 12, 10, 4);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cucumber - English', '<img src=x onerror=alert(''hi'') />', 29, 9, 463);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Broccoli - Fresh', '../../../../../../../../../../../etc/hosts', 15, 9, 413);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Curry Paste - Green Masala', '../../../../../../../../../../../etc/hosts', 41, 4, 230);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Yogurt - Blueberry, 175 Gr', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 15, 5, 116);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cookies - Fortune', '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', 16, 1, 466);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cornish Hen', ' test ', 24, 1, 407);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Chocolate - Chips Compound', 'Œ„´‰ˇÁ¨ˆØ∏”’', 22, 3, 56);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Squash - Guords', 'œ∑´®†¥¨ˆøπ“‘', 47, 8, 155);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lobster - Tail, 3 - 4 Oz', '␢', 39, 9, 173);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Phyllo Dough', '１２３', 1, 9, 461);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beef - Ox Tail, Frozen', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 25, 9, 436);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cloves - Ground', '1', 16, 3, 470);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Fish - Atlantic Salmon, Cold', '社會科學院語學研究所', 4, 3, 190);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pastry - French Mini Assorted', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 43, 9, 145);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cocoa Feuilletine', ',./;''[]\-=', 36, 7, 259);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Flour - Bran, Red', '-1E+02', 31, 7, 104);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pepperoni Slices', '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 10, 7, 240);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sultanas', '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', 3, 10, 75);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pear - Packum', '/dev/null; touch /tmp/blns.fail ; echo', 13, 10, 379);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Veal - Chops, Split, Frenched', '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕', 6, 8, 377);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Food Colouring - Red', '<>?:"{}|_+', 9, 5, 486);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Oil - Cooking Spray', 'NULL', 34, 5, 410);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tea - Orange Pekoe', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 34, 8, 480);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Arctic Char - Fresh, Whole', '-1', 26, 3, 458);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Soap - Pine Sol Floor Cleaner', '<>?:"{}|_+', 50, 4, 245);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lettuce - Boston Bib - Organic', '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', 7, 7, 125);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Maple Syrup', '😍', 20, 2, 126);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Sawmill Creek Autumn', '''', 23, 1, 467);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Ketchup - Tomato', '␢', 22, 5, 299);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beef - Roasted, Cooked', '1', 33, 1, 283);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sole - Fillet', 'Œ„´‰ˇÁ¨ˆØ∏”’', 42, 4, 66);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Veal - Sweetbread', '1', 37, 1, 452);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - White, Ej', 'NIL', 30, 5, 295);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('The Pop Shoppe - Root Beer', '١٢٣', 42, 5, 403);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Port Late Bottled Vintage', '(╯°□°）╯︵ ┻━┻)  ', 48, 3, 341);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Longos - Chicken Curried', '(｡◕ ∀ ◕｡)', 40, 5, 455);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Coffee Beans - Chocolate', '｀ｨ(´∀｀∩', 43, 3, 199);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Salsify, Organic', '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 29, 1, 440);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Veal - Insides, Grains', 'ÅÍÎÏ˝ÓÔÒÚÆ☃', 48, 2, 480);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Monkfish Fresh - Skin Off', '''', 17, 2, 51);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Oneshot Automatic Soap System', '"''''''''"''"', 32, 6, 169);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Broccoli - Fresh', 'œ∑´®†¥¨ˆøπ“‘', 16, 7, 340);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beer - Upper Canada Light', '<script>alert(''hi'')</script>', 22, 3, 289);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pork - Bacon,back Peameal', '""', 31, 9, 120);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beer - Molson Excel', '᠎', 11, 3, 497);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beans - Kidney, Red Dry', '🐵 🙈 🙉 🙊', 36, 1, 10);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Ruffino Chianti', '"', 23, 6, 328);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Lady Fingers', '｀ｨ(´∀｀∩', 9, 1, 454);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Gelatine Leaves - Bulk', 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', 45, 6, 195);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Squash - Butternut', '‪‪test‪', 3, 7, 347);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Salmon - Whole, 4 - 6 Pounds', 'הָיְתָהtestالصفحات التّحول', 50, 3, 107);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pasta - Detalini, White, Fresh', '1.00', 15, 4, 79);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Trout - Hot Smkd, Dbl Fillet', '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', 33, 9, 334);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pork - Belly Fresh', '-$1.00', 27, 1, 8);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Almonds Ground Blanched', '../../../../../../../../../../../etc/hosts', 41, 5, 242);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Yogurt - French Vanilla', '1/0', 22, 6, 364);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Sauvignon Blanc Oyster', '1/0', 9, 8, 282);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Five Alive Citrus', '__ﾛ(,_,*)', 10, 6, 29);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Sicilia Igt Nero Avola', '😍', 21, 1, 112);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Veal - Knuckle', '<img src=x onerror=alert(''hi'') />', 31, 9, 269);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Soup - Chicken And Wild Rice', 'test⁠test‫', 20, 1, 156);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cheese - Feta', '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 41, 10, 250);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - White, Gewurtzraminer', '''"''', 26, 7, 226);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Graham Cracker Mix', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 20, 4, 271);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Water - Spring 1.5lit', '﻿', 47, 8, 396);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Fruit Salad Deluxe', '١٢٣', 24, 6, 472);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Butter Balls Salted', '｀ｨ(´∀｀∩', 4, 4, 320);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Wine - Taylors Reserve', '''''', 15, 6, 304);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('English Muffin', null, 18, 8, 212);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Island Oasis - Cappucino Mix', '😍', 47, 9, 304);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Basil - Dry, Rubbed', '(｡◕ ∀ ◕｡)', 41, 2, 27);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Club Soda - Schweppes, 355 Ml', '() { 0; }; touch /tmp/blns.shellshock1.fail;', 2, 4, 210);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Sauce - Mint', '''''', 29, 2, 173);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Blackberries', '사회과학원 어학연구소', 4, 3, 251);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bread - Sour Batard', '␣', 15, 8, 481);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Cookies Cereal Nut', '/dev/null; touch /tmp/blns.fail ; echo', 31, 7, 397);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bread - Italian Roll With Herbs', '🐵 🙈 🙉 🙊', 25, 4, 113);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Ice Cream - Strawberry', '｀ｨ(´∀｀∩', 40, 7, 378);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Beer - Molson Excel', 'NULL', 16, 7, 436);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Squid - Tubes / Tenticles 10/20', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 23, 8, 325);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tomatoes - Heirloom', '-1.00', 20, 6, 390);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Schnappes - Peach, Walkers', '␡', 48, 9, 439);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Bacardi Breezer - Tropical', '1E+02', 5, 9, 65);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Buffalo - Short Rib Fresh', '😍', 36, 9, 176);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Tea - Decaf 1 Cup', '<img src=x onerror=alert(''hi'') />', 50, 7, 11);
insert into plato (nombre, descripcion, precio, rating_medio, id_vendedor) values ('Pepper - Orange', '・(￣∀￣)・:*:', 26, 5, 493);
