insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (1, 'Cheese - Parmesan Cubes', '(╯°□°）╯︵ ┻━┻)  ', 1, 7, 100);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (2, 'Wine - Two Oceans Sauvignon', '␡', 12, 7, 387);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (3, 'Bread - Italian Roll With Herbs', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 10, 10, 228);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (4, 'Sausage - Andouille', '1E+02', 42, 1, 397);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (5, 'Guava', '🐵 🙈 🙉 🙊', 22, 3, 64);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (6, 'Uniform Linen Charge', '(｡◕ ∀ ◕｡)', 10, 3, 166);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (7, 'Peas - Frozen', '和製漢語', 19, 2, 83);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (8, 'Pomegranates', null, 30, 6, 165);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (9, 'Oil - Peanut', 'Œ„´‰ˇÁ¨ˆØ∏”’', 7, 7, 339);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (10, 'Laundry - Bag Cloth', 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', 28, 7, 195);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (11, 'V8 - Tropical Blend', '部落格', 10, 2, 357);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (12, 'Mousse - Mango', '部落格', 2, 3, 204);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (13, 'Pork - Sausage Casing', '﻿', 22, 7, 279);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (14, 'Sauce - Soya, Dark', '1', 7, 7, 449);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (15, 'Carrots - Mini Red Organic', 'null', 46, 8, 165);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (16, 'Cotton Wet Mop 16 Oz', '和製漢語', 29, 9, 101);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (17, 'Eggplant Oriental', '(╯°□°）╯︵ ┻━┻)  ', 32, 10, 230);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (18, 'Flavouring - Rum', '¡™£¢∞§¶•ªº–≠', 39, 3, 226);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (19, 'Lamb - Leg, Boneless', '1', 21, 2, 87);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (20, 'Island Oasis - Lemonade', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 35, 7, 332);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (21, 'Wine - Sawmill Creek Autumn', '¸˛Ç◊ı˜Â¯˘¿', 4, 4, 403);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (22, 'Bulgar', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 26, 10, 276);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (23, 'Boogies', '‪‪test‪', 10, 6, 456);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (24, 'Lady Fingers', '｀ｨ(´∀｀∩', 34, 8, 319);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (25, 'Chips Potato Reg 43g', 'Œ„´‰ˇÁ¨ˆØ∏”’', 21, 7, 17);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (26, 'Pepsi - Diet, 355 Ml', '社會科學院語學研究所', 21, 6, 390);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (27, 'Hersey Shakes', 'null', 11, 10, 97);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (28, 'Pork - Backfat', '　', 46, 9, 315);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (29, 'Vermouth - Sweet, Cinzano', '😍', 16, 8, 481);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (30, 'Island Oasis - Lemonade', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 12, 9, 10);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (31, 'Wine - Sogrape Mateus Rose', 'åß∂ƒ©˙∆˚¬…æ', 4, 4, 214);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (32, 'Salt - Seasoned', '""', 11, 8, 149);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (33, 'Scallops 60/80 Iqf', '١٢٣', 36, 5, 64);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (34, 'Venison - Racks Frenched', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 47, 2, 196);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (35, 'Coffee - French Vanilla Frothy', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 30, 10, 197);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (36, 'Cherries - Bing, Canned', '1/0', 14, 1, 407);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (37, 'Egg Patty Fried', '﻿', 6, 5, 300);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (38, 'Trout - Rainbow, Fresh', '''"''', 4, 5, 310);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (39, 'Lidsoupcont Rp12dn', '!@#$%^&*()', 8, 10, 20);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (40, 'Wine - Red, Mouton Cadet', '-1/2', 24, 10, 402);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (41, 'Brandy Cherry - Mcguinness', null, 22, 9, 476);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (42, 'Asparagus - White, Canned', '¸˛Ç◊ı˜Â¯˘¿', 46, 9, 52);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (43, 'Schnappes Peppermint - Walker', '‪‪test‪', 45, 1, 410);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (44, 'Cherries - Maraschino,jar', '1;DROP TABLE users', 47, 9, 88);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (45, 'Wine - Shiraz South Eastern', null, 46, 8, 278);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (46, 'Wine - Alsace Riesling Reserve', '部落格', 37, 10, 306);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (47, 'Wine - Red, Mosaic Zweigelt', '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', 45, 8, 208);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (48, 'Sobe - Cranberry Grapefruit', 'NIL', 47, 2, 38);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (49, 'Wiberg Cure', '"', 50, 8, 262);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (50, 'Wine - Prosecco Valdobiaddene', '・(￣∀￣)・:*:', 15, 8, 262);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (51, 'Chick Peas - Canned', '田中さんにあげて下さい', 19, 1, 288);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (52, 'Pur Source', '1;DROP TABLE users', 10, 5, 267);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (53, 'Rootbeer', '(╯°□°）╯︵ ┻━┻)  ', 35, 2, 431);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (54, 'Cheese - Cambozola', '␡', 11, 2, 373);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (55, 'Sugar - Brown', '<script>alert(''hi'')</script>', 44, 2, 202);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (56, 'Muffin Orange Individual', '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕', 35, 10, 352);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (57, 'Milkettes - 2%', '-1/2', 41, 2, 240);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (58, 'Lemonade - Pineapple Passion', 'œ∑´®†¥¨ˆøπ“‘', 35, 4, 340);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (59, 'Coke - Diet, 355 Ml', '00˙Ɩ$-', 29, 3, 487);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (60, 'Sauce - Thousand Island', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 37, 9, 184);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (61, 'Graham Cracker Mix', '1E02', 16, 5, 413);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (62, 'Mayonnaise', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 30, 8, 367);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (63, 'Sea Urchin', '00˙Ɩ$-', 12, 4, 250);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (64, 'Muffin - Mix - Bran And Maple 15l', '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', 47, 3, 446);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (65, 'Coffee Cup 8oz 5338cd', '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 28, 9, 261);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (66, 'Soup - Campbells, Cream Of', '(｡◕ ∀ ◕｡)', 4, 8, 487);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (67, 'Cheese - Victor Et Berthold', '-1E2', 20, 9, 469);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (68, 'Mustard - Pommery', '''', 38, 1, 119);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (69, 'Bag - Clear 7 Lb', '''"''', 49, 3, 283);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (70, 'Cheese - Cheddar, Medium', '1', 26, 4, 226);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (71, 'Quiche Assorted', 'null', 18, 7, 477);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (72, 'Tray - 16in Rnd Blk', 'œ∑´®†¥¨ˆøπ“‘', 14, 3, 500);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (73, 'French Pastries', 'null', 33, 8, 87);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (74, 'Puff Pastry - Sheets', '"''"''"''''''''"', 46, 3, 98);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (75, 'Passion Fruit', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 1, 5, 203);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (76, 'Cream - 35%', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 44, 9, 82);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (77, 'Jam - Apricot', '👩🏽', 16, 8, 122);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (78, 'Sprite - 355 Ml', '../../../../../../../../../../../etc/passwd%00', 24, 9, 498);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (79, 'Veal - Osso Bucco', '-1E2', 20, 5, 67);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (80, 'Ginsing - Fresh', '𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 41, 8, 256);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (81, 'Tart Shells - Barquettes, Savory', '和製漢語', 17, 8, 407);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (82, 'Bread - Raisin Walnut Oval', '社會科學院語學研究所', 11, 5, 253);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (83, 'Soup Campbells - Italian Wedding', '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧', 14, 4, 124);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (84, 'Miso Paste White', '__ﾛ(,_,*)', 4, 1, 2);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (85, 'Beef - Rib Eye Aaa', 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', 26, 9, 465);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (86, 'Sauce - Black Current, Dry Mix', 'œ∑´®†¥¨ˆøπ“‘', 41, 5, 53);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (87, 'Wine - Montecillo Rioja Crianza', '␣', 46, 1, 154);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (88, 'Lettuce - Sea / Sea Asparagus', '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕', 50, 6, 110);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (89, 'Onions Granulated', '部落格', 2, 4, 266);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (90, 'Pasta - Cappellini, Dry', '''', 49, 10, 23);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (91, 'Ice Cream - Strawberry', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 31, 2, 165);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (92, 'Apple - Delicious, Red', '-$1.00', 26, 6, 337);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (93, 'Soup - Tomato Mush. Florentine', '-1E2', 30, 3, 161);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (94, 'Celery', '<script>alert(''hi'')</script>', 7, 6, 94);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (95, 'Chevere Logs', '-1', 37, 7, 91);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (96, 'Wine - Alsace Gewurztraminer', '　', 11, 10, 3);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (97, 'Wine - Saint Emilion Calvet', '../../../../../../../../../../../etc/hosts', 18, 10, 463);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (98, 'Lid - 10,12,16 Oz', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 49, 6, 357);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (99, 'Raspberries - Frozen', '''"''', 14, 6, 89);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (100, 'Cheese - Boursin, Garlic / Herbs', '사회과학원 어학연구소', 49, 10, 292);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (101, 'French Pastries', '''', 49, 10, 495);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (102, 'Longos - Chicken Curried', '・(￣∀￣)・:*:', 5, 3, 287);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (103, 'Chinese Foods - Plain Fried Rice', '!@#$%^&*()', 42, 7, 161);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (104, 'Lobak', '部落格', 22, 6, 219);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (105, 'Cheese - Mozzarella, Shredded', '和製漢語', 32, 6, 100);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (106, 'Soup - Campbells Chili Veg', 'œ∑´®†¥¨ˆøπ“‘', 50, 7, 22);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (107, 'Cake Sheet Combo Party Pack', '١٢٣', 50, 4, 418);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (108, 'Sauce - Sesame Thai Dressing', '1/2', 47, 9, 259);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (109, 'The Pop Shoppe - Grape', '''''', 14, 6, 373);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (110, 'Cloves - Ground', '部落格', 11, 7, 176);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (111, 'Yoplait - Strawbrasp Peac', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 27, 4, 343);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (112, 'Contreau', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 2, 10, 349);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (113, 'Lemonade - Natural, 591 Ml', '''"''', 9, 3, 333);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (114, 'Orange - Tangerine', '울란바토르', 26, 3, 216);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (115, 'Herb Du Provence - Primerba', '⁰⁴⁵', 43, 4, 367);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (116, 'Coconut - Shredded, Unsweet', 'null', 37, 7, 112);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (117, 'Cloves - Ground', '¸˛Ç◊ı˜Â¯˘¿', 49, 10, 121);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (118, 'Wine - Fontanafredda Barolo', '"', 47, 8, 106);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (119, 'Island Oasis - Banana Daiquiri', ' test ', 19, 3, 290);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (120, 'Puree - Raspberry', '<script>alert(''hi'')</script>', 15, 10, 379);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (121, 'Wine - Kwv Chenin Blanc South', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 21, 6, 153);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (122, 'Tortillas - Flour, 10', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 47, 1, 76);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (123, 'Milk - 2% 250 Ml', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 41, 6, 480);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (124, 'Chervil - Fresh', '$1.00', 22, 4, 453);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (125, 'Crackers - Soda / Saltins', 'ÅÍÎÏ˝ÓÔÒÚÆ☃', 17, 2, 380);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (126, 'Milkettes - 2%', '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧', 5, 1, 275);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (127, 'Pasta - Linguini, Dry', '-1', 24, 6, 195);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (128, 'Carbonated Water - Blackcherry', 'パーティーへ行かないか', 42, 4, 141);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (129, 'Nantucket - Orange Mango Cktl', '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', 10, 7, 434);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (130, 'Chicken - Livers', 'nil', 39, 6, 314);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (131, 'Urban Zen Drinks', '１２３', 44, 8, 107);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (132, 'Hipnotiq Liquor', '-$1.00', 38, 8, 268);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (133, 'Soup - Cream Of Broccoli, Dry', '1E02', 11, 2, 480);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (134, 'Nantucket Cranberry Juice', '''"''', 32, 1, 166);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (135, 'Ham - Black Forest', '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 45, 5, 256);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (136, 'Bread - Raisin Walnut Oval', '1''; DROP TABLE users--', 1, 3, 352);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (137, 'Oil - Olive', '-1E+02', 33, 5, 475);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (138, 'Wine - Magnotta - Cab Sauv', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 17, 7, 48);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (139, 'Crawfish', '‫test‫', 15, 1, 94);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (140, 'Jam - Raspberry,jar', '1''; DROP TABLE users--', 9, 4, 302);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (141, 'Fennel - Seeds', '｀ｨ(´∀｀∩', 30, 1, 418);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (142, 'Wine - Beaujolais Villages', '-$1.00', 23, 8, 81);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (143, 'Lotus Rootlets - Canned', '𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 6, 9, 268);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (144, 'Asparagus - White, Canned', ',./;''[]\-=', 19, 9, 219);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (145, 'Water - Mineral, Natural', '""', 39, 6, 150);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (146, 'Juice - Lagoon Mango', '␢', 26, 6, 46);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (147, 'Juice - V8, Tomato', '__ﾛ(,_,*)', 15, 7, 216);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (148, 'Wine - White, Ej Gallo', '﻿', 29, 6, 463);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (149, 'Wheat - Soft Kernal Of Wheat', '社會科學院語學研究所', 24, 8, 438);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (150, 'Longos - Burritos', '-1', 20, 4, 266);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (151, 'Pasta - Canelloni', '１２３', 12, 2, 116);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (152, 'Plastic Arrow Stir Stick', '"', 29, 10, 10);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (153, 'Chutney Sauce', '᠎', 33, 10, 210);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (154, 'Wine - Tio Pepe Sherry Fino', ' ', 4, 5, 335);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (155, 'Soup - Campbells Beef Stew', '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', 26, 3, 158);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (156, 'Squash - Butternut', '1/0', 13, 9, 112);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (157, 'Oil - Macadamia', '`⁄€‹›ﬁﬂ‡°·‚—±', 15, 2, 430);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (158, 'Gherkin', '😍', 36, 7, 261);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (159, 'Beets - Golden', '١٢٣', 31, 8, 297);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (160, 'Bread - Dark Rye, Loaf', '(｡◕ ∀ ◕｡)', 34, 6, 317);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (161, 'Cabbage - Green', '../../../../../../../../../../../etc/hosts', 16, 7, 368);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (162, 'Nut - Cashews, Whole, Raw', '<svg><script>0<1>alert(''XSS'')</script>', 4, 5, 429);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (163, 'Nantucket - 518ml', '-1E02', 16, 1, 472);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (164, 'Anchovy In Oil', '・(￣∀￣)・:*:', 6, 10, 344);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (165, 'Pickle - Dill', '¡™£¢∞§¶•ªº–≠', 32, 1, 270);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (166, 'Longos - Assorted Sandwich', '1', 26, 10, 379);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (167, 'Lemonade - Pineapple Passion', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 23, 8, 186);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (168, 'Beans - Fava Fresh', '`⁄€‹›ﬁﬂ‡°·‚—±', 31, 2, 265);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (169, 'Wine - Vidal Icewine Magnotta', '-1', 17, 10, 256);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (170, 'Sugar - Icing', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 45, 6, 238);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (171, 'Fish - Base, Bouillion', '𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 9, 5, 129);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (172, 'Ice Cream - Life Savers', '__ﾛ(,_,*)', 6, 7, 459);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (173, 'Nut - Cashews, Whole, Raw', '田中さんにあげて下さい', 12, 8, 188);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (174, 'Wine - Zinfandel California 2002', '１２３', 24, 8, 101);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (175, 'Mince Meat - Filling', '᠎', 44, 9, 204);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (176, 'Melon - Honey Dew', '../../../../../../../../../../../etc/hosts', 36, 5, 128);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (177, 'Lamb - Loin Chops', '1/0', 27, 9, 24);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (178, 'Wasabi Paste', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 28, 3, 465);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (179, 'Garam Masala Powder', '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧', 40, 2, 300);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (180, 'Zucchini - Yellow', '😍', 5, 7, 123);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (181, 'Persimmons', 'Ω≈ç√∫˜µ≤≥÷', 1, 1, 410);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (182, 'V8 - Tropical Blend', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 14, 4, 426);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (183, 'Appetizer - Shrimp Puff', '-1E02', 14, 3, 23);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (184, 'Dry Ice', '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', 13, 4, 124);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (185, 'Onions - Spanish', '₀₁₂', 30, 4, 53);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (186, 'Pastry - French Mini Assorted', '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 8, 8, 32);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (187, 'Peppercorns - Green', '../../../../../../../../../../../etc/hosts', 4, 1, 231);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (188, 'Sobe - Cranberry Grapefruit', '社會科學院語學研究所', 46, 1, 47);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (189, 'Tomato - Green', '😍', 42, 3, 425);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (190, 'Loaf Pan - 2 Lb, Foil', '1/2', 17, 2, 209);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (191, 'Pail - 4l White, With Handle', '👩🏽', 2, 5, 30);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (192, 'Cauliflower', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 45, 10, 277);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (193, 'Banana - Green', '-1E02', 33, 2, 264);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (194, 'Salt - Table', '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧', 12, 10, 455);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (195, 'Pasta - Spaghetti, Dry', '1/2', 6, 3, 334);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (196, 'Lychee', '-1/2', 19, 10, 239);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (197, 'Tomatoes - Vine Ripe, Yellow', 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', 34, 2, 71);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (198, 'Lidsoupcont Rp12dn', 'NULL', 11, 3, 303);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (199, 'Potatoes - Peeled', '1', 49, 8, 150);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (200, 'Wine - Chenin Blanc K.w.v.', 'NIL', 49, 5, 273);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (201, 'Nut - Almond, Blanched, Ground', 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', 33, 4, 147);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (202, 'Nutmeg - Ground', '../../../../../../../../../../../etc/hosts', 38, 7, 418);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (203, 'Beef - Rouladin, Sliced', '<img src=x onerror=alert(''hi'') />', 43, 2, 141);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (204, 'Macaroons - Two Bite Choc', '0.00', 12, 3, 284);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (205, 'Beef - Top Sirloin - Aaa', 'Œ„´‰ˇÁ¨ˆØ∏”’', 10, 3, 328);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (206, 'Pork - Sausage Casing', '() { 0; }; touch /tmp/blns.shellshock1.fail;', 39, 8, 127);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (207, 'Water - Evian 355 Ml', 'åß∂ƒ©˙∆˚¬…æ', 29, 7, 285);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (208, 'Wine - Malbec Trapiche Reserve', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 3, 3, 482);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (209, 'Pork Casing', '../../../../../../../../../../../etc/hosts', 43, 3, 117);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (210, 'Salt - Rock, Course', '¡™£¢∞§¶•ªº–≠', 45, 10, 158);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (211, 'Ham - Cooked Bayonne Tinned', '　', 47, 10, 125);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (212, 'Tomato - Tricolor Cherry', '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 5, 6, 220);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (213, 'Wine - Red, Cabernet Sauvignon', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 4, 6, 104);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (214, 'Truffle Cups - Brown', '/dev/null; touch /tmp/blns.fail ; echo', 3, 5, 179);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (215, 'Sobe - Berry Energy', '"''"''"''''''''"', 39, 1, 492);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (216, 'Duck - Breast', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 33, 2, 82);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (217, 'Cleaner - Bleach', '0/0', 29, 6, 472);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (218, 'Pepper - Black, Crushed', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 37, 4, 333);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (219, 'Mcguinness - Blue Curacao', '1/2', 7, 1, 196);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (220, 'Wooden Mop Handle', '1/0', 33, 7, 125);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (221, 'Petit Baguette', '<script>alert(''hi'')</script>', 43, 2, 61);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (222, 'Parsley - Dried', '😍', 39, 6, 148);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (223, 'Sage Derby', '1.00', 5, 7, 84);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (224, 'Shrimp - Prawn', 'œ∑´®†¥¨ˆøπ“‘', 19, 9, 372);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (225, 'Wine - German Riesling', '⁦test⁧', 50, 5, 39);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (226, 'Vodka - Smirnoff', '!@#$%^&*()', 19, 8, 382);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (227, 'Ice Cream Bar - Hageen Daz To', 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', 44, 7, 270);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (228, 'Beef - Ground Lean Fresh', '​', 33, 2, 279);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (229, 'Lamb - Bones', '$1.00', 12, 10, 156);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (230, 'Sachet', '"', 20, 6, 102);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (231, 'Country Roll', '　', 42, 3, 419);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (232, 'Marsala - Sperone, Fine, D.o.c.', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 42, 4, 411);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (233, 'Filling - Mince Meat', 'NULL', 1, 4, 210);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (234, 'Vinegar - Sherry', '-1/2', 44, 6, 499);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (235, 'Brandy Cherry - Mcguinness', '''''', 9, 2, 487);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (236, 'Longos - Chicken Caeser Salad', 'null', 18, 4, 416);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (237, 'Oil - Olive', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 41, 10, 369);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (238, 'Rice - Wild', '<img src=x onerror=alert(''hi'') />', 18, 5, 283);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (239, 'Chocolate - Mi - Amere Semi', '田中さんにあげて下さい', 14, 2, 298);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (240, 'Wasabi Powder', '‫test‫', 27, 10, 100);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (241, 'Beer - Paulaner Hefeweisse', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 25, 8, 253);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (242, 'Wine - Red, Concha Y Toro', '﻿', 25, 2, 367);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (243, 'Sugar - White Packet', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 17, 1, 163);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (244, 'Wine - Sherry Dry Sack, William', '!@#$%^&*()', 49, 4, 204);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (245, 'Sauce - Vodka Blush', '"''"''"''''''''"', 11, 5, 429);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (246, 'Sprouts - China Rose', '''''', 15, 3, 321);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (247, 'Pepper - Cayenne', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 11, 5, 335);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (248, 'Bay Leaf Fresh', '١٢٣', 30, 1, 148);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (249, 'Alize Red Passion', '""', 40, 5, 312);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (250, 'Wine - Shiraz Wolf Blass Premium', '🐵 🙈 🙉 🙊', 8, 10, 201);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (251, 'Nacho Chips', 'ÅÍÎÏ˝ÓÔÒÚÆ☃', 28, 8, 135);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (252, 'Chocolate - Compound Coating', '‫test‫', 13, 6, 444);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (253, 'Tuna - Canned, Flaked, Light', 'åß∂ƒ©˙∆˚¬…æ', 29, 9, 424);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (254, 'Banana - Green', 'null', 10, 7, 439);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (255, 'Beef - Chuck, Boneless', '᠎', 47, 8, 443);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (256, 'Beef - Roasted, Cooked', null, 50, 2, 341);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (257, 'Cocoa Powder - Natural', 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', 45, 4, 35);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (258, 'Plums - Red', '"''"''"''''''''"', 23, 1, 484);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (259, 'Towel Dispenser', 'åß∂ƒ©˙∆˚¬…æ', 38, 3, 395);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (260, 'Sprouts - China Rose', '사회과학원 어학연구소', 29, 4, 52);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (261, 'Cake - Bande Of Fruit', 'NIL', 43, 1, 142);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (262, 'Cocoa Butter', '../../../../../../../../../../../etc/hosts', 27, 6, 257);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (263, 'Teriyaki Sauce', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 38, 3, 352);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (264, 'Canadian Emmenthal', '"''"''"''''''''"', 36, 5, 42);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (265, 'Wine - Montecillo Rioja Crianza', '‪‪test‪', 11, 9, 202);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (266, 'Towel - Roll White', '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', 27, 8, 181);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (267, 'Pasta - Linguini, Dry', '1E+02', 3, 1, 406);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (268, 'Steam Pan - Half Size Deep', 'NULL', 20, 3, 66);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (269, 'Mushroom - Morel Frozen', '​', 26, 3, 487);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (270, 'Beer - Creemore', 'ÅÍÎÏ˝ÓÔÒÚÆ☃', 19, 2, 378);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (271, 'Bread - Hamburger Buns', '"''''''''"''"', 29, 10, 186);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (272, 'Crackers - Graham', '<>?:"{}|_+', 27, 9, 442);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (273, 'Cheese - Shred Cheddar / Mozza', '0.00', 6, 7, 213);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (274, 'Tia Maria', '`⁄€‹›ﬁﬂ‡°·‚—±', 45, 4, 449);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (275, 'Tofu - Soft', 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', 7, 6, 2);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (276, 'Soup Campbells', '⁦test⁧', 39, 3, 169);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (277, 'Easy Off Oven Cleaner', '(╯°□°）╯︵ ┻━┻)  ', 47, 8, 377);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (278, 'Pasta - Shells, Medium, Dry', '-1.00', 12, 9, 140);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (279, 'Cheese - Parmesan Grated', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 45, 8, 31);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (280, 'Pate - Cognac', '␢', 20, 8, 86);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (281, 'Soup - Campbells - Tomato', '""', 47, 2, 380);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (282, 'Pepper - White, Ground', '‪‪test‪', 47, 2, 431);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (283, 'Chips - Potato Jalapeno', '１２３', 25, 10, 495);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (284, 'Vanilla Beans', '/dev/null; touch /tmp/blns.fail ; echo', 23, 4, 111);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (285, 'Cheese - Wine', '''''', 23, 10, 201);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (286, 'Cardamon Seed / Pod', 'הָיְתָהtestالصفحات التّحول', 16, 4, 484);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (287, 'Basil - Dry, Rubbed', '"''''''''"''"', 4, 3, 252);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (288, 'Cattail Hearts', '᠎', 5, 5, 463);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (289, 'Sauce - Chili', '﻿', 32, 9, 32);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (290, 'Bread - Olive', '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧', 21, 1, 99);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (291, 'Shichimi Togarashi Peppeers', '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', 7, 1, 74);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (292, 'Liqueur Banana, Ramazzotti', 'הָיְתָהtestالصفحات التّحول', 2, 3, 493);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (293, 'Pasta - Cappellini, Dry', '1/2', 26, 2, 406);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (294, 'Chicken - Thigh, Bone In', '⁰⁴⁵₀₁₂', 32, 5, 19);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (295, 'Tortillas - Flour, 12', '‪‪test‪', 9, 2, 430);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (296, 'Pastry - Banana Tea Loaf', 'הָיְתָהtestالصفحات التّحول', 18, 10, 459);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (297, 'Beer - Mcauslan Apricot', '() { 0; }; touch /tmp/blns.shellshock1.fail;', 26, 8, 131);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (298, 'Flax Seed', '../../../../../../../../../../../etc/passwd%00', 40, 7, 14);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (299, 'Spice - Paprika', 'test⁠test‫', 43, 10, 145);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (300, 'Canada Dry', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 27, 5, 106);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (301, 'Baking Powder', '../../../../../../../../../../../etc/passwd%00', 10, 2, 466);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (302, 'Bagel - Ched Chs Presliced', '0.00', 24, 10, 297);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (303, 'Lamb - Shoulder', '00˙Ɩ$-', 24, 7, 426);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (304, 'Lemonade - Kiwi, 591 Ml', '0/0', 29, 2, 500);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (305, 'Cabbage - Green', '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', 3, 7, 198);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (306, 'Transfer Sheets', '<svg><script>0<1>alert(''XSS'')</script>', 31, 3, 342);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (307, 'Lotus Rootlets - Canned', '␡', 45, 10, 54);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (308, 'Rabbit - Frozen', '../../../../../../../../../../../etc/passwd%00', 23, 9, 68);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (309, 'Cheese - Roquefort Pappillon', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 50, 1, 335);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (310, 'Cheese - Perron Cheddar', '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', 47, 3, 403);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (311, 'Sauce - Demi Glace', '-1/2', 33, 10, 140);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (312, 'Walkers Special Old Whiskey', 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', 33, 6, 30);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (313, 'Sponge Cake Mix - Chocolate', '1.00', 40, 3, 117);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (314, 'Chicken - Whole', '👩🏽', 27, 10, 499);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (315, 'Curry Powder Madras', '｀ｨ(´∀｀∩', 5, 6, 497);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (316, 'Apricots Fresh', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 25, 2, 384);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (317, 'Cinnamon Buns Sticky', '__ﾛ(,_,*)', 48, 6, 203);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (318, 'Madeira', '１２３', 35, 4, 218);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (319, 'Okra', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 13, 7, 410);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (320, 'Cheese - Sheep Milk', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 8, 3, 417);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (321, 'Pastry - Banana Muffin - Mini', '1/0', 12, 5, 466);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (322, 'Wine - Red, Wolf Blass, Yellow', '👩🏽', 46, 3, 108);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (323, 'Cake - Cake Sheet Macaroon', 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', 37, 3, 53);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (324, 'Wine - Rosso Toscano Igt', '울란바토르', 22, 6, 177);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (325, 'Wine - Domaine Boyar Royal', '(╯°□°）╯︵ ┻━┻)  ', 2, 4, 158);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (326, 'Emulsifier', ' ', 11, 9, 437);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (327, 'Sprite - 355 Ml', '0.00', 24, 2, 394);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (328, 'Carbonated Water - Raspberry', '₀₁₂', 18, 10, 207);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (329, 'Cheese - Cheddar, Mild', '../../../../../../../../../../../etc/passwd%00', 32, 8, 108);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (330, 'Extract - Vanilla,artificial', 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', 20, 3, 341);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (331, 'Oil - Hazelnut', '1.00', 7, 8, 158);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (332, 'Sour Puss Raspberry', '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', 12, 8, 372);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (333, 'Gin - Gilbeys London, Dry', '｀ｨ(´∀｀∩', 26, 9, 316);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (334, 'Bread - Calabrese Baguette', '｀ｨ(´∀｀∩', 50, 4, 173);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (335, 'Iced Tea - Lemon, 460 Ml', '🐵 🙈 🙉 🙊', 34, 1, 285);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (336, 'Sultanas', '../../../../../../../../../../../etc/passwd%00', 32, 8, 184);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (337, 'Asparagus - White, Canned', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 37, 6, 195);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (338, 'Bagel - Plain', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 24, 6, 337);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (339, 'Absolut Citron', '1/2', 19, 8, 353);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (340, 'Pail - 4l White, With Handle', '␡', 38, 8, 445);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (341, 'Beer - Mill St Organic', 'Œ„´‰ˇÁ¨ˆØ∏”’', 38, 1, 118);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (342, 'Bay Leaf Fresh', ',./;''[]\-=', 28, 4, 237);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (343, 'Port - 74 Brights', '1E+02', 3, 9, 40);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (344, 'Filling - Mince Meat', '1''; DROP TABLE users--', 8, 5, 288);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (345, 'Kellogs Cereal In A Cup', '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕', 22, 3, 276);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (346, 'Flour - Buckwheat, Dark', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 24, 3, 155);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (347, 'Ketchup - Tomato', '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕', 5, 9, 356);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (348, 'Wine - Alicanca Vinho Verde', '-1E2', 14, 1, 306);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (349, 'Pear - Prickly', '¸˛Ç◊ı˜Â¯˘¿', 42, 4, 15);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (350, 'Ecolab - Power Fusion', '../../../../../../../../../../../etc/passwd%00', 47, 4, 437);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (351, 'Pear - Prickly', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 19, 8, 309);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (352, 'Pepper - Green', '(｡◕ ∀ ◕｡)', 8, 5, 467);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (353, 'Garlic', '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 44, 10, 208);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (354, 'Crackers - Trio', 'Œ„´‰ˇÁ¨ˆØ∏”’', 42, 8, 87);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (355, 'Clams - Bay', '᠎', 10, 10, 22);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (356, 'Mushroom - Morels, Dry', '../../../../../../../../../../../etc/passwd%00', 5, 5, 448);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (357, 'Piping Jelly - All Colours', '␢', 30, 8, 114);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (358, 'Sprouts - Onion', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 41, 5, 433);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (359, 'Jam - Marmalade, Orange', '<img src=x onerror=alert(''hi'') />', 22, 4, 456);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (360, 'Cake - Pancake', 'œ∑´®†¥¨ˆøπ“‘', 43, 2, 117);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (361, 'Soup - Knorr, Chicken Noodle', '!@#$%^&*()', 41, 5, 409);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (362, 'Saskatoon Berries - Frozen', 'test⁠test‫', 12, 10, 466);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (363, 'Nut - Walnut, Chopped', '(╯°□°）╯︵ ┻━┻)  ', 27, 7, 258);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (364, 'Bagel - Everything Presliced', 'NULL', 7, 3, 100);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (365, 'Gatorade - Lemon Lime', '/dev/null; touch /tmp/blns.fail ; echo', 49, 1, 4);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (366, 'Napkin - Dinner, White', '和製漢語', 7, 10, 209);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (367, 'Lamb Rack - Ontario', '$1.00', 25, 2, 214);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (368, 'Chip - Potato Dill Pickle', '00˙Ɩ$-', 48, 4, 119);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (369, 'Wine - White, Pinot Grigio', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 22, 6, 187);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (370, 'Chicken - Base', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 35, 4, 9);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (371, 'Chinese Foods - Thick Noodles', '../../../../../../../../../../../etc/passwd%00', 45, 10, 33);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (372, 'Island Oasis - Strawberry', '　', 8, 10, 159);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (373, 'Carbonated Water - Blackberry', ' ', 26, 10, 391);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (374, 'Jicama', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 25, 5, 20);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (375, 'Lamb Rack - Ontario', '/dev/null; touch /tmp/blns.fail ; echo', 28, 5, 101);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (376, 'Cloves - Ground', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 43, 4, 30);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (377, 'Tart Shells - Savory, 2', '-1E2', 27, 1, 7);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (378, 'Soup - Campbells, Classic Chix', ' test ', 4, 4, 316);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (379, 'Duck - Breast', '｀ｨ(´∀｀∩', 4, 1, 191);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (380, 'Towel Dispenser', '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', 49, 7, 399);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (381, 'Coffee Swiss Choc Almond', '(╯°□°）╯︵ ┻━┻)  ', 34, 1, 264);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (382, 'Sachet', '"''"''"''''''''"', 36, 2, 376);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (383, 'Scallops - In Shell', '和製漢語', 50, 2, 320);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (384, 'Glaze - Apricot', '<script>alert(''hi'')</script>', 8, 4, 110);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (385, 'Crab Meat Claw Pasteurise', '👩🏽', 44, 8, 170);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (386, 'Chilli Paste, Ginger Garlic', null, 43, 5, 110);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (387, 'Jerusalem Artichoke', '() { 0; }; touch /tmp/blns.shellshock1.fail;', 41, 7, 367);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (388, 'Bag Clear 10 Lb', '1''; DROP TABLE users--', 6, 2, 124);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (389, 'Bagel - Plain', '‫test‫', 12, 3, 487);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (390, 'Sloe Gin - Mcguinness', '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧', 10, 5, 230);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (391, 'Soap - Pine Sol Floor Cleaner', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 4, 4, 181);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (392, 'Cheese - Cheddar, Mild', '00˙Ɩ$-', 47, 6, 488);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (393, 'Cucumber - Pickling Ontario', '""', 45, 8, 9);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (394, 'Cookies Almond Hazelnut', '-1.00', 27, 2, 280);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (395, 'Chocolate - Sugar Free Semi Choc', '''''', 43, 1, 371);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (396, 'Apples - Sliced / Wedge', '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧', 46, 5, 142);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (397, 'Phyllo Dough', '"''''''''"''"', 10, 10, 451);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (398, 'Pepper - Red Chili', '¸˛Ç◊ı˜Â¯˘¿', 22, 9, 186);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (399, 'Cheese - Roquefort Pappillon', '𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 10, 4, 15);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (400, 'Chicken - Thigh, Bone In', '-1E02', 19, 1, 193);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (401, 'Longos - Chicken Curried', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 10, 6, 66);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (402, 'Pesto - Primerba, Paste', '1/0', 4, 8, 325);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (403, 'Wine - Magnotta - Pinot Gris Sr', '‫test‫', 14, 6, 318);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (404, 'Wine - Toasted Head', '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', 1, 9, 7);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (405, 'Wine - Remy Pannier Rose', ' test ', 48, 5, 158);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (406, 'Pepper - Red Chili', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 45, 2, 217);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (407, 'Plasticforkblack', 'Œ„´‰ˇÁ¨ˆØ∏”’', 26, 3, 62);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (408, 'Wine - Cotes Du Rhone Parallele', '1/0', 39, 1, 335);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (409, 'Wanton Wrap', '¡™£¢∞§¶•ªº–≠', 15, 4, 260);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (410, 'Wine - Vineland Estate Semi - Dry', '🐵 🙈 🙉 🙊', 5, 1, 65);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (411, 'Cheese - Mozzarella, Shredded', '１２３', 44, 4, 268);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (412, 'Banana - Leaves', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 16, 8, 373);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (413, 'Water - Spring Water, 355 Ml', '・(￣∀￣)・:*:', 28, 4, 443);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (414, 'Split Peas - Green, Dry', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 12, 5, 68);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (415, 'Irish Cream - Butterscotch', '-1E+02', 15, 3, 284);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (416, 'Ecolab Crystal Fusion', '🐵 🙈 🙉 🙊', 7, 2, 305);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (417, 'Nut - Almond, Blanched, Ground', '¸˛Ç◊ı˜Â¯˘¿', 19, 2, 125);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (418, 'Wine - Jackson Triggs Okonagan', '/dev/null; touch /tmp/blns.fail ; echo', 16, 2, 466);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (419, 'Salt - Sea', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 37, 3, 77);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (420, 'Veal - Eye Of Round', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 22, 4, 179);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (421, 'The Pop Shoppe - Cream Soda', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 11, 7, 86);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (422, 'Veal - Shank, Pieces', 'nil', 42, 6, 134);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (423, 'Chicken - Thigh, Bone In', '"', 50, 8, 308);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (424, 'Wine - Zonnebloem Pinotage', '١٢٣', 28, 4, 145);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (425, 'Cheese - Cottage Cheese', '‫test‫', 38, 4, 484);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (426, 'Beer - Fruli', '¸˛Ç◊ı˜Â¯˘¿', 24, 3, 69);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (427, 'Oil - Coconut', '(╯°□°）╯︵ ┻━┻)  ', 21, 5, 410);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (428, 'Lamb - Rack', '和製漢語', 12, 1, 483);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (429, 'Cranberries - Dry', '｀ｨ(´∀｀∩', 11, 7, 295);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (430, 'Potatoes - Instant, Mashed', '(｡◕ ∀ ◕｡)', 7, 10, 230);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (431, 'Liners - Baking Cups', null, 2, 4, 464);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (432, 'Noodles - Cellophane, Thin', '-1/2', 48, 3, 117);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (433, 'Dill Weed - Dry', '-1/2', 20, 6, 317);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (434, 'Creme De Menth - White', '../../../../../../../../../../../etc/hosts', 42, 8, 413);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (435, 'Chicken - Whole Roasting', '!@#$%^&*()', 9, 2, 195);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (436, 'Juice - Apple Cider', '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', 4, 8, 266);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (437, 'Cheese - Parmigiano Reggiano', '﻿', 21, 3, 451);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (438, 'Scallops - Live In Shell', '1''; DROP TABLE users--', 23, 5, 344);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (439, 'Sprouts - China Rose', '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', 21, 2, 8);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (440, 'Chutney Sauce - Mango', '-1', 34, 6, 140);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (441, 'Irish Cream - Baileys', '¡™£¢∞§¶•ªº–≠', 31, 10, 120);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (442, 'Bacardi Breezer - Strawberry', '<svg><script>0<1>alert(''XSS'')</script>', 21, 9, 123);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (443, 'Egg - Salad Premix', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 3, 4, 297);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (444, 'Slt - Individual Portions', '1''; DROP TABLE users--', 1, 4, 414);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (445, 'Coffee - Decaffeinato Coffee', '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', 27, 8, 191);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (446, 'Soup - Campbells, Cream Of', '⁰⁴⁵₀₁₂', 27, 9, 124);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (447, 'Soup Campbells - Tomato Bisque', '1/2', 31, 4, 37);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (448, 'Bread - Sour Sticks With Onion', '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', 22, 9, 143);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (449, 'Wine - Ej Gallo Sonoma', '<script>alert(''hi'')</script>', 35, 6, 405);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (450, 'Wine - Red, Gamay Noir', '사회과학원 어학연구소', 19, 7, 164);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (451, 'Water - Evian 355 Ml', '᠎', 1, 5, 66);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (452, 'Juice - Orangina', 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', 45, 3, 258);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (453, 'Venison - Ground', '1/0', 49, 6, 201);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (454, 'Bag - Clear 7 Lb', 'null', 3, 9, 62);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (455, 'Cup - Translucent 7 Oz Clear', '・(￣∀￣)・:*:', 43, 8, 135);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (456, 'Cheese - Mascarpone', '''"''', 34, 7, 270);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (457, 'Pear - Packum', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 36, 8, 61);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (458, 'Bread Crumbs - Panko', '👩🏽', 39, 9, 164);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (459, 'Muffin Mix - Lemon Cranberry', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 2, 1, 317);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (460, 'Anchovy Paste - 56 G Tube', '-1.00', 43, 5, 114);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (461, 'Nestea - Iced Tea', '0/0', 3, 9, 337);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (462, 'Wine - Muscadet Sur Lie', 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', 50, 6, 63);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (463, 'Chocolate Bar - Smarties', '1''; DROP TABLE users--', 2, 1, 312);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (464, 'Potatoes - Mini Red', '⁰⁴⁵₀₁₂', 46, 4, 440);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (465, 'Tart - Butter Plain Squares', '''', 11, 1, 75);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (466, 'Bread - Roll, Canadian Dinner', '₀₁₂', 18, 10, 411);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (467, 'Gatorade - Fruit Punch', '"''''''''"''"', 31, 8, 415);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (468, 'Oil - Grapeseed Oil', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 2, 6, 347);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (469, 'Nut - Almond, Blanched, Sliced', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 26, 10, 496);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (470, 'Wine - Magnotta, Merlot Sr Vqa', '../../../../../../../../../../../etc/passwd%00', 30, 9, 270);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (471, 'Bread Base - Toscano', '𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 24, 4, 186);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (472, 'Soup - French Onion', ',./;''[]\-=', 30, 8, 51);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (473, 'Pea - Snow', '''''', 26, 10, 311);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (474, 'Island Oasis - Peach Daiquiri', '(╯°□°）╯︵ ┻━┻)  ', 26, 6, 166);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (475, 'Pepper - Red Chili', '‫test‫', 5, 9, 268);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (476, 'Eggroll', '"''"''"''''''''"', 22, 3, 264);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (477, 'Sauce - Soya, Light', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 15, 1, 193);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (478, 'Appetizer - Mini Egg Roll, Shrimp', '﻿', 27, 8, 457);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (479, 'Scallops - U - 10', '・(￣∀￣)・:*:', 15, 6, 462);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (480, 'Food Colouring - Pink', '''"''', 11, 2, 472);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (481, 'Paper Cocktail Umberlla 80 - 180', '-1E+02', 12, 5, 417);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (482, 'Drambuie', '‪‪test‪', 25, 5, 472);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (483, 'Silicone Parch. 16.3x24.3', '⁰⁴⁵', 6, 9, 485);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (484, 'Bread - Bagels, Mini', '-$1.00', 49, 1, 121);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (485, 'Sage - Ground', '1''; DROP TABLE users--', 50, 3, 198);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (486, 'Rice - Jasmine Sented', '울란바토르', 16, 8, 21);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (487, 'Sprouts - Pea', '울란바토르', 20, 6, 92);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (488, 'Soup Campbells - Italian Wedding', '1;DROP TABLE users', 8, 2, 109);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (489, 'Hummus - Spread', ' test ', 45, 6, 435);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (490, 'Pastry - Butterscotch Baked', ',./;''[]\-=', 19, 6, 41);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (491, 'Pastry - Cheese Baked Scones', '''''', 41, 9, 474);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (492, 'Sausage - Liver', 'test⁠test‫', 36, 2, 205);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (493, 'Spice - Greek 1 Step', '울란바토르', 6, 2, 52);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (494, 'Wine - Malbec Trapiche Reserve', '部落格', 13, 4, 443);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (495, 'Cookie Dough - Chocolate Chip', '‫test‫', 19, 5, 124);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (496, 'Beer - Sleemans Honey Brown', 'NULL', 7, 5, 251);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (497, 'Flour - Rye', '-1', 44, 6, 455);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (498, 'Squash - Guords', '''', 8, 3, 438);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (499, 'Tea - Camomele', '1;DROP TABLE users', 7, 6, 5);
insert into plato (id, nombre, descripcion, precio, rating_medio, id_vendedor) values (500, 'Wine - Ej Gallo Sonoma', '​', 42, 2, 470);
