insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (52, 128, 17, 1, 7, '-1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (97, 200, 36, 4, 2, '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (84, 261, 29, 5, 9, '-$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (203, 170, 39, 1, 10, 'test⁠test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (241, 50, 36, 5, 5, '!@#$%^&*()');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (443, 77, 97, 1, 7, '␡');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (26, 203, 18, 3, 6, '社會科學院語學研究所');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (108, 96, 25, 3, 9, '和製漢語');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (235, 465, 74, 4, 8, ',./;''[]\-=');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (58, 169, 29, 3, 5, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (285, 493, 54, 2, 7, '1');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (332, 392, 1, 2, 1, '0.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (477, 179, 28, 5, 6, '・(￣∀￣)・:*:');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (3, 461, 99, 4, 5, '<script>alert(''hi'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (360, 319, 81, 5, 3, 'הָיְתָהtestالصفحات التّحول');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (55, 364, 76, 3, 10, '᠎');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (94, 113, 70, 2, 5, '␡');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (386, 308, 47, 1, 10, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (195, 425, 100, 4, 1, '田中さんにあげて下さい');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (39, 60, 51, 2, 2, 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (472, 241, 59, 4, 3, '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (344, 277, 81, 3, 10, '<>?:"{}|_+');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (159, 204, 33, 5, 1, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (311, 365, 40, 1, 1, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (276, 255, 95, 3, 6, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (446, 51, 50, 3, 7, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (175, 166, 74, 1, 10, '''"''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (178, 15, 39, 2, 8, '‫test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (274, 119, 24, 3, 5, '<img src=x onerror=alert(''hi'') />');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (251, 75, 51, 4, 1, '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (7, 400, 76, 5, 1, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (446, 245, 73, 1, 3, '-$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (196, 99, 88, 3, 9, 'test⁠test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (353, 166, 22, 1, 2, '␢');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (390, 32, 70, 4, 4, '(╯°□°）╯︵ ┻━┻)  ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (339, 95, 77, 2, 4, '﻿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (5, 282, 96, 1, 4, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (198, 285, 53, 5, 2, '__ﾛ(,_,*)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (135, 67, 66, 1, 3, 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (140, 58, 29, 5, 10, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (478, 176, 72, 1, 7, '0/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (62, 497, 47, 4, 1, ' test ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (11, 137, 2, 4, 6, '''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (317, 186, 15, 5, 6, '田中さんにあげて下さい');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (107, 46, 98, 1, 1, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (492, 227, 74, 2, 9, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (444, 191, 7, 5, 4, '1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (474, 443, 9, 2, 5, '<script>alert(''hi'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (326, 440, 35, 5, 10, '(╯°□°）╯︵ ┻━┻)  ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (13, 53, 49, 2, 7, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (359, 193, 12, 3, 4, 'åß∂ƒ©˙∆˚¬…æ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (227, 161, 51, 2, 1, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (457, 167, 35, 4, 6, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (472, 135, 27, 4, 1, '../../../../../../../../../../../etc/passwd%00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (414, 166, 84, 2, 1, 'åß∂ƒ©˙∆˚¬…æ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (469, 374, 92, 3, 3, ',./;''[]\-=');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (286, 140, 24, 4, 5, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (318, 125, 90, 4, 9, '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (474, 425, 27, 3, 9, '00˙Ɩ$-');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (214, 258, 74, 2, 5, '¸˛Ç◊ı˜Â¯˘¿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (28, 412, 93, 3, 3, '␡');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (442, 278, 34, 3, 3, 'NULL');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (262, 14, 30, 1, 10, '''''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (158, 246, 77, 2, 8, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (69, 85, 100, 3, 1, '﻿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (292, 70, 72, 1, 8, '-1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (431, 57, 64, 3, 4, '0.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (304, 120, 49, 4, 5, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (125, 167, 78, 3, 4, '1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (464, 209, 47, 1, 7, '1''; DROP TABLE users--');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (388, 306, 36, 4, 7, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (99, 278, 25, 2, 7, 'nil');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (462, 392, 78, 5, 3, '¸˛Ç◊ı˜Â¯˘¿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (473, 298, 64, 4, 8, '⁦test⁧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (122, 100, 57, 3, 5, '社會科學院語學研究所');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (202, 8, 59, 1, 8, '-1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (335, 389, 5, 1, 3, '-1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (354, 252, 81, 4, 4, '<script>alert(''hi'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (207, 281, 31, 1, 7, ' ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (21, 378, 23, 2, 6, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (1, 230, 49, 3, 1, '⁰⁴⁵');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (310, 20, 87, 5, 10, '👩🏽');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (102, 473, 93, 2, 4, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (181, 64, 38, 3, 4, 'NIL');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (4, 340, 56, 5, 2, '-1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (132, 103, 29, 2, 10, '1''; DROP TABLE users--');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (320, 95, 23, 5, 5, '"''"''"''''''''"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (234, 76, 91, 5, 2, ',./;''[]\-=');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (241, 173, 47, 4, 10, '-1/2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (169, 157, 66, 2, 2, '__ﾛ(,_,*)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (265, 335, 64, 2, 7, '社會科學院語學研究所');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (464, 21, 39, 4, 4, '␢');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (437, 132, 87, 2, 5, '﻿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (400, 216, 59, 2, 6, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (140, 410, 62, 3, 6, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (211, 167, 9, 1, 5, '<script>alert(''hi'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (344, 490, 29, 4, 4, '(｡◕ ∀ ◕｡)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (313, 233, 72, 1, 6, '-1/2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (370, 122, 66, 4, 3, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (303, 434, 94, 4, 7, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (184, 147, 69, 4, 3, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (50, 109, 82, 4, 8, ',./;''[]\-=');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (98, 208, 56, 5, 2, '__ﾛ(,_,*)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (435, 221, 29, 1, 1, '​');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (414, 492, 70, 1, 6, '''''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (346, 438, 24, 4, 7, 'null');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (333, 468, 96, 1, 4, '１２３');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (365, 272, 100, 4, 6, 'test⁠test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (321, 188, 51, 4, 5, '<script>alert(''hi'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (482, 51, 4, 5, 6, '(｡◕ ∀ ◕｡)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (180, 430, 43, 5, 2, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (233, 475, 22, 2, 8, '<script>alert(''hi'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (204, 468, 46, 1, 4, '울란바토르');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (383, 3, 31, 5, 3, '⁰⁴⁵₀₁₂');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (362, 466, 21, 1, 4, '‪‪test‪');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (499, 25, 42, 2, 4, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (242, 212, 27, 4, 5, '​');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (500, 432, 44, 5, 3, '"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (495, 61, 47, 3, 2, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (334, 497, 92, 1, 6, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (313, 204, 47, 2, 3, 'œ∑´®†¥¨ˆøπ“‘');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (102, 63, 85, 5, 4, '社會科學院語學研究所');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (391, 25, 8, 3, 5, '-1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (204, 438, 13, 5, 8, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (68, 396, 48, 2, 8, 'åß∂ƒ©˙∆˚¬…æ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (387, 419, 62, 3, 6, '''"''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (306, 197, 4, 2, 3, '1/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (105, 173, 30, 1, 5, '-1');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (355, 361, 33, 2, 7, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (124, 320, 80, 5, 7, '""');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (155, 39, 28, 5, 1, '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (347, 476, 65, 5, 4, '-$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (27, 389, 69, 5, 9, '''''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (66, 475, 79, 5, 5, 'ÅÍÎÏ˝ÓÔÒÚÆ☃');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (80, 76, 99, 1, 2, '사회과학원 어학연구소');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (155, 385, 42, 5, 6, '␡');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (490, 230, 25, 2, 9, '1');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (265, 21, 95, 3, 10, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (390, 83, 83, 5, 9, '"''"''"''''''''"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (36, 483, 60, 5, 10, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (79, 132, 99, 3, 4, '-1');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (80, 40, 88, 1, 7, '١٢٣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (427, 19, 28, 1, 4, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (366, 381, 81, 3, 1, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (96, 476, 34, 1, 5, 'null');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (324, 440, 71, 1, 4, '和製漢語');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (210, 164, 85, 5, 9, '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (67, 233, 55, 1, 7, '1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (396, 326, 10, 4, 10, '<svg><script>0<1>alert(''XSS'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (200, 85, 89, 5, 9, '1/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (458, 198, 13, 2, 3, '-1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (191, 296, 91, 1, 2, '''"''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (256, 9, 26, 4, 7, '␣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (253, 469, 10, 3, 1, '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (12, 463, 7, 4, 1, '1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (285, 8, 74, 4, 10, '⁰⁴⁵₀₁₂');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (345, 376, 44, 3, 5, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (26, 399, 12, 4, 1, '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (142, 360, 76, 3, 3, '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (408, 57, 24, 3, 2, '1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (287, 175, 31, 5, 7, '../../../../../../../../../../../etc/hosts');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (44, 232, 30, 4, 1, '00˙Ɩ$-');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (368, 68, 86, 4, 9, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (444, 500, 62, 2, 1, '-$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (342, 195, 43, 5, 1, 'test⁠test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (49, 445, 22, 1, 9, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (336, 91, 77, 1, 7, '｀ｨ(´∀｀∩');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (178, 107, 10, 2, 9, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (452, 84, 75, 2, 7, ',./;''[]\-=');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (382, 282, 54, 3, 2, '😍');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (483, 2, 64, 1, 3, '١٢٣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (331, 349, 98, 4, 5, '1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (407, 298, 79, 3, 6, '!@#$%^&*()');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (151, 407, 72, 5, 3, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (262, 157, 18, 2, 10, '울란바토르');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (169, 98, 33, 3, 10, '1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (417, 19, 8, 5, 7, '1');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (330, 385, 10, 3, 5, 'åß∂ƒ©˙∆˚¬…æ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (18, 196, 46, 1, 4, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (320, 364, 24, 4, 6, '・(￣∀￣)・:*:');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (183, 180, 81, 2, 9, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (310, 137, 67, 5, 3, 'Ω≈ç√∫˜µ≤≥÷');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (497, 90, 89, 3, 8, 'NIL');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (157, 96, 66, 1, 1, '(｡◕ ∀ ◕｡)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (477, 283, 80, 2, 4, '울란바토르');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (392, 339, 36, 4, 7, '-1');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (5, 176, 57, 1, 10, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (197, 130, 49, 5, 10, 'Œ„´‰ˇÁ¨ˆØ∏”’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (462, 17, 18, 2, 8, '﻿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (84, 25, 55, 4, 6, '｀ｨ(´∀｀∩');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (386, 488, 47, 3, 2, '社會科學院語學研究所');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (237, 401, 17, 2, 4, '和製漢語');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (486, 464, 96, 1, 1, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (413, 204, 1, 4, 4, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (450, 197, 52, 4, 2, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (391, 102, 28, 3, 3, '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (416, 66, 86, 5, 8, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (187, 306, 42, 4, 6, '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (5, 154, 89, 2, 6, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (433, 420, 55, 2, 2, '🐵 🙈 🙉 🙊');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (274, 436, 52, 4, 10, '00˙Ɩ$-');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (59, 35, 99, 5, 4, ' test ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (411, 101, 26, 3, 5, '00˙Ɩ$-');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (171, 139, 83, 3, 3, '-1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (478, 341, 89, 4, 6, '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (290, 328, 10, 5, 9, ' test ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (152, 347, 17, 5, 10, '1;DROP TABLE users');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (135, 15, 50, 4, 10, '1/2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (455, 223, 77, 4, 8, '-1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (409, 301, 21, 2, 1, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (423, 10, 80, 1, 10, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (424, 278, 88, 1, 6, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (436, 477, 11, 5, 10, 'הָיְתָהtestالصفحات التّحول');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (184, 173, 85, 1, 1, null);
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (74, 492, 18, 5, 8, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (162, 411, 75, 3, 8, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (128, 56, 43, 4, 10, '🐵 🙈 🙉 🙊');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (415, 123, 66, 4, 5, '　');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (488, 281, 47, 1, 5, '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (72, 480, 82, 3, 2, '和製漢語');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (326, 209, 29, 5, 10, '<img src=x onerror=alert(''hi'') />');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (428, 262, 79, 4, 8, '(｡◕ ∀ ◕｡)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (13, 447, 89, 3, 6, 'Œ„´‰ˇÁ¨ˆØ∏”’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (413, 380, 2, 1, 1, '␣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (100, 67, 23, 4, 5, '⁰⁴⁵');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (357, 169, 73, 5, 8, '1/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (161, 166, 31, 3, 5, 'test⁠test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (93, 275, 27, 2, 2, '᠎');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (453, 457, 30, 3, 10, ',./;''[]\-=');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (134, 101, 79, 1, 10, '../../../../../../../../../../../etc/passwd%00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (2, 345, 58, 1, 9, 'åß∂ƒ©˙∆˚¬…æ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (444, 254, 98, 3, 10, 'הָיְתָהtestالصفحات التّحول');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (75, 206, 80, 2, 7, '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (274, 458, 61, 4, 9, 'nil');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (225, 382, 76, 3, 7, '1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (205, 428, 61, 5, 5, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (258, 164, 54, 4, 6, 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (362, 250, 29, 3, 10, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (104, 394, 86, 1, 3, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (226, 69, 37, 2, 8, '0.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (362, 463, 3, 3, 4, '␢');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (137, 79, 87, 4, 7, '　');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (189, 144, 4, 1, 5, '-$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (132, 399, 81, 5, 4, '"''"''"''''''''"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (71, 296, 46, 3, 9, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (275, 464, 49, 1, 2, '(╯°□°）╯︵ ┻━┻)  ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (125, 394, 38, 4, 10, '🐵 🙈 🙉 🙊');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (42, 490, 46, 3, 3, '울란바토르');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (175, 491, 66, 1, 9, '‪‪test‪');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (467, 247, 30, 2, 7, '・(￣∀￣)・:*:');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (232, 412, 44, 3, 6, '␣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (478, 164, 76, 1, 1, 'test⁠test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (192, 234, 28, 2, 4, 'œ∑´®†¥¨ˆøπ“‘');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (378, 56, 17, 2, 1, 'NIL');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (402, 205, 85, 3, 6, '<img src=x onerror=alert(''hi'') />');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (301, 201, 44, 1, 8, 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (27, 43, 56, 3, 2, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (92, 415, 59, 3, 3, '0/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (381, 90, 31, 5, 2, 'test⁠test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (150, 498, 14, 2, 1, '​');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (342, 337, 21, 3, 3, '1;DROP TABLE users');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (424, 149, 49, 1, 8, '""');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (438, 2, 38, 4, 1, '1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (282, 310, 61, 1, 2, '-1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (99, 465, 80, 1, 5, '・(￣∀￣)・:*:');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (98, 329, 73, 1, 4, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (313, 493, 93, 2, 8, 'œ∑´®†¥¨ˆøπ“‘');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (357, 365, 68, 2, 10, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (301, 273, 24, 5, 4, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (262, 457, 90, 2, 4, '１２３');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (479, 473, 59, 5, 5, '社會科學院語學研究所');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (258, 134, 97, 4, 5, '-1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (192, 104, 2, 1, 2, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (403, 140, 35, 5, 1, 'œ∑´®†¥¨ˆøπ“‘');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (120, 444, 77, 3, 4, null);
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (342, 423, 32, 3, 4, '₀₁₂');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (126, 339, 69, 3, 7, 'Œ„´‰ˇÁ¨ˆØ∏”’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (445, 108, 53, 3, 7, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (156, 79, 62, 5, 7, '👩🏽');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (220, 289, 56, 4, 7, '0.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (60, 244, 76, 1, 7, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (137, 368, 73, 4, 5, '<script>alert(''hi'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (70, 461, 36, 3, 2, '1/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (148, 412, 75, 2, 4, '<svg><script>0<1>alert(''XSS'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (387, 355, 1, 1, 6, '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (34, 331, 55, 1, 4, '__ﾛ(,_,*)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (358, 122, 23, 3, 8, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (424, 151, 64, 3, 7, '<svg><script>0<1>alert(''XSS'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (62, 265, 14, 3, 8, '<img src=x onerror=alert(''hi'') />');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (101, 130, 25, 3, 2, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (89, 176, 5, 2, 9, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (300, 174, 59, 3, 2, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (386, 110, 12, 1, 4, 'NIL');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (38, 126, 92, 5, 8, '⁦test⁧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (446, 166, 55, 2, 1, '-1/2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (196, 276, 93, 5, 6, 'null');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (148, 309, 15, 1, 8, '-1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (460, 214, 4, 4, 1, '١٢٣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (168, 306, 66, 5, 2, '''"''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (4, 496, 62, 4, 4, '␣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (451, 224, 72, 2, 8, '1/2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (479, 57, 18, 4, 6, '␣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (303, 253, 32, 4, 2, '田中さんにあげて下さい');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (457, 35, 67, 2, 7, 'パーティーへ行かないか');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (210, 25, 22, 5, 4, '⁰⁴⁵₀₁₂');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (352, 353, 61, 2, 7, 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (137, 329, 96, 4, 3, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (211, 96, 68, 2, 4, '울란바토르');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (176, 264, 76, 2, 8, '⁰⁴⁵');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (229, 359, 88, 2, 5, '0.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (96, 386, 93, 3, 9, '¸˛Ç◊ı˜Â¯˘¿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (435, 57, 27, 5, 7, '・(￣∀￣)・:*:');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (10, 205, 26, 4, 2, '0/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (235, 280, 39, 2, 8, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (276, 290, 8, 5, 1, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (406, 351, 21, 3, 6, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (93, 12, 59, 4, 2, '../../../../../../../../../../../etc/passwd%00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (191, 110, 46, 5, 6, '"''"''"''''''''"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (189, 171, 21, 1, 6, 'nil');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (319, 330, 100, 2, 4, 'null');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (359, 457, 99, 3, 2, 'Œ„´‰ˇÁ¨ˆØ∏”’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (18, 23, 43, 1, 10, '<svg><script>0<1>alert(''XSS'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (234, 455, 40, 3, 5, '1/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (243, 450, 2, 4, 6, ' test ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (19, 423, 31, 4, 5, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (208, 243, 96, 1, 10, '‫test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (223, 433, 56, 1, 9, '울란바토르');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (462, 461, 46, 5, 3, 'Œ„´‰ˇÁ¨ˆØ∏”’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (110, 337, 31, 1, 4, '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (399, 183, 59, 5, 5, 'ÅÍÎÏ˝ÓÔÒÚÆ☃');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (359, 129, 95, 1, 6, '😍');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (208, 201, 3, 1, 3, '﻿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (314, 223, 15, 5, 6, '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (289, 128, 52, 1, 5, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (496, 65, 21, 3, 7, '""');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (491, 396, 11, 1, 1, '👩🏽');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (364, 357, 100, 4, 6, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (223, 138, 30, 1, 8, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (234, 396, 93, 5, 1, '１２３');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (249, 466, 9, 3, 1, '1');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (487, 207, 43, 1, 10, '社會科學院語學研究所');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (182, 226, 66, 2, 1, '__ﾛ(,_,*)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (470, 386, 73, 1, 10, '-1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (254, 125, 69, 5, 4, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (402, 28, 65, 1, 5, '"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (227, 234, 35, 2, 4, '""');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (107, 443, 61, 3, 6, '-1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (487, 397, 14, 2, 9, '1''; DROP TABLE users--');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (377, 143, 84, 3, 6, '１２３');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (40, 467, 69, 2, 1, '(╯°□°）╯︵ ┻━┻)  ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (337, 440, 2, 3, 8, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (171, 463, 97, 1, 9, '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (296, 418, 58, 1, 10, '사회과학원 어학연구소');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (392, 14, 14, 3, 3, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (490, 260, 19, 4, 1, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (364, 16, 88, 5, 7, '😍');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (23, 474, 9, 2, 4, '　');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (35, 272, 17, 2, 1, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (87, 200, 57, 5, 8, '"''"''"''''''''"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (99, 249, 95, 5, 10, 'test⁠test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (199, 392, 71, 5, 7, '$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (156, 255, 65, 4, 8, '0/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (421, 69, 48, 3, 1, '・(￣∀￣)・:*:');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (389, 74, 38, 4, 3, '../../../../../../../../../../../etc/passwd%00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (245, 144, 54, 1, 6, '''"''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (365, 45, 7, 2, 10, '''"''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (418, 461, 52, 1, 5, '<img src=x onerror=alert(''hi'') />');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (265, 428, 32, 3, 10, 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (162, 166, 71, 5, 9, '‫test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (309, 431, 32, 1, 6, '0.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (162, 20, 25, 4, 5, '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (116, 347, 17, 3, 7, '0.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (49, 320, 54, 2, 8, '1;DROP TABLE users');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (9, 67, 56, 4, 9, '"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (392, 166, 45, 1, 6, '‪‪test‪');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (250, 310, 18, 4, 2, 'NULL');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (494, 335, 36, 4, 7, '⁰⁴⁵');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (97, 379, 95, 5, 2, '‫test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (353, 310, 70, 5, 2, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (8, 289, 14, 3, 5, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (305, 415, 46, 4, 5, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (216, 349, 7, 5, 7, '᠎');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (368, 262, 73, 5, 8, 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (211, 463, 60, 2, 10, '-1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (267, 391, 87, 2, 10, null);
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (357, 67, 7, 5, 4, '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (25, 384, 49, 1, 6, '1');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (271, 367, 55, 1, 10, '　');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (259, 363, 66, 4, 4, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (476, 302, 81, 2, 5, '᠎');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (194, 210, 82, 4, 10, '0/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (145, 467, 81, 4, 7, '''"''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (485, 44, 84, 2, 4, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (395, 13, 36, 1, 10, '""');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (283, 376, 42, 4, 9, '<svg><script>0<1>alert(''XSS'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (411, 192, 24, 1, 8, '1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (105, 373, 62, 2, 5, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (370, 362, 98, 3, 9, '​');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (202, 222, 90, 3, 5, '울란바토르');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (374, 149, 25, 1, 5, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (420, 497, 57, 3, 6, 'null');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (382, 3, 45, 2, 7, 'Ω≈ç√∫˜µ≤≥÷');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (186, 398, 41, 1, 3, '1/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (339, 67, 47, 3, 1, '🐵 🙈 🙉 🙊');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (424, 49, 100, 1, 6, '"''"''"''''''''"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (122, 152, 79, 2, 10, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (213, 202, 80, 3, 9, '😍');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (464, 97, 95, 4, 9, '-$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (13, 211, 29, 2, 6, '0/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (263, 470, 50, 1, 2, '⁦test⁧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (316, 273, 51, 5, 7, '""');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (162, 375, 86, 5, 8, '1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (203, 337, 37, 1, 7, '0/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (90, 255, 64, 4, 3, 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (33, 308, 14, 2, 6, '-1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (122, 124, 86, 5, 1, '🐵 🙈 🙉 🙊');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (138, 312, 36, 3, 6, 'nil');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (485, 416, 63, 2, 9, '1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (133, 33, 63, 5, 6, ',./;''[]\-=');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (45, 20, 73, 4, 7, '١٢٣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (290, 433, 66, 2, 7, '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (173, 83, 78, 4, 7, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (349, 59, 8, 2, 7, '田中さんにあげて下さい');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (150, 236, 22, 4, 1, '''''');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (350, 259, 90, 5, 5, '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (182, 119, 45, 1, 7, '-1E02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (194, 354, 99, 3, 2, '‫test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (404, 500, 79, 5, 4, '0/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (342, 78, 39, 4, 2, 'NULL');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (476, 202, 55, 2, 1, '₀₁₂');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (490, 242, 92, 4, 2, '﻿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (485, 366, 12, 3, 7, '"');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (266, 441, 100, 2, 4, ' test ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (339, 416, 63, 1, 6, '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (140, 205, 35, 3, 3, '​');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (462, 168, 42, 1, 6, '⁦test⁧');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (61, 120, 86, 1, 2, 'test⁠test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (277, 252, 7, 2, 5, '‫test‫');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (476, 135, 50, 4, 8, ' ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (179, 205, 14, 3, 6, '__ﾛ(,_,*)');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (369, 115, 87, 3, 5, null);
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (287, 252, 72, 1, 9, '和製漢語');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (408, 499, 18, 1, 9, '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (61, 474, 8, 3, 2, '-1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (109, 216, 47, 4, 10, '١٢٣');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (451, 109, 63, 1, 5, '部落格');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (309, 438, 53, 2, 7, '../../../../../../../../../../../etc/hosts');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (330, 234, 63, 4, 8, ' ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (204, 450, 52, 3, 8, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (53, 274, 63, 5, 4, '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (301, 340, 84, 4, 7, '<>?:"{}|_+');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (391, 108, 93, 3, 3, '␢');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (464, 326, 89, 4, 3, '⁰⁴⁵₀₁₂');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (306, 408, 17, 3, 1, 'הָיְתָהtestالصفحات التّحول');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (420, 373, 92, 5, 4, 'パーティーへ行かないか');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (364, 150, 46, 5, 4, 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (232, 498, 99, 5, 6, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (135, 123, 48, 2, 10, '$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (196, 72, 54, 5, 1, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (239, 68, 49, 2, 6, '!@#$%^&*()');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (264, 205, 26, 5, 8, '/dev/null; touch /tmp/blns.fail ; echo');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (251, 317, 25, 3, 5, '../../../../../../../../../../../etc/hosts');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (75, 36, 5, 1, 8, ' ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (472, 220, 21, 3, 1, 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (460, 40, 77, 3, 6, '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (71, 20, 34, 2, 1, '""');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (60, 466, 11, 4, 7, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (222, 302, 1, 3, 7, '1/0');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (129, 237, 66, 2, 2, '00˙Ɩ$-');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (203, 118, 83, 4, 6, '$1.00');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (203, 379, 25, 4, 1, '１２３');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (95, 482, 2, 2, 7, 'åß∂ƒ©˙∆˚¬…æ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (473, 448, 76, 3, 10, '1;DROP TABLE users');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (150, 386, 93, 3, 4, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (295, 299, 39, 4, 8, '-1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (378, 196, 42, 2, 9, ' test ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (431, 57, 4, 4, 7, '᠎');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (259, 465, 52, 4, 5, '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (70, 5, 83, 2, 6, '(╯°□°）╯︵ ┻━┻)  ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (307, 169, 47, 1, 7, 'åß∂ƒ©˙∆˚¬…æ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (195, 402, 79, 1, 1, '<svg><script>0<1>alert(''XSS'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (385, 40, 86, 3, 3, '-1/2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (264, 303, 42, 2, 9, 'ÅÍÎÏ˝ÓÔÒÚÆ☃');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (245, 367, 45, 1, 5, '᠎');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (150, 419, 14, 2, 2, '᠎');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (71, 343, 52, 5, 1, '¡™£¢∞§¶•ªº–≠');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (441, 81, 96, 5, 10, 'Ω≈ç√∫˜µ≤≥÷');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (134, 58, 31, 4, 7, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (437, 310, 28, 5, 5, '1''; DROP TABLE users--');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (267, 219, 66, 4, 6, '1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (112, 296, 77, 4, 2, '-1E+02');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (243, 450, 53, 1, 1, '<svg><script>0<1>alert(''XSS'')</script>');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (179, 356, 18, 4, 1, ' test ');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (466, 317, 33, 5, 2, 'null');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (322, 277, 42, 1, 1, ',./;''[]\-=');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (72, 41, 70, 5, 1, '👩🏽');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (448, 337, 26, 5, 8, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (258, 436, 100, 1, 3, '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (236, 251, 28, 5, 5, '1E2');
insert into carrito_platos (id_carrito, id_plato, precio, cantidad, rating, comentario) values (354, 53, 6, 5, 4, ' ');
