insert into usuario_local (id_usuario, id_local, rating, comentario) values (69, 494, 6, '<svg><script>0<1>alert(''XSS'')</script>');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (71, 147, 5, '1''; DROP TABLE users--');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (385, 367, 6, '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (175, 499, 6, 'œ∑´®†¥¨ˆøπ“‘');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (494, 274, 9, '␢');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (242, 291, 7, '"''"''"''''''''"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (459, 411, 6, '部落格');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (471, 448, 8, 'œ∑´®†¥¨ˆøπ“‘');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (67, 251, 5, 'test⁠test‫');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (344, 106, 6, '١٢٣');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (485, 392, 4, 'nil');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (9, 206, 1, '../../../../../../../../../../../etc/hosts');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (85, 73, 8, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (267, 456, 9, '<img src=x onerror=alert(''hi'') />');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (52, 455, 7, '!@#$%^&*()');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (322, 426, 2, '‪‪test‪');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (449, 130, 3, '00˙Ɩ$-');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (353, 132, 8, '"''''''''"''"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (14, 256, 1, '　');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (497, 294, 4, '-1');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (68, 475, 9, '🐵 🙈 🙉 🙊');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (17, 103, 4, 'œ∑´®†¥¨ˆøπ“‘');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (287, 481, 7, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (25, 27, 7, ',./;''[]\-=');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (321, 407, 9, '-$1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (26, 469, 4, '⁰⁴⁵');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (10, 311, 8, '␡');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (163, 473, 1, '-$1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (338, 126, 5, '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (197, 283, 6, '''"''');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (379, 463, 3, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (368, 374, 5, '!@#$%^&*()');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (88, 285, 1, '　');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (30, 489, 4, 'null');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (193, 348, 8, '사회과학원 어학연구소');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (271, 120, 6, '-1/2');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (357, 397, 9, ' ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (239, 222, 6, '‪‪test‪');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (248, 69, 4, '和製漢語');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (258, 132, 9, '1;DROP TABLE users');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (292, 452, 1, '1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (402, 131, 1, '"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (499, 362, 2, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (73, 225, 8, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (140, 59, 4, '-$1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (453, 134, 9, '¡™£¢∞§¶•ªº–≠');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (253, 244, 5, '部落格');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (314, 490, 2, '-1E+02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (45, 156, 2, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (401, 155, 8, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (423, 417, 5, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (149, 244, 7, '-1/2');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (141, 350, 2, '‪‪test‪');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (288, 281, 8, '''"''');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (383, 406, 8, '"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (277, 216, 4, '0.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (459, 488, 8, '../../../../../../../../../../../etc/hosts');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (178, 477, 1, '''"''');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (180, 75, 5, '-1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (210, 416, 8, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (15, 463, 5, '1/0');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (14, 102, 2, '1');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (234, 66, 8, '"''''''''"''"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (172, 120, 7, '1E2');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (273, 24, 9, '¸˛Ç◊ı˜Â¯˘¿');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (263, 345, 1, '0.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (429, 29, 6, ' test ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (430, 131, 10, '社會科學院語學研究所');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (231, 211, 6, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (232, 222, 4, 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (296, 55, 7, '''"''');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (395, 144, 7, '‪‪test‪');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (445, 461, 6, 'NULL');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (361, 217, 8, 'パーティーへ行かないか');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (376, 1, 1, '(╯°□°）╯︵ ┻━┻)  ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (18, 297, 4, 'הָיְתָהtestالصفحات التّحول');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (112, 116, 9, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (418, 484, 6, '<script>alert(''hi'')</script>');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (189, 397, 7, '田中さんにあげて下さい');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (437, 97, 4, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (128, 93, 1, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (239, 200, 9, '../../../../../../../../../../../etc/hosts');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (345, 373, 2, 'œ∑´®†¥¨ˆøπ“‘');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (185, 6, 1, '😍');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (124, 354, 7, '-1');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (24, 379, 4, 'œ∑´®†¥¨ˆøπ“‘');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (268, 279, 3, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (71, 213, 5, '👩🏽');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (394, 373, 9, '/dev/null; touch /tmp/blns.fail ; echo');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (179, 258, 7, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (448, 141, 6, 'ÅÍÎÏ˝ÓÔÒÚÆ☃');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (7, 358, 2, '0/0');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (109, 228, 5, '사회과학원 어학연구소');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (355, 459, 6, '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (317, 125, 4, '../../../../../../../../../../../etc/hosts');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (1, 248, 8, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (143, 203, 9, '''');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (24, 473, 3, '␢');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (22, 412, 6, '1E02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (331, 405, 7, null);
insert into usuario_local (id_usuario, id_local, rating, comentario) values (269, 196, 7, '﻿');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (235, 381, 2, ' test ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (383, 279, 1, '␢');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (214, 137, 2, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (330, 278, 9, '1/2');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (344, 451, 5, 'הָיְתָהtestالصفحات التّحول');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (275, 390, 4, '(╯°□°）╯︵ ┻━┻)  ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (382, 181, 2, '""');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (28, 412, 7, '・(￣∀￣)・:*:');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (354, 52, 10, 'nil');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (139, 133, 10, '"''''''''"''"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (287, 52, 7, 'test⁠test‫');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (99, 442, 2, '(╯°□°）╯︵ ┻━┻)  ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (364, 449, 3, '../../../../../../../../../../../etc/hosts');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (251, 252, 4, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (384, 10, 10, '-1E+02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (35, 184, 8, '$1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (339, 122, 6, '1E+02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (145, 49, 8, '1E2');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (410, 287, 5, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (287, 151, 4, '00˙Ɩ$-');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (396, 122, 3, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (58, 464, 6, '-1');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (61, 301, 4, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (157, 484, 5, 'nil');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (232, 107, 2, '¸˛Ç◊ı˜Â¯˘¿');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (121, 195, 8, '<svg><script>0<1>alert(''XSS'')</script>');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (180, 280, 9, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (136, 159, 5, ',./;''[]\-=');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (395, 421, 6, '₀₁₂');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (477, 119, 6, '''"''');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (129, 3, 2, '1');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (414, 212, 10, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (403, 168, 3, '$1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (480, 54, 7, '⁰⁴⁵₀₁₂');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (491, 81, 10, '　');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (218, 236, 3, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (73, 179, 10, 'null');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (228, 2, 7, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (184, 414, 3, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (151, 58, 8, '⁰⁴⁵₀₁₂');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (8, 292, 4, '⁰⁴⁵₀₁₂');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (277, 15, 8, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (197, 426, 10, 'null');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (115, 383, 7, '__ﾛ(,_,*)');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (397, 154, 8, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (421, 28, 3, '⁰⁴⁵₀₁₂');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (412, 413, 6, 'Ω≈ç√∫˜µ≤≥÷');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (311, 137, 6, '../../../../../../../../../../../etc/hosts');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (458, 258, 7, '-$1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (188, 196, 1, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (436, 480, 8, '-1E+02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (369, 151, 3, '사회과학원 어학연구소');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (195, 197, 2, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (462, 334, 4, '""');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (452, 245, 2, '和製漢語');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (148, 84, 1, 'null');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (221, 84, 5, '␡');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (392, 113, 9, '../../../../../../../../../../../etc/passwd%00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (133, 38, 5, '사회과학원 어학연구소');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (84, 343, 3, 'null');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (131, 283, 10, '１２３');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (449, 124, 6, '١٢٣');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (322, 107, 5, '1/0');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (489, 3, 8, '١٢٣');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (497, 123, 4, '0/0');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (424, 149, 7, '0/0');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (251, 96, 9, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (285, 96, 2, '0/0');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (171, 8, 3, '사회과학원 어학연구소');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (140, 466, 5, null);
insert into usuario_local (id_usuario, id_local, rating, comentario) values (456, 116, 9, 'åß∂ƒ©˙∆˚¬…æ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (378, 235, 7, 'NIL');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (277, 65, 3, '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (475, 224, 9, '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (56, 160, 3, 'ÅÍÎÏ˝ÓÔÒÚÆ☃');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (244, 474, 6, '-1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (176, 468, 9, '1E2');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (283, 292, 3, '¸˛Ç◊ı˜Â¯˘¿');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (404, 160, 8, '1/0');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (44, 446, 5, '👩🏽');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (48, 310, 6, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (446, 51, 1, 'パーティーへ行かないか');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (293, 264, 2, '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (227, 228, 10, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (353, 481, 6, '社會科學院語學研究所');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (33, 31, 4, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (372, 356, 6, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (187, 300, 7, '｀ｨ(´∀｀∩');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (176, 334, 1, '1;DROP TABLE users');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (65, 166, 1, '😍');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (216, 391, 6, '!@#$%^&*()');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (104, 198, 5, '/dev/null; touch /tmp/blns.fail ; echo');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (205, 193, 9, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (434, 248, 2, '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (70, 491, 3, 'nil');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (255, 464, 5, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (322, 343, 9, '1/2');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (188, 377, 4, '-1/2');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (467, 447, 4, '👩🏽');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (200, 389, 5, '''');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (253, 137, 7, '‪‪test‪');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (168, 24, 9, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (381, 479, 6, 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (247, 260, 9, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (266, 337, 8, '''''');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (234, 341, 10, '$1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (381, 466, 10, '울란바토르');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (491, 440, 6, '"''''''''"''"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (477, 154, 3, 'NULL');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (241, 219, 5, 'パーティーへ行かないか');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (425, 211, 1, '¸˛Ç◊ı˜Â¯˘¿');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (348, 181, 4, '｀ｨ(´∀｀∩');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (431, 298, 1, '⁰⁴⁵₀₁₂');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (60, 321, 8, 'åß∂ƒ©˙∆˚¬…æ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (33, 151, 1, '₀₁₂');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (430, 191, 2, '-1/2');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (6, 452, 7, '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (199, 184, 5, '😍');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (262, 173, 9, '''"''');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (396, 16, 10, '1/0');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (236, 391, 9, ',./;''[]\-=');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (492, 35, 4, '⁰⁴⁵₀₁₂');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (337, 462, 2, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (67, 441, 4, '1E02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (345, 173, 10, '1''; DROP TABLE users--');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (183, 404, 4, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (92, 260, 1, '¸˛Ç◊ı˜Â¯˘¿');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (291, 12, 10, '<img src=x onerror=alert(''hi'') />');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (126, 182, 4, '␢');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (180, 177, 8, '⁰⁴⁵₀₁₂');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (422, 155, 7, '0/0');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (272, 104, 8, '␢');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (26, 183, 2, 'null');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (67, 135, 2, '<script>alert(''hi'')</script>');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (245, 60, 7, ' ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (126, 242, 8, '١٢٣');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (300, 14, 1, '部落格');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (447, 109, 4, '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (68, 214, 5, '␣');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (169, 279, 7, 'הָיְתָהtestالصفحات التّحول');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (39, 376, 9, '1/0');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (382, 138, 3, '部落格');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (467, 160, 3, ',./;''[]\-=');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (117, 298, 2, '　');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (423, 315, 6, null);
insert into usuario_local (id_usuario, id_local, rating, comentario) values (423, 370, 10, '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (21, 75, 7, '-1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (59, 155, 2, 'nil');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (96, 31, 7, '00˙Ɩ$-');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (342, 61, 2, '-$1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (225, 336, 9, '"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (268, 222, 4, 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (447, 459, 6, '<svg><script>0<1>alert(''XSS'')</script>');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (40, 487, 7, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (197, 257, 2, '''''');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (181, 197, 1, '1;DROP TABLE users');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (228, 34, 9, '0/0');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (466, 212, 7, '‫test‫');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (350, 242, 5, ' ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (23, 462, 10, '"''"''"''''''''"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (336, 448, 6, ',./;''[]\-=');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (180, 14, 2, ',./;''[]\-=');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (246, 426, 2, '"''"''"''''''''"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (163, 178, 7, '/dev/null; touch /tmp/blns.fail ; echo');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (178, 249, 9, '田中さんにあげて下さい');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (175, 419, 9, '₀₁₂');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (130, 229, 3, '사회과학원 어학연구소');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (8, 498, 3, ',./;''[]\-=');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (70, 395, 2, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (265, 38, 7, '$1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (26, 307, 7, '-1/2');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (356, 53, 2, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (339, 85, 7, '00˙Ɩ$-');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (227, 12, 4, '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (183, 42, 5, '社會科學院語學研究所');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (240, 409, 10, '-$1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (417, 44, 1, '''');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (452, 19, 9, '''''');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (422, 19, 2, 'test⁠test‫');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (478, 436, 4, '｀ｨ(´∀｀∩');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (391, 388, 1, '-1E+02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (44, 390, 1, 'הָיְתָהtestالصفحات التّحول');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (154, 279, 9, '""');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (448, 478, 7, 'NULL');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (305, 314, 7, '-1E02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (12, 130, 3, '1E02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (103, 340, 6, '1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (223, 329, 10, '１２３');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (376, 256, 7, '울란바토르');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (230, 192, 3, '᠎');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (17, 18, 1, '""');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (371, 317, 9, '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (421, 327, 6, '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (367, 435, 4, 'NULL');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (36, 147, 10, '-1E2');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (147, 283, 10, '-$1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (366, 123, 2, '울란바토르');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (49, 161, 10, '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (390, 1, 4, '<svg><script>0<1>alert(''XSS'')</script>');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (474, 208, 9, '0.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (278, 244, 7, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (368, 337, 5, '''"''');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (486, 86, 6, 'הָיְתָהtestالصفحات التّحول');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (249, 193, 10, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (141, 106, 7, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (365, 222, 8, '/dev/null; touch /tmp/blns.fail ; echo');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (35, 203, 1, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (83, 178, 2, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (458, 171, 5, '-1E+02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (88, 286, 9, '<script>alert(''hi'')</script>');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (493, 31, 7, '・(￣∀￣)・:*:');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (158, 335, 4, '<svg><script>0<1>alert(''XSS'')</script>');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (171, 465, 6, '␣');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (343, 357, 5, '‫test‫');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (409, 34, 2, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (181, 316, 7, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (33, 358, 7, '-1E+02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (105, 222, 9, 'Œ„´‰ˇÁ¨ˆØ∏”’');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (376, 44, 10, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (14, 204, 9, 'NULL');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (283, 290, 5, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (275, 330, 4, '​');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (430, 364, 8, '1/0');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (177, 306, 9, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (162, 256, 7, '¡™£¢∞§¶•ªº–≠');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (371, 262, 9, '""');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (233, 25, 8, '和製漢語');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (177, 439, 10, '../../../../../../../../../../../etc/hosts');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (179, 131, 6, '<script>alert(''hi'')</script>');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (209, 271, 3, '・(￣∀￣)・:*:');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (150, 94, 3, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (234, 338, 7, '１２３');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (149, 132, 6, ',./;''[]\-=');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (21, 360, 9, '部落格');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (155, 442, 10, '‫test‫');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (219, 473, 3, 'הָיְתָהtestالصفحات التّحول');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (251, 3, 1, '𠜎𠜱𠝹𠱓𠱸𠲖𠳏');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (373, 396, 10, '⁰⁴⁵');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (213, 363, 3, 'test⁠test‫');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (63, 3, 8, '-1E02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (316, 476, 6, '''''');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (312, 319, 8, '(｡◕ ∀ ◕｡)');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (348, 288, 4, '<img src=x onerror=alert(''hi'') />');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (293, 229, 10, '""');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (484, 191, 7, '﻿');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (403, 274, 9, 'NIL');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (367, 438, 10, 'null');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (269, 311, 3, '１２３');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (183, 144, 5, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (132, 453, 7, 'Œ„´‰ˇÁ¨ˆØ∏”’');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (407, 142, 3, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (284, 196, 7, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (357, 471, 6, '1');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (313, 78, 9, '¡™£¢∞§¶•ªº–≠');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (53, 46, 7, '⁰⁴⁵');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (38, 20, 3, '00˙Ɩ$-');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (417, 131, 6, 'test⁠test‫');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (387, 149, 1, '᠎');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (413, 334, 10, '‫test‫');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (363, 249, 1, '部落格');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (99, 25, 9, '⁰⁴⁵₀₁₂');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (66, 465, 5, '"''''''''"''"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (343, 210, 3, '‫test‫');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (181, 378, 10, '田中さんにあげて下さい');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (162, 347, 10, '1;DROP TABLE users');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (202, 312, 2, 'Ω≈ç√∫˜µ≤≥÷');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (79, 82, 6, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (436, 17, 6, '-1E02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (230, 462, 7, '田中さんにあげて下さい');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (200, 490, 8, null);
insert into usuario_local (id_usuario, id_local, rating, comentario) values (229, 377, 9, ' ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (233, 122, 5, 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (261, 227, 2, 'ÅÍÎÏ˝ÓÔÒÚÆ☃');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (57, 66, 2, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (91, 310, 7, 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (270, 33, 8, '😍');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (120, 112, 4, '1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (243, 393, 1, '0/0');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (230, 325, 10, '␡');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (24, 63, 2, '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (322, 255, 7, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (439, 26, 4, 'Œ„´‰ˇÁ¨ˆØ∏”’');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (345, 205, 9, '"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (100, 4, 4, '・(￣∀￣)・:*:');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (81, 78, 1, '​');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (120, 66, 7, 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (190, 64, 4, '１２３');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (336, 279, 7, 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (497, 291, 1, '😍');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (457, 371, 9, 'パーティーへ行かないか');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (46, 399, 1, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (427, 492, 7, '/dev/null; touch /tmp/blns.fail ; echo');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (137, 333, 7, '<>?:"{}|_+');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (72, 214, 7, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (122, 205, 9, '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (389, 87, 6, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (263, 108, 9, '"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (205, 334, 10, 'NIL');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (500, 290, 5, '-$1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (261, 87, 9, '😍');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (120, 77, 7, '-1E2');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (205, 429, 2, '"''"''"''''''''"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (103, 189, 8, '｀ｨ(´∀｀∩');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (314, 296, 5, '-1E02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (481, 417, 5, '😍');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (351, 354, 5, 'ÅÍÎÏ˝ÓÔÒÚÆ☃');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (460, 2, 7, '__ﾛ(,_,*)');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (36, 235, 8, '1/2');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (9, 29, 3, '-1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (364, 349, 3, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (475, 435, 3, '울란바토르');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (306, 283, 2, 'åß∂ƒ©˙∆˚¬…æ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (115, 71, 5, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (36, 230, 4, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (378, 7, 1, '1/0');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (72, 451, 3, '/dev/null; touch /tmp/blns.fail ; echo');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (55, 338, 5, 'null');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (363, 312, 10, '!@#$%^&*()');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (145, 355, 1, '␢');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (142, 311, 7, '00˙Ɩ$-');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (154, 43, 9, '⁰⁴⁵');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (318, 70, 5, ',./;''[]\-=');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (12, 48, 1, '1/2');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (110, 18, 4, 'NULL');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (426, 242, 1, '(｡◕ ∀ ◕｡)');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (328, 369, 7, '"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (139, 323, 9, '-1E+02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (224, 139, 3, 'NIL');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (381, 419, 4, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (87, 126, 9, '1''; DROP TABLE users--');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (58, 24, 4, '-1E2');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (221, 260, 5, '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (47, 181, 3, '-1E+02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (273, 310, 3, '울란바토르');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (275, 264, 8, '-1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (213, 364, 9, 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (97, 139, 10, '₀₁₂');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (119, 391, 3, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (406, 92, 9, 'הָיְתָהtestالصفحات التّحول');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (494, 23, 6, '!@#$%^&*()');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (367, 135, 1, '‫test‫');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (272, 174, 3, '社會科學院語學研究所');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (408, 374, 5, '"''''''''"''"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (249, 413, 2, '1;DROP TABLE users');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (496, 396, 7, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (146, 273, 6, '1E02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (396, 68, 10, 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (481, 324, 10, '__ﾛ(,_,*)');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (374, 308, 8, '‫test‫');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (370, 364, 8, '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (66, 435, 9, '-1E+02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (59, 263, 7, '__ﾛ(,_,*)');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (465, 229, 7, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (27, 19, 1, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (365, 63, 6, '(╯°□°）╯︵ ┻━┻)  ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (198, 484, 4, 'Ω≈ç√∫˜µ≤≥÷');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (308, 334, 4, '␢');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (27, 359, 8, '-1');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (225, 120, 2, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (467, 223, 5, '᠎');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (34, 433, 7, 'パーティーへ行かないか');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (11, 137, 6, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (12, 438, 10, 'nil');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (161, 6, 6, '・(￣∀￣)・:*:');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (338, 140, 6, '../../../../../../../../../../../etc/hosts');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (345, 37, 7, '🐵 🙈 🙉 🙊');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (95, 38, 1, '"''''''''"''"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (152, 260, 1, '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (492, 364, 9, '$1.00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (115, 98, 5, 'œ∑´®†¥¨ˆøπ“‘');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (231, 392, 1, null);
insert into usuario_local (id_usuario, id_local, rating, comentario) values (185, 245, 9, ' test ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (93, 378, 8, '../../../../../../../../../../../etc/passwd%00');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (104, 157, 2, '(╯°□°）╯︵ ┻━┻)  ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (291, 475, 1, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (118, 370, 4, '١٢٣');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (308, 127, 6, ' ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (494, 413, 9, '울란바토르');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (25, 282, 7, '1/0');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (478, 56, 2, ' ');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (392, 177, 7, '部落格');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (336, 340, 6, '᠎');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (12, 346, 2, ',./;''[]\-=');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (321, 400, 4, '社會科學院語學研究所');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (5, 120, 3, '/dev/null; touch /tmp/blns.fail ; echo');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (87, 304, 4, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (134, 393, 4, '🐵 🙈 🙉 🙊');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (74, 155, 5, 'パーティーへ行かないか');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (2, 387, 9, '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (175, 441, 6, '<svg><script>0<1>alert(''XSS'')</script>');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (28, 27, 5, 'nil');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (1, 485, 6, '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (449, 386, 5, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (317, 163, 5, '1E+02');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (444, 48, 7, '"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (274, 387, 8, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (380, 453, 1, '사회과학원 어학연구소');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (462, 19, 6, '"''"''"''''''''"');
insert into usuario_local (id_usuario, id_local, rating, comentario) values (460, 134, 5, '../../../../../../../../../../../etc/hosts');
